(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.ClashCalendarCore = api;
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  var KEYWORDS = {
    free: ['무료','선물','보상','재화','쿠폰','링크','보너스','free','gift','reward','bonus'],
    event: ['이벤트','기념','event','anniversary'],
    update: ['업데이트','패치','update','patch']
  };
  function pad(n) { return String(n).padStart(2, '0'); }
  function iso(y,m,d) { return y + '-' + pad(m) + '-' + pad(d); }
  function daysInMonth(y,m) { return new Date(Date.UTC(y,m,0)).getUTCDate(); }
  function classifyNews(title) {
    var s = String(title || '').toLocaleLowerCase();
    var categories = ['official-news'];
    Object.keys(KEYWORDS).forEach(function (key) {
      if (KEYWORDS[key].some(function (word) { return s.indexOf(word.toLocaleLowerCase()) !== -1; })) categories.push(key);
    });
    return categories;
  }
  function normalizeOfficialUrl(value, base) {
    try {
      var raw=String(value || ''),url = new URL(raw, base || 'https://supercell.com');
      if(raw.indexOf('/../')>=0||raw.indexOf('/./')>=0||/^https?:/i.test(raw)&&raw!==url.href||url.protocol !== 'https:' || url.username || url.password || url.port || url.search || url.hash) return null;
      if(url.hostname==='event.supercell.com'&&url.pathname==='/brawlstars/v1/event')return url.href;
      if(url.hostname!=='supercell.com'||/%|\\/.test(url.pathname)||!/^\/en\/games\/(clashofclans|brawlstars|boombeach|clashroyale|hayday)\/blog\/(news|release-notes|esports|blog|community)\/[a-z0-9]+(?:-[a-z0-9]+)*\/$/.test(url.pathname)&&!/^\/en\/games\/hayday\/blog\/game-updates\/[a-z0-9]+(?:-[a-z0-9]+)*\/$/.test(url.pathname))return null;
      return url.href;
    } catch (_) { return null; }
  }
  function classifyCreatorTitle(title) {
    var value = String(title || '').toLocaleLowerCase();
    var topics = [];
    if (['무료','보상','쿠폰','이벤트 보상','free','reward','gift','coupon'].some(function(word){ return value.indexOf(word) !== -1; })) topics.push('reward-topic');
    if (['이벤트','기념','event','anniversary'].some(function(word){ return value.indexOf(word) !== -1; })) topics.push('event-topic');
    return topics;
  }
  function normalizeCreatorVideoUrl(value) {
    var raw = String(value || '');
    return /^https:\/\/www\.youtube\.com\/watch\?v=[A-Za-z0-9_-]{11}$/.test(raw) ? raw : null;
  }
  function normalizeCreatorThumbnailUrl(value) {
    var raw = String(value || '');
    return /^https:\/\/i\.ytimg\.com\/vi\/[A-Za-z0-9_-]{11}\/hqdefault\.jpg$/.test(raw) ? raw : null;
  }
  function cleanExpectedTitle(value) {
    return String(value || '').replace(/\s*·\s*예상\s*$/, '').replace(/\s*\(예상\)\s*$/, '').trim();
  }
  function generateMonth(year, month) {
    if (!Number.isInteger(year) || !Number.isInteger(month) || month < 1 || month > 12) throw new TypeError('유효한 연도와 월이 필요합니다.');
    var last = daysInMonth(year,month), events = [];
    function add(id,title,start,end,category,description) {
      events.push({ id:id+'-'+iso(year,month,start), title:title, status:'EXPECTED', official:false, startDate:iso(year,month,start), endDate:iso(year,month,end), category:category, description:description });
    }
    add('season','월간 시즌 · 예상',1,last,'season','한 달 동안 진행되는 시즌 일정의 예상 범위입니다. 정확한 시간은 게임 내 공지를 확인하세요.');
    add('cwl','클랜전 리그 · 예상',1,Math.min(11,last),'league','통상적인 월초 범위입니다. 실제 등록 및 전투 시각은 게임에서 달라질 수 있습니다.');
    add('games','클랜 게임 · 예상',Math.min(22,last),Math.min(28,last),'clan-games','통상적인 월말 범위입니다. 실제 일정은 게임 내 공지를 확인하세요.');
    for (var d=-2; d<=last; d++) {
      var start = new Date(Date.UTC(year,month-1,d));
      if (start.getUTCDay() === 5) {
        var startIso = iso(start.getUTCFullYear(),start.getUTCMonth()+1,start.getUTCDate());
        var end = new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),start.getUTCDate()+3));
        events.push({ id:'raid-'+startIso, title:'레이드 주말 · 예상', status:'EXPECTED', official:false, startDate:startIso, endDate:iso(end.getUTCFullYear(),end.getUTCMonth()+1,end.getUTCDate()), category:'raid', description:'금요일부터 월요일까지의 반복 예상 범위입니다. 정확한 시각은 게임에서 확인하세요.' });
      }
    }
    return { year:year, month:month, daysInMonth:last, firstWeekday:new Date(Date.UTC(year,month-1,1)).getUTCDay(), events:events };
  }
  function eventsForDate(model,date) { return model.events.filter(function(e){ return e.startDate <= date && e.endDate >= date; }); }
  var OFFICIAL_DISPLAY_KO={
    'Clash of Cards Event':['클래시 오브 카드 이벤트','마을 회관 3레벨 이상이라면 누구나 참여할 수 있는 새로운 형식의 이벤트입니다.'],
    'Gold Pass: Tempest Champion season':['골드 패스 · 템페스트 챔피언 시즌','8월 골드 패스 시즌입니다.'],
    'Gold Pass':['골드 패스','보상을 잠금 해제하고 성장을 가속하며 이번 시즌 한정 영웅 스킨인 템페스트 챔피언을 획득할 수 있습니다.'],
    'New Crafted Defenses':['신규 제작 방어 시설','제작소가 문을 열었습니다.'],
    'Clan War League':['클랜전 리그','7개 클랜과 15대15 또는 30대30 클랜전을 치릅니다.'],
    'Mass Spell Event #1: Totem and Birth Boom Spells':['대규모 마법 이벤트 1: 토템과 탄생 폭발 마법','밤새 마법 제작소가 가동되어 특별한 마법을 대량으로 사용할 수 있습니다.'],
    'The Awesome Quest Scenery':['어썸 퀘스트 배경','마을 주민들이 어썸 산에 올라 최강의 챔피언들이 펼치는 대결을 관람합니다.'],
    'Hero Skin: King Barbarian':['영웅 스킨 · 킹 바바리안','8월 공식 영웅 스킨 일정입니다.'],
    'Hero Skin: Elven Archer':['영웅 스킨 · 엘븐 아처','8월 공식 영웅 스킨 일정입니다.'],
    'Hero Skin: King Barbarian (Barbarian King)':['영웅 스킨: 킹 바바리안','턴제 전투를 기다릴 인내심이 없는 콧수염 없는 위협적인 전사입니다.'],
    'Hero Skin: Elven Archer (Archer Queen)':['영웅 스킨: 엘븐 아처','숲 가장자리를 누비는 고귀하고 발 빠른 궁수입니다.'],
    "Chief's Chronicles":['수장의 연대기','클래시 오브 클랜 최초의 연간 결산입니다.'],
    'Mass Elephant Riders and Super Valkyries':['코끼리 기수와 슈퍼 발키리 대규모 지원','코끼리 기수 50명과 슈퍼 발키리 20명이 24시간 동안 일반 군대에 합류합니다.'],
    'Hero Skin: Drakan Duke (Dragon Duke)':['영웅 스킨: 드라칸 듀크','지옥불 검을 벼린 메마른 황무지의 불꽃 야수입니다.'],
    'Hero Skin: Drakan Duke':['영웅 스킨 · 드라칸 듀크','8월 공식 영웅 스킨 일정입니다.'],
    'Hero Skin: Lich Prince (Minion Prince)':['영웅 스킨: 리치 프린스','익살스럽게 거대한 메너스 메이스를 든 불멸의 마법 대가입니다.'],
    'Hero Skin: Lich Prince':['영웅 스킨 · 리치 프린스','8월 공식 영웅 스킨 일정입니다.'],
    'Awesome Medal Event':['어썸 메달 이벤트','어썸 마법사가 여러분의 도움을 기다립니다.'],
    'Hero Skin: Grand Mage (Grand Warden)':['영웅 스킨: 그랜드 메이지','반경 70타일 안의 모든 병력을 감탄하게 만드는 해안 출신 마법사입니다.'],
    'Hero Skin: Grand Mage':['영웅 스킨 · 그랜드 메이지','8월 공식 영웅 스킨 일정입니다.'],
    'Resource Fest & Work for Hire #1':['자원 축제와 일꾼 고용 1','자원 생산 시설의 생산량과 저장량이 4배로 증가하고 고블린 장인의 도움도 받을 수 있습니다.'],
    'Clash-A-Rama Cosmetics Return':['클래시라마 장식품 재출시','클래식 클래시라마 장식품이 상점에 돌아옵니다.'],
    'Mass Spell Event #2':['대규모 마법 이벤트 2','군대에 치유 마법 30개와 신속 마법 30개가 추가됩니다.'],
    'Clan Games':['클랜 게임','도전을 완료해 점수를 모으고 클랜과 함께 보상 트랙을 획득합니다.'],
    'Revenge Deck Boost':['리벤지 덱 부스트','새로운 리벤지 덱 영웅 장비가 영웅 회관에서 허용하는 최대 레벨로 강화됩니다.'],
    'Resource Fest & Work for Hire #2':['자원 축제와 일꾼 고용 2','시즌 종료 전에 자원 생산 시설 4배 부스트와 고블린 장인의 도움을 한 번 더 받을 수 있습니다.'],
    'Card Hunt':['카드 사냥','공식 안내 기간은 8월 1일부터 31일까지입니다.'],
    'SC Store':['슈퍼셀 스토어','공식 안내 기간은 8월 3일부터 30일까지입니다.'],
    'Trader':['상인','공식 안내 날짜에 상인이 찾아옵니다.'],
    'Trading closes':['거래 종료','공식 안내에 따라 9월 2일 08:00 UTC에 거래가 종료됩니다.'],
    'Medal Event':['메달 이벤트','공식 글에 명시된 기간 동안 메달 이벤트가 진행됩니다.'],
    'Goblin Researcher':['고블린 연구원','고블린 연구원이 이벤트의 마지막 구간을 위해 돌아옵니다.'],
    'Summer Jam Event 4: Everything Quest':['서머 잼 이벤트 4: 모든 것 퀘스트','서머 잼 이벤트의 마지막 구간인 모든 것 퀘스트입니다.']
  };
  function officialDisplayKo(e){var title=String(e&&e.title||'').replace(/&amp;/g,'&');return OFFICIAL_DISPLAY_KO[title];}
  function eventTitleKo(e){var display=officialDisplayKo(e),title=display?display[0]:cleanExpectedTitle(e&&e.title);if(e&&e.sourceState==='FRESH_SOURCE_PARTIAL')return title+' · 부분 갱신 새 자료';if(e&&e.sourceState==='PRESERVED_CACHE_PARTIAL')return title+' · 부분 갱신 보존 캐시';if(e&&e.sourceState==='STALE_CACHE')return title+' · 오래된 캐시';return title;}
  function eventDescriptionKo(e){var display=officialDisplayKo(e);return display?display[1]:String(e&&e.description||'');}
  function eventDisplayCategory(e){if(e&&e.official===true&&e.title==='Clan War League')return 'league';if(e&&e.official===true&&e.title==='Clan Games')return 'clan-games';return e&&e.category;}
  function sortMonthHighlights(events){return (Array.isArray(events)?events:[]).slice().sort(function(a,b){var ap=a.title==='Clan War League'?0:a.title==='Clan Games'?1:2,bp=b.title==='Clan War League'?0:b.title==='Clan Games'?1:2;return ap-bp||String(a.startDate).localeCompare(String(b.startDate))||String(a.endDate).localeCompare(String(b.endDate))||String(a.title).localeCompare(String(b.title));});}
  function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')))return false;var d=new Date(value+'T00:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===value;}
  var OFFICIAL_EVENT_KEYS=new Set(['id','title','startDate','endDate','category','description','official','status','sourceUrl','verifiedAt','verifiedDate','datePrecision','startInstant','pointDate','timezone','sourceTimeZone','sourceState','sourceFamily','lastVerifiedAt','sourceUrls','filterTags','gameId','canonicalEventKey','officialSourceFamily']);
  function exactOfficialEventKeys(e){return Object.keys(e).every(function(key){return OFFICIAL_EVENT_KEYS.has(key);});}
  function officialGameIdFromUrl(value){try{var u=new URL(String(value||''));if(u.href==='https://event.supercell.com/brawlstars/v1/event')return'brawl-stars';var m=u.pathname.match(/^\/en\/games\/(clashofclans|brawlstars|boombeach|clashroyale|hayday)\/blog\//),ids={clashofclans:'clash-of-clans',brawlstars:'brawl-stars',boombeach:'boom-beach',clashroyale:'clash-royale',hayday:'hay-day'};return m?ids[m[1]]:null}catch(_){return null}}
  function validOfficialEvent(e,expectedGameId){
    if(!e||!exactOfficialEventKeys(e)||e.official!==true||e.status!=='OFFICIAL'||!/^[-a-z0-9]{1,80}$/.test(String(e.id||''))||!String(e.title||'').trim()||String(e.title).length>160||/[\u0000-\u001f\u007f]/.test(String(e.title))||!String(e.description||'').trim()||String(e.description).length>600||/[\u0000-\u001f\u007f]/.test(String(e.description))||!['special-event','medal-event','spotlight','esports','challenge','season','warships','operation','mania','event'].includes(e.category)||!validDate(e.verifiedDate)||!/^(?:BRAWL_ESPORTS|SUPERCELL_ARCHIVE)$/.test(String(e.sourceFamily||'')))return false;
    var owns=function(key){return Object.prototype.hasOwnProperty.call(e,key);};
    if(owns('sourceState')&&(typeof e.sourceState!=='string'||!/^(?:BUNDLED|FRESH_NETWORK|CACHED_FRESH|FRESH_SOURCE|FRESH_SOURCE_PARTIAL|PRESERVED_CACHE_PARTIAL|PARTIAL_MIXED|STALE_CACHE)$/.test(e.sourceState)))return false;
    if(owns('lastVerifiedAt')&&(typeof e.lastVerifiedAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/.test(e.lastVerifiedAt)||Number.isNaN(new Date(e.lastVerifiedAt).getTime())))return false;
    var sourceGame=officialGameIdFromUrl(e.sourceUrl);if(!sourceGame||(expectedGameId&&sourceGame!==expectedGameId)||(owns('gameId')&&(typeof e.gameId!=='string'||e.gameId!==sourceGame))||!['DATE_ONLY','START_DATE_ONLY','END_DATE_ONLY','START_INSTANT_ONLY'].includes(e.datePrecision))return false;
    if(owns('verifiedAt')&&(typeof e.verifiedAt!=='string'||!validDate(e.verifiedAt)))return false;
    if(owns('filterTags')&&(!Array.isArray(e.filterTags)||e.filterTags.length>12||new Set(e.filterTags).size!==e.filterTags.length||e.filterTags.some(function(tag){return typeof tag!=='string'||!/^[a-z0-9-]{1,40}$/.test(tag);})))return false;
    if(owns('officialSourceFamily')&&(typeof e.officialSourceFamily!=='string'||e.officialSourceFamily!==e.sourceFamily))return false;
    var startPoint=e.datePrecision==='START_INSTANT_ONLY',startDateOnly=e.datePrecision==='START_DATE_ONLY',endDeadline=e.datePrecision==='END_DATE_ONLY';
    if(startPoint){if('endDate' in e||'startDate' in e||!validDate(e.pointDate)||e.timezone!=='Asia/Seoul'||e.sourceTimeZone!=='UTC'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(String(e.startInstant||''))||Number.isNaN(new Date(e.startInstant).getTime()))return false;var expected=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(e.startInstant));if(expected!==e.pointDate)return false;}
    else if(startDateOnly){if('endDate' in e||!validDate(e.startDate)||'pointDate' in e||'startInstant' in e||'timezone' in e||e.sourceTimeZone!=='UNPUBLISHED'||'sourceUrls' in e)return false;}
    else if(endDeadline){if('startDate' in e||!validDate(e.endDate)||'pointDate' in e||'startInstant' in e||'timezone' in e||e.sourceTimeZone!=='UNPUBLISHED'||'sourceUrls' in e)return false;}
    else if(!validDate(e.startDate)||!validDate(e.endDate)||e.sourceTimeZone!=='UNPUBLISHED'||'pointDate' in e||'startInstant' in e||'timezone' in e||'sourceUrls' in e)return false;
    if(owns('canonicalEventKey')&&(typeof e.canonicalEventKey!=='string'||!/^[a-z0-9-]+(?:\/[a-z0-9-]+){0,2}$/.test(e.canonicalEventKey)))return false;
    if(startPoint){var pointSafe=normalizeOfficialUrl(e.sourceUrl);if(e.sourceFamily!=='BRAWL_ESPORTS'||pointSafe!==e.sourceUrl||pointSafe!=='https://event.supercell.com/brawlstars/v1/event')return false;return Array.isArray(e.sourceUrls)&&e.sourceUrls.length===3&&e.sourceUrls[0]===e.sourceUrl&&e.sourceUrls[1]==='https://event.supercell.com/brawlstars/assets/events/en.json'&&e.sourceUrls[2]==='https://event.supercell.com/brawlstars/assets/events/kr.json';}
    var archiveEndpoint=e.sourceFamily==='SUPERCELL_ARCHIVE'&&(/^https:\/\/supercell\.com\/en\/games\/(?:clashofclans|brawlstars|boombeach|clashroyale)\/blog\/(?:news|release-notes|esports|blog|community)\/[a-z0-9-]+\/$/.test(e.sourceUrl)||/^https:\/\/supercell\.com\/en\/games\/hayday\/blog\/(?:news|release-notes|esports|blog|community|game-updates)\/[a-z0-9-]+\/$/.test(e.sourceUrl));
    if(startDateOnly||endDeadline)return archiveEndpoint;
    var safe=normalizeOfficialUrl(e.sourceUrl);if(e.sourceFamily!=='SUPERCELL_ARCHIVE'||safe!==e.sourceUrl||!archiveEndpoint)return false;
    var span=(new Date(e.endDate+'T00:00:00Z')-new Date(e.startDate+'T00:00:00Z'))/86400000;return span>=0&&span<=62;
  }
  function projectOfficialEvent(e){if(e.datePrecision==='START_INSTANT_ONLY')return Object.assign({},e,{startDate:e.pointDate,endDate:e.pointDate,dateProjection:'START_POINT',description:'공식 시작 시각: '+e.startInstant+' (공식 종료 시각 미공개)'});if(e.datePrecision==='START_DATE_ONLY')return Object.assign({},e,{endDate:e.startDate,dateProjection:'START_DATE',description:'공식 시작일: '+e.startDate+' (공식 종료일 미공개)'});if(e.datePrecision==='END_DATE_ONLY')return Object.assign({},e,{startDate:e.endDate,endDate:e.endDate,dateProjection:'END_DEADLINE',description:'공식 종료일: '+e.endDate+' (공식 시작일 미공개)'});return Object.assign({},e);}
  function actionableOfficialEvidence(e){return e&&e.sourceState!=='STALE_CACHE'&&e.sourceState!=='PRESERVED_CACHE_PARTIAL';}
  function validProjectedOfficialCalendarEvent(e,gameId){
    if(!e||!('dateProjection' in e))return validOfficialEvent(e,gameId);
    var raw=Object.assign({},e);
    if(e.dateProjection==='START_POINT'){
      if(e.datePrecision!=='START_INSTANT_ONLY'||e.pointDate!==e.startDate||e.startDate!==e.endDate)return false;
      delete raw.startDate;delete raw.endDate;delete raw.dateProjection;
      return validOfficialEvent(raw,gameId);
    }
    if(e.dateProjection==='END_DEADLINE'){
      if(e.datePrecision!=='END_DATE_ONLY'||e.endDate!==e.startDate)return false;
      delete raw.startDate;delete raw.dateProjection;
      return validOfficialEvent(raw,gameId);
    }
    if(e.dateProjection==='START_DATE'){
      if(e.datePrecision!=='START_DATE_ONLY'||e.startDate!==e.endDate)return false;
      delete raw.endDate;delete raw.dateProjection;
      return validOfficialEvent(raw,gameId);
    }
    return false;
  }
  function mergeOfficialEvents(model,events,remoteEvents,gameId){
    var scopedGame=gameId||((Array.isArray(events)?events:[]).concat(Array.isArray(remoteEvents)?remoteEvents:[]).map(function(e){return officialGameIdFromUrl(e&&e.sourceUrl)}).filter(Boolean)[0]),source=events;
    if(Array.isArray(remoteEvents)){
      var remoteByKey={};
      remoteEvents.filter(function(e){return validOfficialEvent(e,scopedGame)}).forEach(function(e){var p=projectOfficialEvent(e),key=String(e.sourceFamily||'')+'|'+String(p.title).toLocaleLowerCase()+'|'+p.startDate+'|'+p.endDate,current=remoteByKey[key];if(!current||actionableOfficialEvidence(e)&&!actionableOfficialEvidence(current))remoteByKey[key]=e;});
      var validRemote=Object.keys(remoteByKey).map(function(key){return remoteByKey[key];}),validSeeds=(Array.isArray(events)?events:[]).filter(function(e){return validOfficialEvent(e,scopedGame)}),seedGroups={},used={};
      function projected(e){return projectOfficialEvent(e);}
      function occurrenceGroup(e){var p=projected(e);return String(e.sourceFamily||'')+'|'+String(p.title).toLocaleLowerCase()+'|'+p.startDate.slice(0,7);}
      validSeeds.forEach(function(e,index){var key=occurrenceGroup(e);(seedGroups[key]||(seedGroups[key]=[])).push(index);});
      validRemote.filter(actionableOfficialEvidence).forEach(function(remote){var rp=projected(remote),candidates=seedGroups[occurrenceGroup(remote)]||[],best=-1,bestDistance=Infinity;for(var i=0;i<candidates.length;i++){var index=candidates[i];if(used[index])continue;var sp=projected(validSeeds[index]),distance=Math.abs(new Date(sp.startDate+'T00:00:00Z')-new Date(rp.startDate+'T00:00:00Z'));if(distance<bestDistance){best=index;bestDistance=distance;}}if(best>=0)used[best]=true;});
      source=validSeeds.filter(function(e,index){return !used[index];}).concat(validRemote.filter(function(remote){return actionableOfficialEvidence(remote)||!(seedGroups[occurrenceGroup(remote)]||[]).length;}));
    }
    var copy={year:model.year,month:model.month,daysInMonth:model.daysInMonth,firstWeekday:model.firstWeekday,events:model.events.slice()},byKey={};
    (Array.isArray(source)?source:[]).forEach(function(e){if(!validOfficialEvent(e,scopedGame))return;var projected=projectOfficialEvent(e),key=String(e.sourceFamily||'')+'|'+String(projected.title).toLocaleLowerCase()+'|'+projected.startDate+'|'+projected.endDate;byKey[key]=projected;});
    var officialValues=Object.keys(byKey).map(function(key){return byKey[key];});
    var hasCwl=officialValues.some(function(e){return e.title.toLocaleLowerCase()==='clan war league'&&e.startDate.slice(0,7)===iso(model.year,model.month,1).slice(0,7);});
    var hasClanGames=officialValues.some(function(e){return e.title.toLocaleLowerCase()==='clan games'&&e.startDate.slice(0,7)===iso(model.year,model.month,1).slice(0,7);});
    copy.events=copy.events.filter(function(e){return !(hasCwl&&e.category==='league')&&!(hasClanGames&&e.category==='clan-games');});
    var first=iso(model.year,model.month,1),last=iso(model.year,model.month,model.daysInMonth);Object.keys(byKey).forEach(function(key){var e=byKey[key];if(e.startDate<=last&&e.endDate>=first)copy.events.push(e);});return copy;
  }
  var CREATOR_CHANNELS=Object.freeze({
    'clash-of-clans':Object.freeze({'UCD1Em4q90ZUK2R5HKesszJg':Object.freeze({name:'Clash of Clans',authority:'OFFICIAL',promotionAllowed:true}),'UC85aYbNSFjsJdxfpxgQr8tA':Object.freeze({name:'Judo Sloth Gaming',authority:'VERIFIED',promotionAllowed:true}),'UCv45ttLI7WSM5YnNjIWDb8A':Object.freeze({name:'빠다',authority:'PARTNER_STATUS_UNVERIFIED',promotionAllowed:false})}),
    'brawl-stars':Object.freeze({'UCooVYzDxdwTtGYAkcPmOgOw':Object.freeze({name:'Brawl Stars',authority:'OFFICIAL',promotionAllowed:true}),'UClJspSpzADMROqOW9HLHaoA':Object.freeze({name:'Brawl Stars Korea',authority:'OFFICIAL',promotionAllowed:true}),'UCoH2pCzAr6zWDG-LtUiLWRw':Object.freeze({name:'Holit',authority:'PARTNER_STATUS_UNVERIFIED',promotionAllowed:false})}),
    'boom-beach':Object.freeze({'UC3Xzm_n7d0jy726uHsTX7yA':Object.freeze({name:'Boom Beach',authority:'OFFICIAL',promotionAllowed:true}),'UCVtCq_mSA6YpVV7FG5dYM-g':Object.freeze({name:'TheChicken',authority:'PARTNER_STATUS_UNVERIFIED',promotionAllowed:false})}),
    'clash-royale':Object.freeze({'UC_F8DoJf9MZogEOU51TpTbQ':Object.freeze({name:'Clash Royale',authority:'OFFICIAL',promotionAllowed:true}),'UCL_IvtOZo6sONpiydbzzHpA':Object.freeze({name:'JUNE',authority:'PARTNER_STATUS_UNVERIFIED',promotionAllowed:false})}),
    'hay-day':Object.freeze({'UCBrMq7wkdPWb3PxR-GUR61A':Object.freeze({name:'Hay Day',authority:'OFFICIAL',promotionAllowed:true}),'UCGoJ4CNJj3BI3uslWV9nUsA':Object.freeze({name:'HayDayEveryday',authority:'PARTNER_STATUS_UNVERIFIED',promotionAllowed:false})})
  });
  function creatorChannelPolicy(gameId,channelId){var game=CREATOR_CHANNELS[gameId],value=game&&game[channelId];return value?Object.assign({},value):null;}
  function normalizedEvidenceText(value){return String(value||'').replace(/[\s\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+/g,' ').trim()}
  function exactIsoDate(y,m,d){var value=String(y).padStart(4,'0')+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');return validDate(value)?value:null}
  function parseCreatorDateExpression(raw,precision){var s=normalizedEvidenceText(raw),m,start,end,months={January:1,February:2,March:3,April:4,May:5,June:6,July:7,August:8,September:9,October:10,November:11,December:12};if(!s||s.length>80)return null;if((m=s.match(/^(\d{4})\.(\d{2})\.(\d{2})\.$/))){start=end=exactIsoDate(+m[1],+m[2],+m[3])}else if((m=s.match(/^(\d{4}-\d{2}-\d{2})\s+(?:to|[-\u2013])\s+(\d{4}-\d{2}-\d{2})$/i))){start=validDate(m[1])?m[1]:null;end=validDate(m[2])?m[2]:null}else if((m=s.match(/^([A-Z][a-z]+)\s+(\d{1,2})\s*[-\u2013]\s*(\d{1,2}),\s*(\d{4})$/))&&months[m[1]]){start=exactIsoDate(+m[4],months[m[1]],+m[2]);end=exactIsoDate(+m[4],months[m[1]],+m[3])}else if((m=s.match(/^(\d{4})\uB144\s*(\d{1,2})\uC6D4\s*(\d{1,2})\uC77C\s*(?:\uBD80\uD130\s*)?(?:[-\u2013~]|\uC5D0\uC11C)\s*(\d{4})\uB144\s*(\d{1,2})\uC6D4\s*(\d{1,2})\uC77C(?:\s*\uAE4C\uC9C0)?$/))){start=exactIsoDate(+m[1],+m[2],+m[3]);end=exactIsoDate(+m[4],+m[5],+m[6])}else if((m=s.match(/^(\d{4}-\d{2}-\d{2})$/))){start=end=validDate(m[1])?m[1]:null}else if((m=s.match(/^([A-Z][a-z]+)\s+(\d{1,2}),\s*(\d{4})$/))&&months[m[1]]){start=end=exactIsoDate(+m[3],months[m[1]],+m[2])}else if((m=s.match(/^(\d{4})\uB144\s*(\d{1,2})\uC6D4\s*(\d{1,2})\uC77C$/))){start=end=exactIsoDate(+m[1],+m[2],+m[3])}else return null;if(!start||!end||end<start||(new Date(end+'T00:00:00Z')-new Date(start+'T00:00:00Z'))/86400000>62)return null;var inferred=start===end?'START_ONLY':'START_END';if(precision&&((precision==='START_END')!==(start!==end)||!['START_END','START_ONLY','END_ONLY'].includes(precision)))return null;return{startDate:start,endDate:end,datePrecision:precision||inferred}}  function sha256(value){function rr(n,x){return x>>>n|x<<32-n}var bytes=unescape(encodeURIComponent(value)),words=[],bit=bytes.length*8,h=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],k=[],prime=2;function isPrime(n){for(var i=2;i*i<=n;i++)if(n%i===0)return false;return true}while(k.length<64){if(isPrime(prime)){var r=Math.sqrt(prime),c=Math.cbrt(prime);if(h.length<8)h.push(r*4294967296|0);k.push(c*4294967296|0)}prime++}for(var i=0;i<bytes.length;i++)words[i>>2]|=bytes.charCodeAt(i)<<(3-i%4)*8;words[bit>>5]|=128<<(24-bit%32);words[(bit+64>>9<<4)+15]=bit;for(var j=0;j<words.length;j+=16){var w=[],old=h.slice();for(i=0;i<64;i++){var x=w[i]=i<16?words[j+i]|0:(w[i-16]+(rr(7,w[i-15])^rr(18,w[i-15])^w[i-15]>>>3)+w[i-7]+(rr(17,w[i-2])^rr(19,w[i-2])^w[i-2]>>>10))|0,t1=(h[7]+(rr(6,h[4])^rr(11,h[4])^rr(25,h[4]))+(h[4]&h[5]^~h[4]&h[6])+k[i]+x)|0,t2=((rr(2,h[0])^rr(13,h[0])^rr(22,h[0]))+(h[0]&h[1]^h[0]&h[2]^h[1]&h[2]))|0;h=[t1+t2|0,h[0],h[1],h[2],h[3]+t1|0,h[4],h[5],h[6]]}for(i=0;i<8;i++)h[i]=h[i]+old[i]|0}return h.map(function(n){return(n>>>0).toString(16).padStart(8,'0')}).join('')}
  function validCreatorEvent(e){var policy=e&&creatorChannelPolicy(e.gameId,e.channelId),expected=['id','title','canonicalEventKey','startDate','endDate','official','status','confidence','authority','evidenceKind','captionType','evidenceQuote','evidenceHash','dateExpression','datePrecision','deadlineSemantics','eventScope','corroborationState','gameId','videoId','channelId','creatorName','sourceUrl','publishedAt','reviewedAt','quoteTimestamp','timezone','sourceState'];if(!e||Object.keys(e).sort().join('|')!==expected.sort().join('|')||e.official!==false||e.status!=='CREATOR_DATED'||e.confidence!=='HIGH'||!policy||!policy.promotionAllowed||e.authority!==policy.authority||e.creatorName!==policy.name||!['DESCRIPTION','TRANSCRIPT_SEGMENT'].includes(e.evidenceKind))return false;if(!/^(NONE|ON_OR_BEFORE_DATE)$/.test(String(e.deadlineSemantics||''))||!/^[A-Z][A-Z0-9_]{0,63}$/.test(String(e.eventScope||''))||!/^[A-Z][A-Z0-9_]{0,63}$/.test(String(e.corroborationState||'')))return false;if(!/^[-a-z0-9]{1,100}$/.test(String(e.id||''))||!String(e.title||'').trim()||String(e.title).length>160||!String(e.evidenceQuote||'').trim()||String(e.evidenceQuote).length>320||!/^[A-Za-z0-9_-]{11}$/.test(String(e.videoId||'')))return false;var parsed=parseCreatorDateExpression(e.dateExpression,e.datePrecision);if(!parsed||parsed.startDate!==e.startDate||parsed.endDate!==e.endDate||!normalizedEvidenceText(e.evidenceQuote).includes(normalizedEvidenceText(e.dateExpression))||sha256(e.evidenceQuote)!==e.evidenceHash)return false;if(!new RegExp('^'+e.gameId.replace(/-/g,'\\-')+'\/[a-z0-9-]+\/'+e.startDate.slice(0,4)+'$').test(String(e.canonicalEventKey||''))||e.sourceUrl!=='https://www.youtube.com/watch?v='+e.videoId)return false;var transcript=/^\d{2}:\d{2}:\d{2}\.\d{3}-\d{2}:\d{2}:\d{2}\.\d{3}$/.test(String(e.quoteTimestamp||''));if(e.evidenceKind==='DESCRIPTION'&&(e.captionType!=='DESCRIPTION_TEXT'||e.quoteTimestamp!==null)||e.evidenceKind==='TRANSCRIPT_SEGMENT'&&(!['MANUAL_CAPTION','AUTO_GENERATED'].includes(e.captionType)||!transcript))return false;if(e.timezone!==null&&(String(e.timezone).length>64||e.timezone!=='UTC'&&!/^[A-Za-z_]+(?:\/[A-Za-z0-9_+.-]+){1,2}$/.test(String(e.timezone))))return false;var iso=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/,published=Date.parse(e.publishedAt),reviewed=Date.parse(e.reviewedAt),low=Date.parse('2020-01-01T00:00:00Z'),high=Date.parse('2100-01-01T00:00:00Z');return iso.test(String(e.publishedAt||''))&&iso.test(String(e.reviewedAt||''))&&published>=low&&reviewed>=published&&reviewed<high&&e.sourceState==='BUNDLED_REVIEWED';}
  function validCreatorEvidenceManifest(value){var ids=['clash-of-clans','brawl-stars','boom-beach','clash-royale','hay-day'];if(!value||Object.keys(value).sort().join('|')!=='inventories|reviewedCutoff|schemaVersion'||value.schemaVersion!==1||!validDate(value.reviewedCutoff)||!Array.isArray(value.inventories)||value.inventories.length!==5)return false;var cutoff=Date.parse(value.reviewedCutoff+'T23:59:59.999Z');for(var i=0;i<ids.length;i++){var inventory=value.inventories[i];if(!inventory||Object.keys(inventory).sort().join('|')!=='events|gameId'||inventory.gameId!==ids[i]||!Array.isArray(inventory.events)||inventory.events.length>24)return false;for(var j=0;j<inventory.events.length;j++)if(inventory.events[j].gameId!==ids[i]||!validCreatorEvent(inventory.events[j])||Date.parse(inventory.events[j].publishedAt)>cutoff||Date.parse(inventory.events[j].reviewedAt)>cutoff)return false;}return true;}  var creatorSchemaValidator=validCreatorEvent;function strictValidCreatorEvent(e){var policy=e&&creatorChannelPolicy(e.gameId,e.channelId);return creatorSchemaValidator(e)&&policy&&e.creatorName===policy.name;}validCreatorEvent=strictValidCreatorEvent;
  function derivedCreatorFilterTags(e){return e&&e.gameId==='brawl-stars'&&e.eventScope==='COMMUNITY_ESPORTS_APPLICATION'?['championship']:[];}
  function validCreatorCalendarEvent(e){if(validCreatorEvent(e))return true;if(!e||!Array.isArray(e.filterTags))return false;var keys=Object.keys(e),strictKeys=keys.filter(function(key){return key!=='filterTags';});if(keys.length!==strictKeys.length+1)return false;var strict={};strictKeys.forEach(function(key){strict[key]=e[key];});if(!validCreatorEvent(strict))return false;var expected=derivedCreatorFilterTags(strict);return e.filterTags.length===expected.length&&e.filterTags.every(function(tag,index){return tag===expected[index];});}
  function reconcileCalendarEvents(official,creator,trusted,gameId){
    if(typeof trusted==='string'&&gameId===undefined){gameId=trusted;trusted=[];}var scoped=typeof gameId==='string'&&gameId.length>0,allCreators=(Array.isArray(creator)?creator:[]).filter(validCreatorEvent),scope=gameId||(allCreators[0]&&allCreators[0].gameId)||'clash-of-clans',creators=scoped?allCreators.filter(function(e){return e.gameId===scope;}):allCreators,events=(Array.isArray(official)?official:[]).map(function(e){return canonicalizeOfficialEvent(e,scope,scoped);}).filter(Boolean),trustedEvents=(Array.isArray(trusted)?trusted:[]).filter(function(e){return(!scoped||e.gameId===scope)&&validTrustedCalendarEvent(e);}),officialByKey={},trustedByKey={},groups={},quarantined=[];events.filter(actionableOfficialEvidence).forEach(function(e){officialByKey[e.canonicalEventKey]=e;});trustedEvents.forEach(function(e){var key=e.gameId+'/'+canonicalSlug(e.title)+'/'+e.startDate.slice(0,4),winner=officialByKey[key],overlap=winner&&e.startDate<=winner.endDate&&winner.startDate<=e.endDate;if(winner&&(e.status==='HIGH_CONFIDENCE'||overlap)){if(winner.startDate!==e.startDate||winner.endDate!==e.endDate)quarantined.push(Object.assign({},e,{quarantineReason:'OFFICIAL_TRUSTED_BOUNDARY_CONFLICT'}));return;}events.push(e);(trustedByKey[key]||(trustedByKey[key]=[])).push(e);});creators.forEach(function(e){var officialWinner=officialByKey[e.canonicalEventKey],trustedWinners=trustedByKey[e.canonicalEventKey]||[];if(officialWinner){if(officialWinner.startDate!==e.startDate||officialWinner.endDate!==e.endDate)quarantined.push(Object.assign({},e,{quarantineReason:'OFFICIAL_BOUNDARY_CONFLICT'}));return;}if(trustedWinners.length){if(!trustedWinners.some(function(winner){return winner.startDate===e.startDate&&winner.endDate===e.endDate;}))quarantined.push(Object.assign({},e,{quarantineReason:'TRUSTED_BOUNDARY_CONFLICT'}));return;}(groups[e.canonicalEventKey]||(groups[e.canonicalEventKey]=[])).push(e);});Object.keys(groups).sort().forEach(function(key){var group=groups[key],boundaries={};group.forEach(function(e){boundaries[e.startDate+'|'+e.endDate]=true;});if(Object.keys(boundaries).length>1)quarantined=quarantined.concat(group.map(function(e){return Object.assign({},e,{quarantineReason:'CONFLICTING_BOUNDARIES'});}));else events.push(Object.assign({},group.slice().sort(function(a,b){return a.id.localeCompare(b.id);})[0]));});return{events:events,quarantined:quarantined};
  }
  var TRUSTED_EVENT_KEYS=new Set(['id','gameId','title','startDate','endDate','startInstant','endInstant','datePrecision','category','eventFamily','status','confidence','dateConfidence','timeConfidence','authority','sourceUrl','sourceQuote','channelId','verifiedAt','verifiedDate','projectionStart','projectionEnd','expiry','filterTags','official','timezone','sourceTimeZone','changeNotice']);
  var TRUSTED_RULE_KEYS=new Set(['id','gameId','title','eventFamily','status','confidence','dateConfidence','timeConfidence','authority','sourceUrl','sourceQuote','sourceRevision','verifiedAt','verifiedDate','projectionStart','projectionEnd','expiry','category','filterTags','official','timezone','sourceTimeZone','weekdays','starts','changeNotice']);
  var TRUSTED_RECORD_BINDINGS={
    'coc-clash-of-cards':['clash-of-clans','Clash of Cards Event','CLASH_OF_CARDS','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-quest-is-here/','August 1-31: Clash of Cards Event'],
    'coc-card-hunt':['clash-of-clans','Clash of Cards — Card Hunt','CARD_HUNT','https://supercell.com/en/games/clashofclans/blog/news/clash-of-cards-event/','Card Hunt (Aug 1-31) - The main event.'],
    'coc-store-card-tasks':['clash-of-clans','Supercell Store free card-pack tasks','STORE_CARD_TASKS','https://supercell.com/en/games/clashofclans/blog/news/clash-of-cards-event/','SC Store (Aug 3-30) - Complete exclusive tasks in the SC Store for free card packs'],
    'coc-august-gold-pass':['clash-of-clans','August Gold Pass','GOLD_PASS','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-quest-is-here/','August 1-31: Gold Pass'],
    'coc-chiefs-chronicles':['clash-of-clans',"Chief's Chronicles",'CHIEFS_CHRONICLES','https://supercell.com/en/games/clashofclans/blog/news/chiefs-chronicles-are-here/','Chief’s Chronicles runs from August 8 (8:00 UTC) through August 31.'],
    'coc-awesome-medal':['clash-of-clans','Awesome Medal Event','AWESOME_MEDAL','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/','Event starts: August 12, 08:00 UTC. Event ends: August 31, 08:00 UTC.'],
    'coc-clan-games':['clash-of-clans','Clan Games','CLAN_GAMES','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-quest-is-here/','August 22-28: Clan Games'],
    'coc-revenge-deck':['clash-of-clans','Revenge Deck Boost','REVENGE_DECK','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/','Equipment boost: from August 26-31, Revenge Deck gets boosted…'],
    'coc-resource-fest-2':['clash-of-clans','Resource Fest & Work for Hire #2','RESOURCE_FEST','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-quest-is-here/','August 29-31: Resource Fest & Work for Hire #2'],
    'coc-medal-access-end':['clash-of-clans','Awesome Medal Trader/Event Building access','AWESOME_MEDAL_ACCESS','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/',"The Trader's Event tab and Event Building stay accessible until September 2, 08:00 UTC"],
    'coc-card-trading-end':['clash-of-clans','Clash of Cards trading window','CARD_TRADING','https://supercell.com/en/games/clashofclans/blog/news/clash-of-cards-event/','On September 2nd at 08:00 AM UTC, the trading window closes'],
    'coc-september-gold-pass':['clash-of-clans','Gold Pass','SEPTEMBER_GOLD_PASS','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-30: Gold Pass'],
    'coc-september-cwl':['clash-of-clans','Clan War League','SEPTEMBER_CWL','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-11: Clan War League'],
    'coc-john-cena-challenge':['clash-of-clans','John Cena Challenge','JOHN_CENA_CHALLENGE','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-30: John Cena Challenge'],
    'coc-wwe-chests':['clash-of-clans','WWE Chests','WWE_CHESTS','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-30: WWE Chests'],
    'coc-temporary-wwe-troops':['clash-of-clans','Temporary WWE Troops','TEMP_WWE_TROOPS','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-30: Temp Troops'],
    'coc-battle-options-1':['clash-of-clans','Battle Options #1','BATTLE_OPTIONS_1','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-6: Battle Options'],
    'coc-money-in-the-bank-rush':['clash-of-clans','Money in the Bank Rush','MONEY_IN_THE_BANK_RUSH','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 1-5: Money in the Bank Rush'],
    'coc-friend-or-foe-army-camps-1':['clash-of-clans','Friend or Foe Army Camps #1','FRIEND_OR_FOE_ARMY_CAMPS_1','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 6-9: Friend or Foe Army Camps'],
    'coc-wwe-equipment-blast':['clash-of-clans','Equipment Blast Medal Event','WWE_EQUIPMENT_BLAST','https://supercell.com/en/games/clashofclans/blog/news/equipment-blast-medal-event/','Event starts: September 9 at 08:00 UTC Event ends: September 22 at 08:00 UTC'],
    'coc-battle-options-2':['clash-of-clans','Battle Options #2','BATTLE_OPTIONS_2','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 9-22: Battle Options #2'],
    'coc-resource-collector-boosts-1':['clash-of-clans','Resource Collector Boosts #1','RESOURCE_COLLECTOR_BOOSTS_1','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 12-14: Resource Collector Boosts'],
    'coc-equipment-boost':['clash-of-clans','Equipment Boost','EQUIPMENT_BOOST','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 16-21: Equipment Boost'],
    'coc-september-clan-games':['clash-of-clans','Clan Games','SEPTEMBER_CLAN_GAMES','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 22-28: Clan Games'],
    'coc-resource-collector-boosts-2':['clash-of-clans','Resource Collector Boosts #2','RESOURCE_COLLECTOR_BOOSTS_2','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 26-28: Resource Collector Boosts'],
    'coc-friend-or-foe-army-camps-2':['clash-of-clans','Friend or Foe Army Camps #2','FRIEND_OR_FOE_ARMY_CAMPS_2','https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/','September 28-30: Friend or Foe Army Camps'],
    'brawl-challengers-finals-2026':['brawl-stars','Brawl Stars Challengers Finals 2026','CHALLENGERS_FINALS','https://supercell.com/en/games/brawlstars/blog/esports/brawl-stars-challengers-finals-format--2/','Brawl Stars Challengers Final takes place September 5-6 at the ESA Espor Arena in Istanbul, Turkiye. Venue doors will open at 10:30am local times (09:30 CEST) each day. The show will start at 11:00am (subject to change).'],
    'brawl-update-planned-2026-09-01':['brawl-stars','August 2026 game update (planned release)','PLANNED_UPDATE','https://www.youtube.com/watch?v=qhvPlcwJUvk','We are planning to release this update on September 1st, but if this information turns out to be false, blame Danny.'],
    'brawl-duo-community-event-2026-09-19':['brawl-stars','Duo Community Event / Duolingo collaboration','DUO_COMMUNITY_EVENT','https://www.youtube.com/watch?v=qhvPlcwJUvk','The event starts on September 19th.'],
    'boom-crystal-critters':['boom-beach','Crystal Critters','CRYSTAL_CRITTERS','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','17 - 19: Crystal Critters'],
    'boom-gunboat-crab':['boom-beach','Gunboat Crab','GUNBOAT_CRAB','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','21 - 23: Gunboat Crab'],
    'boom-crystal-shield':['boom-beach','Crystal Shield','CRYSTAL_SHIELD','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','24 - 26: Crystal Shield'],
    'boom-warships-91':['boom-beach','Warships Season 91','WARSHIPS_SEASON','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','24 Aug - 13 Sept: Warships Season 91'],
    'boom-sonar-ops':['boom-beach','Sonar Ops','SONAR_OPS','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','28 Aug - 6 Sept: Sonar Ops'],
    'boom-heavy-mania':['boom-beach','Heavy Mania','HEAVY_MANIA','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','28 - 30: Heavy Mania'],
    'boom-deployable-turret':['boom-beach','Deployable Turret','DEPLOYABLE_TURRET','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','31 Aug - 2 Sept: Deployable Turret'],
    'boom-warrior-bombardier-mania':['boom-beach','Warrior & Bombardier Mania','WARRIOR_BOMBARDIER_MANIA','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','4 - 6: Warrior & Bombardier Mania'],
    'boom-speed-serum':['boom-beach','Speed Serum','SPEED_SERUM','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','7 - 9: Speed Serum'],
    'boom-grenadier-rocket-choppa-mania':['boom-beach','Grenadier & Rocket Choppa Mania','GRENADIER_ROCKET_CHOPPA_MANIA','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','11 - 13: Grenadier & Rocket Choppa Mania'],
    'boom-cryo-bomb':['boom-beach','Cryo Bomb','CRYO_BOMB','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','14 - 16: Cryo Bomb'],
    'boom-beastly-crab':['boom-beach','Beastly Crab','BEASTLY_CRAB','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','18 - 20: Beastly Crab'],
    'boom-leader-deployment':['boom-beach','Leader Deployment Event','LEADER_DEPLOYMENT','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','18 - 24: Leader Deployment Event'],
    'boom-crystal-critters-september':['boom-beach','Crystal Critters','CRYSTAL_CRITTERS','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','21 - 23: Crystal Critters'],
    'boom-joker-crab':['boom-beach','Joker Crab','JOKER_CRAB','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','25 - 27: Joker Crab'],
    'boom-explosive-drones-september':['boom-beach','Explosive Drones','EXPLOSIVE_DRONES','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','28 - 30: Explosive Drones'],
    'boom-warships-92':['boom-beach','Warships Season 92','WARSHIPS_SEASON_92','https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/','28 Sept - 18 Oct: Warships Season 92'],
    'cr-chaos-triple-draft':['clash-royale','C.H.A.O.S Triple Draft','CHAOS_TRIPLE_DRAFT','https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/','C.H.A.O.S Triple Draft: August 17th – Sept 7th'],
    'coc-wwe-equipment-blast-access':['clash-of-clans','Equipment Blast Trader/Event Building access','WWE_EQUIPMENT_BLAST_ACCESS','https://supercell.com/en/games/clashofclans/blog/news/equipment-blast-medal-event/',"After the event ends, you'll still be able to access the Trader Shop and Event Building until September 24"],
    'cr-chaos-epic-only':['clash-royale','C.H.A.O.S Epic Only','CHAOS_EPIC_ONLY','https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/','C.H.A.O.S Epic Only: August 17th – 24th'],
    'cr-chaos-sudden-death':['clash-royale','C.H.A.O.S Sudden Death','CHAOS_SUDDEN_DEATH','https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/','C.H.A.O.S Sudden Death: August 24th – 31st'],
    'cr-kens-mega-draft':['clash-royale','Ken’s C.H.A.O.S Mega Draft — Global Tournament','CHAOS_MEGA_DRAFT','https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/','Ken’s C.H.A.O.S Mega Draft: August 24th – 29th'],
    'cr-chaos-infinite-elixir':['clash-royale','C.H.A.O.S Infinite Elixir','CHAOS_INFINITE_ELIXIR','https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/','C.H.A.O.S Infinite Elixir: August 31st – Sept 7th'],
    'cr-merge-tactics-11':['clash-royale','Merge Tactics Season 11','MERGE_TACTICS_11','https://supercell.com/en/games/clashroyale/blog/release-notes/merge-tactics-season-11/','Season 11 will run from September 1st to December 1st, with no monthly resets!'],
    'cr-academy-antics':['clash-royale','Academy Antics','ACADEMY_ANTICS','https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/','Academy Antics: September 7th – October 5th'],
    'cr-2v2-league-september':['clash-royale','2v2 League','TWO_V_TWO_LEAGUE','https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/','2v2 League: September 7th – 21st'],
    'cr-princess-gambit':['clash-royale','Princess Gambit','PRINCESS_GAMBIT','https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/','Princess Gambit: September 21st – 26th'],
    'cr-royale-shuffle':['clash-royale','Royale Shuffle','ROYALE_SHUFFLE','https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/','Royale Shuffle: September 21st – October 5th'],
    'cr-clashroom-community':['clash-royale','Clashroom Community Event','CLASHROOM_COMMUNITY','https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/','CLASHROOM COMMUNITY EVENT September 22nd – 26th'],
    'cr-royale-shuffle-challenge':['clash-royale','Royale Shuffle Challenge','ROYALE_SHUFFLE_CHALLENGE','https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/','Challenge: September 28th – October 5th']
  };
  var TRUSTED_RULE_BINDINGS={
    CYCLE_HAMMERMAN:['boom-cycle-hammerman','boom-beach','Hammerman Strikes Back (Threat)','COMMUNITY_MAINTAINED_SECONDARY','https://boombeach.fandom.com/wiki/Hammerman_Strikes_Back_(Threat)','This event starts on Monday at 8 a.m. GMT and lasts for 24 hours.','2026-08-17T13:17:59Z',[1],[]],
    CYCLE_DR_T_TROPICAL:['boom-cycle-dr-t-tropical','boom-beach','Dr. T Tropical','COMMUNITY_MAINTAINED_SECONDARY','https://boombeach.fandom.com/wiki/Dr._T','Thereafter, the tropical Dr. T challenge will appear on the island of the defeated base every Tuesday and Saturday.','2026-08-15T20:58:20Z',[2,6],[]],
    CYCLE_DR_T_VOLCANO:['boom-cycle-dr-t-volcano','boom-beach','Dr. T Volcano','COMMUNITY_MAINTAINED_SECONDARY','https://boombeach.fandom.com/wiki/Dr._T',"Dr. T's volcano challenge will appear every Wednesday and Sunday.",'2026-08-15T20:58:20Z',[3,0],[]],
    CYCLE_WAR_FACTORY:['boom-cycle-war-factory','boom-beach','War Factory','COMMUNITY_MAINTAINED_SECONDARY','https://boombeach.fandom.com/wiki/The_War_Factory','The War Factory is an event that takes place every Thursday after beating the first War Factory, which is accessible after exploring at least 93 regions on the Archipelago.','2026-08-20T08:53:44Z',[4],[]],
    CYCLE_IMITATION:['boom-cycle-imitation','boom-beach','Imitation Game','COMMUNITY_MAINTAINED_SECONDARY','https://boombeach.fandom.com/wiki/Imitation_Game','The Imitation Game is an event that occurs on Fridays in the event cycle. Like the other events, it lasts for 24 hours, appearing at 8 am GMT.','2026-08-17T13:17:34Z',[5],[]],
    HAY_DERBY:['hay-derby','hay-day','Neighborhood Derby','OFFICIAL_RECURRENCE_RULE','https://support.supercell.com/hay-day/en/articles/about-the-derby.html','This event starts from 8 AM UTC on Tuesdays and ends at 8 AM UTC the following Monday.','2026-08-19T06:06:14Z',[],['2026-08-18','2026-08-25','2026-09-01','2026-09-08','2026-09-15','2026-09-22','2026-09-29']]
  };
  var TRUSTED_RULE_CONFIDENCE={CYCLE_HAMMERMAN:'MEDIUM',CYCLE_DR_T_TROPICAL:'MEDIUM',CYCLE_DR_T_VOLCANO:'MEDIUM',CYCLE_WAR_FACTORY:'MEDIUM',CYCLE_IMITATION:'MEDIUM',HAY_DERBY:'MEDIUM_HIGH'};
  var TRUSTED_RECORD_TIMING={
    'coc-clash-of-cards':'2026-08-01|2026-08-31|DATE_ONLY_RANGE||||UNKNOWN','coc-card-hunt':'2026-08-01|2026-08-31|DATE_ONLY_RANGE||||UNKNOWN','coc-store-card-tasks':'2026-08-03|2026-08-30|DATE_ONLY_RANGE||||UNKNOWN','coc-august-gold-pass':'2026-08-01|2026-08-31|DATE_ONLY_RANGE||||UNKNOWN',
    'coc-chiefs-chronicles':'2026-08-08|2026-08-31|MIXED_START_INSTANT_END_DATE|2026-08-08T08:00:00Z||Asia/Seoul|UTC','coc-awesome-medal':'2026-08-12|2026-08-31|INSTANT_RANGE|2026-08-12T08:00:00Z|2026-08-31T08:00:00Z|Asia/Seoul|UTC',
    'coc-clan-games':'2026-08-22|2026-08-28|DATE_ONLY_RANGE||||UNKNOWN','coc-revenge-deck':'2026-08-26|2026-08-31|DATE_ONLY_RANGE||||UNKNOWN','coc-resource-fest-2':'2026-08-29|2026-08-31|DATE_ONLY_RANGE||||UNKNOWN',
    'coc-medal-access-end':'2026-09-02|2026-09-02|END_INSTANT_ONLY||2026-09-02T08:00:00Z|Asia/Seoul|UTC','coc-card-trading-end':'2026-09-02|2026-09-02|END_INSTANT_ONLY||2026-09-02T08:00:00Z|Asia/Seoul|UTC',
    'coc-september-gold-pass':'2026-09-01|2026-09-30|DATE_ONLY_RANGE||||UNKNOWN','coc-september-cwl':'2026-09-01|2026-09-11|DATE_ONLY_RANGE||||UNKNOWN','coc-john-cena-challenge':'2026-09-01|2026-09-30|DATE_ONLY_RANGE||||UNKNOWN','coc-wwe-chests':'2026-09-01|2026-09-30|DATE_ONLY_RANGE||||UNKNOWN','coc-temporary-wwe-troops':'2026-09-01|2026-09-30|DATE_ONLY_RANGE||||UNKNOWN','coc-battle-options-1':'2026-09-01|2026-09-06|DATE_ONLY_RANGE||||UNKNOWN','coc-money-in-the-bank-rush':'2026-09-01|2026-09-05|DATE_ONLY_RANGE||||UNKNOWN','coc-friend-or-foe-army-camps-1':'2026-09-06|2026-09-09|DATE_ONLY_RANGE||||UNKNOWN','coc-wwe-equipment-blast':'2026-09-09|2026-09-22|INSTANT_RANGE|2026-09-09T08:00:00Z|2026-09-22T08:00:00Z|Asia/Seoul|UTC','coc-wwe-equipment-blast-access':'2026-09-22|2026-09-24|MIXED_START_INSTANT_END_DATE|2026-09-22T08:00:00Z||Asia/Seoul|UTC','coc-battle-options-2':'2026-09-09|2026-09-22|DATE_ONLY_RANGE||||UNKNOWN','coc-resource-collector-boosts-1':'2026-09-12|2026-09-14|DATE_ONLY_RANGE||||UNKNOWN','coc-equipment-boost':'2026-09-16|2026-09-21|DATE_ONLY_RANGE||||UNKNOWN','coc-september-clan-games':'2026-09-22|2026-09-28|DATE_ONLY_RANGE||||UNKNOWN','coc-resource-collector-boosts-2':'2026-09-26|2026-09-28|DATE_ONLY_RANGE||||UNKNOWN','coc-friend-or-foe-army-camps-2':'2026-09-28|2026-09-30|DATE_ONLY_RANGE||||UNKNOWN',
    'brawl-challengers-finals-2026':'2026-09-05|2026-09-06|MIXED_START_INSTANT_END_DATE|2026-09-05T08:00:00Z||Asia/Seoul|Europe/Istanbul','brawl-update-planned-2026-09-01':'2026-09-01|2026-09-01|START_DATE_ONLY||||UNKNOWN','brawl-duo-community-event-2026-09-19':'2026-09-19|2026-09-19|START_DATE_ONLY||||UNKNOWN',
    'boom-crystal-critters':'2026-08-17|2026-08-19|DATE_ONLY_RANGE||||UNKNOWN','boom-gunboat-crab':'2026-08-21|2026-08-23|DATE_ONLY_RANGE||||UNKNOWN','boom-crystal-shield':'2026-08-24|2026-08-26|DATE_ONLY_RANGE||||UNKNOWN','boom-warships-91':'2026-08-24|2026-09-13|DATE_ONLY_RANGE||||UNKNOWN','boom-sonar-ops':'2026-08-28|2026-09-06|DATE_ONLY_RANGE||||UNKNOWN','boom-heavy-mania':'2026-08-28|2026-08-30|DATE_ONLY_RANGE||||UNKNOWN','boom-deployable-turret':'2026-08-31|2026-09-02|DATE_ONLY_RANGE||||UNKNOWN',
    'boom-warrior-bombardier-mania':'2026-09-04|2026-09-06|DATE_ONLY_RANGE||||UNKNOWN','boom-speed-serum':'2026-09-07|2026-09-09|DATE_ONLY_RANGE||||UNKNOWN','boom-grenadier-rocket-choppa-mania':'2026-09-11|2026-09-13|DATE_ONLY_RANGE||||UNKNOWN','boom-cryo-bomb':'2026-09-14|2026-09-16|DATE_ONLY_RANGE||||UNKNOWN','boom-beastly-crab':'2026-09-18|2026-09-20|DATE_ONLY_RANGE||||UNKNOWN','boom-leader-deployment':'2026-09-18|2026-09-24|DATE_ONLY_RANGE||||UNKNOWN','boom-crystal-critters-september':'2026-09-21|2026-09-23|DATE_ONLY_RANGE||||UNKNOWN','boom-joker-crab':'2026-09-25|2026-09-27|DATE_ONLY_RANGE||||UNKNOWN','boom-explosive-drones-september':'2026-09-28|2026-09-30|DATE_ONLY_RANGE||||UNKNOWN','boom-warships-92':'2026-09-28|2026-10-18|DATE_ONLY_RANGE||||UNKNOWN',
    'cr-chaos-triple-draft':'2026-08-17|2026-09-07|DATE_ONLY_RANGE||||UNKNOWN','cr-chaos-epic-only':'2026-08-17|2026-08-24|DATE_ONLY_RANGE||||UNKNOWN','cr-chaos-sudden-death':'2026-08-24|2026-08-31|DATE_ONLY_RANGE||||UNKNOWN','cr-kens-mega-draft':'2026-08-24|2026-08-29|DATE_ONLY_RANGE||||UNKNOWN','cr-chaos-infinite-elixir':'2026-08-31|2026-09-07|DATE_ONLY_RANGE||||UNKNOWN','cr-merge-tactics-11':'2026-09-01|2026-12-01|DATE_ONLY_RANGE||||UNKNOWN','cr-academy-antics':'2026-09-07|2026-10-05|DATE_ONLY_RANGE||||UNKNOWN','cr-2v2-league-september':'2026-09-07|2026-09-21|DATE_ONLY_RANGE||||UNKNOWN','cr-princess-gambit':'2026-09-21|2026-09-26|DATE_ONLY_RANGE||||UNKNOWN','cr-royale-shuffle':'2026-09-21|2026-10-05|DATE_ONLY_RANGE||||UNKNOWN','cr-clashroom-community':'2026-09-22|2026-09-26|DATE_ONLY_RANGE||||UNKNOWN','cr-royale-shuffle-challenge':'2026-09-28|2026-10-05|DATE_ONLY_RANGE||||UNKNOWN'
  };
  function cleanBoundedText(value,max){return typeof value==='string'&&value.length>0&&value.length<=max&&value.trim()===value&&!/[\u0000-\u001f\u007f]/.test(value);}
  function sameArray(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every(function(x,i){return x===b[i];});}
  function validInstant(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(value)&&!Number.isNaN(Date.parse(value));}
  function validEvaluationInstant(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value)&&Number.isFinite(Date.parse(value));}
  function exactKeys(value,allowed){var keys=value&&Object.keys(value);if(!keys||!keys.every(function(k){return allowed.has(k);}))return false;var missing=Array.from(allowed).filter(function(k){return keys.indexOf(k)<0;});return missing.length===0||(allowed===TRUSTED_EVENT_KEYS&&missing.every(function(k){return k==='startInstant'||k==='endInstant'||k==='channelId';}));}
  var TRUSTED_RECORD_CATEGORIES={'coc-clash-of-cards':'special-event','coc-card-hunt':'special-event','coc-store-card-tasks':'special-event','coc-august-gold-pass':'season','coc-chiefs-chronicles':'special-event','coc-awesome-medal':'medal-event','coc-clan-games':'clan-games','coc-revenge-deck':'special-event','coc-resource-fest-2':'special-event','coc-medal-access-end':'medal-event','coc-card-trading-end':'special-event','brawl-challengers-finals-2026':'esports','boom-crystal-critters':'event','boom-gunboat-crab':'event','boom-crystal-shield':'event','boom-warships-91':'warships','boom-sonar-ops':'operation','boom-heavy-mania':'mania','boom-deployable-turret':'event','boom-warrior-bombardier-mania':'mania','boom-speed-serum':'event','boom-grenadier-rocket-choppa-mania':'mania','boom-cryo-bomb':'event','boom-beastly-crab':'event','boom-leader-deployment':'event','boom-crystal-critters-september':'event','boom-joker-crab':'event','boom-explosive-drones-september':'event','boom-warships-92':'warships','cr-chaos-triple-draft':'challenge','cr-chaos-epic-only':'challenge','cr-chaos-sudden-death':'challenge','cr-kens-mega-draft':'challenge','cr-chaos-infinite-elixir':'challenge','cr-merge-tactics-11':'season'};
  Object.assign(TRUSTED_RECORD_CATEGORIES,{'coc-september-gold-pass':'season','coc-september-cwl':'clan-war-league','coc-john-cena-challenge':'challenge','coc-wwe-chests':'special-event','coc-temporary-wwe-troops':'troop-event','coc-battle-options-1':'special-event','coc-money-in-the-bank-rush':'special-event','coc-friend-or-foe-army-camps-1':'troop-event','coc-wwe-equipment-blast':'medal-event','coc-wwe-equipment-blast-access':'medal-event','coc-battle-options-2':'special-event','coc-resource-collector-boosts-1':'resource-boost','coc-equipment-boost':'equipment-event','coc-september-clan-games':'clan-games','coc-resource-collector-boosts-2':'resource-boost','coc-friend-or-foe-army-camps-2':'troop-event','brawl-update-planned-2026-09-01':'game-update','brawl-duo-community-event-2026-09-19':'community-event','cr-academy-antics':'special-event','cr-2v2-league-september':'challenge','cr-princess-gambit':'challenge','cr-royale-shuffle':'special-event','cr-clashroom-community':'community-event','cr-royale-shuffle-challenge':'challenge'});
  function recordPolicy(e){var tags,category=TRUSTED_RECORD_CATEGORIES[e.id],verifiedAt='2026-08-19T06:03:18Z',verifiedDate=null,timeConfidence=null,notice='일정은 변경될 수 있습니다.';if(e.gameId==='clash-of-clans'){tags=/clan-games/.test(e.id)?['clan-games']:/cwl|clan-war-league/.test(e.id)||category==='clan-war-league'?['league']:/gold-pass/.test(e.id)?['season-pass']:e.id==='coc-store-card-tasks'?['free']:['official-news'];if(e.sourceUrl.indexOf('wwe-search-for-cena')>=0)verifiedAt='2026-09-01T08:40:42Z';if(e.id==='coc-wwe-equipment-blast')verifiedAt='2026-09-10T20:06:03Z';if(e.id==='coc-wwe-equipment-blast-access'){verifiedAt='2026-09-11T04:08:00Z';notice='종료 시각 미공개 · 날짜 범위 양끝 포함';}}else if(e.gameId==='brawl-stars'){tags=e.id==='brawl-challengers-finals-2026'?['championship']:['events-quests'];verifiedAt=e.id==='brawl-challengers-finals-2026'?'2026-08-19T06:06:14Z':'2026-08-29T15:00:06Z';if(e.id==='brawl-challengers-finals-2026'){timeConfidence='MEDIUM_HIGH';notice='11:00 시작 시각은 변경될 수 있습니다.';}else if(e.id==='brawl-update-planned-2026-09-01')notice='계획된 시작일 · 공식 영상의 변경 가능성 문구 유지';else notice='종료일 미공개 · Chaos Drops 및 무료 Spike';}else if(e.gameId==='boom-beach'){verifiedAt=null;verifiedDate=e.sourceUrl.indexOf('this-september-on-boom-beach-2')>=0?'2026-08-30':'2026-08-19';tags=/crab/.test(e.id)?['mega-crab']:/mania/.test(e.id)?['troop-mania']:/warships/.test(e.id)?['warships']:e.id==='boom-sonar-ops'?['sonar-ops']:['abilities-boosts'];}else if(e.gameId==='clash-royale'){tags=category==='season'?['season-pass']:/draft/i.test(e.title)?['challenge','draft']:['challenge','special-modes'];if(e.id==='cr-merge-tactics-11')verifiedAt='2026-08-29T18:00:30Z';if(e.sourceUrl.indexOf('new-season-minion-academy')>=0)verifiedAt='2026-09-10T20:06:03Z';}else return null;return{category:category,filterTags:tags,verifiedAt:verifiedAt,verifiedDate:verifiedDate,projectionStart:null,projectionEnd:null,expiry:null,dateConfidence:'HIGH',timeConfidence:timeConfidence,changeNotice:notice};}
  function rulePolicy(r){var hay=r.gameId==='hay-day',refetched=/^(?:CYCLE_DR_T_TROPICAL|CYCLE_WAR_FACTORY|CYCLE_IMITATION)$/.test(r.eventFamily);return{category:hay?'derby':'event',filterTags:[hay?'derby':'cycle-of-evil'],verifiedAt:hay?'2026-08-19T06:06:14Z':null,verifiedDate:hay?null:refetched?'2026-08-25':'2026-08-19',projectionStart:hay?'2026-08-18':'2026-08-19',projectionEnd:'2026-09-29',expiry:hay?'2026-10-05':'2026-09-29',dateConfidence:r.confidence,timeConfidence:hay?'MEDIUM_HIGH':null,changeNotice:'반복 규칙 기반 예상이며 변경될 수 있습니다.'};}
  function policyMatches(value,policy){return policy&&Object.keys(policy).every(function(k){return Array.isArray(policy[k])?sameArray(value[k],policy[k]):value[k]===policy[k];});}
  function validTrustedCalendarEvent(e){
    if(!exactKeys(e,TRUSTED_EVENT_KEYS)||e.official!==false||!['HIGH_CONFIDENCE','EXPECTED'].includes(e.status)||!['HIGH','MEDIUM_HIGH','MEDIUM'].includes(e.confidence)||!['OFFICIAL_CONTEXT_YEAR','OFFICIAL_RECURRENCE_RULE','COMMUNITY_MAINTAINED_SECONDARY'].includes(e.authority))return false;
    if(!/^(?:clash-of-clans|brawl-stars|boom-beach|clash-royale|hay-day)$/.test(String(e.gameId||''))||!/^[-a-z0-9]{1,100}$/.test(String(e.id||''))||!/^[A-Z][A-Z0-9_]{1,79}$/.test(String(e.eventFamily||''))||!String(e.title||'').trim()||String(e.title).length>160||!String(e.sourceQuote||'').trim()||String(e.sourceQuote).length>400)return false;
    if(!validDate(e.startDate)||!validDate(e.endDate)||e.endDate<e.startDate||!Array.isArray(e.filterTags)||e.filterTags.some(function(x){return !cleanBoundedText(x,40);})||!cleanBoundedText(e.title,160)||!cleanBoundedText(e.sourceQuote,400)||!cleanBoundedText(e.changeNotice,120)||!policyMatches(e,e.status==='HIGH_CONFIDENCE'?recordPolicy(e):rulePolicy(e)))return false;
    var record=TRUSTED_RECORD_BINDINGS[e.id],rule=TRUSTED_RULE_BINDINGS[e.eventFamily],binding=e.status==='HIGH_CONFIDENCE'?record:rule;if(!binding||e.gameId!==binding[e.status==='HIGH_CONFIDENCE'?0:1]||e.title!==binding[e.status==='HIGH_CONFIDENCE'?1:2]||e.eventFamily!==(e.status==='HIGH_CONFIDENCE'?binding[2]:e.eventFamily)||e.authority!==(e.status==='HIGH_CONFIDENCE'?'OFFICIAL_CONTEXT_YEAR':binding[3])||e.sourceUrl!==binding[e.status==='HIGH_CONFIDENCE'?3:4]||e.sourceQuote!==binding[e.status==='HIGH_CONFIDENCE'?4:5])return false;if(e.sourceUrl==='https://www.youtube.com/watch?v=qhvPlcwJUvk'?e.channelId!=='UCooVYzDxdwTtGYAkcPmOgOw':e.channelId!=null)return false;
    if(e.status==='HIGH_CONFIDENCE'&&[e.startDate,e.endDate,e.datePrecision,e.startInstant||'',e.endInstant||'',e.timezone||'',e.sourceTimeZone].join('|')!==TRUSTED_RECORD_TIMING[e.id])return false;
    var span=(Date.parse(e.endDate+'T00:00:00Z')-Date.parse(e.startDate+'T00:00:00Z'))/86400000,mergeSeasonException=e.id==='cr-merge-tactics-11'&&span===91;if(span<0||(span>62&&!mergeSeasonException)||!['DATE_ONLY_RANGE','MIXED_START_INSTANT_END_DATE','INSTANT_RANGE','END_INSTANT_ONLY','START_DATE_ONLY'].includes(e.datePrecision))return false;
    if(e.datePrecision==='DATE_ONLY_RANGE'&&(e.timezone!==null||e.sourceTimeZone!=='UNKNOWN'||e.startInstant||e.endInstant))return false;
    if(e.datePrecision==='START_DATE_ONLY'&&(e.startDate!==e.endDate||e.startInstant||e.endInstant||e.timezone!==null||e.sourceTimeZone!=='UNKNOWN'))return false;
    if(e.datePrecision==='MIXED_START_INSTANT_END_DATE'&&(!validInstant(e.startInstant)||e.endInstant||e.startInstant.slice(0,10)!==e.startDate||e.timezone!=='Asia/Seoul'||!cleanBoundedText(e.sourceTimeZone,64)))return false;
    if(e.datePrecision==='INSTANT_RANGE'&&(!validInstant(e.startInstant)||!validInstant(e.endInstant)||Date.parse(e.endInstant)<=Date.parse(e.startInstant)||e.startInstant.slice(0,10)!==e.startDate||e.endInstant.slice(0,10)!==e.endDate||e.timezone!=='Asia/Seoul'||e.sourceTimeZone!=='UTC'))return false;
    if(e.datePrecision==='END_INSTANT_ONLY'&&(!validInstant(e.endInstant)||e.startInstant||e.startDate!==e.endDate||e.endInstant.slice(0,10)!==e.endDate||e.timezone!=='Asia/Seoul'||e.sourceTimeZone!=='UTC'))return false;
    if(e.status==='EXPECTED'&&(e.confidence!==TRUSTED_RULE_CONFIDENCE[e.eventFamily]||e.dateConfidence!==TRUSTED_RULE_CONFIDENCE[e.eventFamily]))return false;
    if(e.status==='EXPECTED'&&e.gameId==='boom-beach'){var timed=e.eventFamily==='CYCLE_HAMMERMAN'||e.eventFamily==='CYCLE_IMITATION';if(e.id!==binding[0]+'-'+e.startDate||binding[7].indexOf(new Date(e.startDate+'T00:00:00Z').getUTCDay())<0)return false;if(timed){if(e.endDate!==addUtcDays(e.startDate,1)||e.startInstant!==e.startDate+'T08:00:00Z'||e.endInstant!==e.endDate+'T08:00:00Z'||e.datePrecision!=='INSTANT_RANGE'||e.timezone!=='Asia/Seoul'||e.sourceTimeZone!=='UTC')return false;}else if(e.startDate!==e.endDate||e.datePrecision!=='DATE_ONLY_RANGE'||e.startInstant||e.endInstant||e.timezone!==null||e.sourceTimeZone!=='UNKNOWN')return false;}
    if(e.status==='EXPECTED'&&e.gameId==='hay-day'&&(e.id!==binding[0]+'-expected-'+e.startDate||binding[8].indexOf(e.startDate)<0||e.endDate!==addUtcDays(e.startDate,6)||e.startInstant!==e.startDate+'T08:00:00Z'||e.endInstant!==e.endDate+'T08:00:00Z'||e.datePrecision!=='INSTANT_RANGE'))return false;
    return !(e.status==='HIGH_CONFIDENCE'&&(e.confidence!=='HIGH'||e.authority!=='OFFICIAL_CONTEXT_YEAR'))&&!(e.status==='EXPECTED'&&e.authority==='OFFICIAL_CONTEXT_YEAR');
  }
  function validTrustedCalendarRule(r){
    if(!exactKeys(r,TRUSTED_RULE_KEYS)||r.official!==false||r.status!=='EXPECTED'||!['MEDIUM_HIGH','MEDIUM'].includes(r.confidence)||!['OFFICIAL_RECURRENCE_RULE','COMMUNITY_MAINTAINED_SECONDARY'].includes(r.authority)||!validDate(r.projectionStart)||!validDate(r.projectionEnd)||!validDate(r.expiry)||!validInstant(r.sourceRevision)||!policyMatches(r,rulePolicy(r)))return false;
    if(!/^(?:boom-beach|hay-day)$/.test(String(r.gameId||''))||!/^[-a-z0-9]{1,100}$/.test(String(r.id||''))||!/^[A-Z][A-Z0-9_]{1,79}$/.test(String(r.eventFamily||''))||!cleanBoundedText(r.title,160)||!cleanBoundedText(r.sourceQuote,400)||!cleanBoundedText(r.changeNotice,120)||!Array.isArray(r.filterTags)||r.filterTags.some(function(x){return !cleanBoundedText(x,40);})||!Array.isArray(r.weekdays)||!Array.isArray(r.starts))return false;
    var binding=TRUSTED_RULE_BINDINGS[r.eventFamily];if(!binding||r.id!==binding[0]||r.gameId!==binding[1]||r.title!==binding[2]||r.authority!==binding[3]||r.sourceUrl!==binding[4]||r.sourceQuote!==binding[5]||r.sourceRevision!==binding[6]||!sameArray(r.weekdays,binding[7])||!sameArray(r.starts,binding[8])||r.confidence!==TRUSTED_RULE_CONFIDENCE[r.eventFamily])return false;
    if(r.gameId==='boom-beach'){var timed=r.eventFamily==='CYCLE_HAMMERMAN'||r.eventFamily==='CYCLE_IMITATION';return r.authority==='COMMUNITY_MAINTAINED_SECONDARY'&&r.projectionEnd==='2026-09-29'&&r.weekdays.length>0&&r.weekdays.every(function(d){return Number.isInteger(d)&&d>=0&&d<=6;})&&r.starts.length===0&&(timed?r.timezone==='Asia/Seoul'&&r.sourceTimeZone==='UTC':r.timezone===null&&r.sourceTimeZone==='UNKNOWN');}
    return r.authority==='OFFICIAL_RECURRENCE_RULE'&&r.weekdays.length===0&&r.starts.length===7&&r.starts.every(validDate)&&r.timezone==='Asia/Seoul'&&r.sourceTimeZone==='UTC';
  }
  function addUtcDays(date,days){var d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
  function projectTrustedCalendar(records,rules,windowStart,windowEnd){if(!validDate(windowStart)||!validDate(windowEnd)||windowStart!=='2026-08-19'||windowEnd!=='2026-09-30')return[];var out=(Array.isArray(records)?records:[]).filter(validTrustedCalendarEvent).map(function(e){return Object.assign({},e,{filterTags:e.filterTags.slice()});});(Array.isArray(rules)?rules:[]).filter(validTrustedCalendarRule).forEach(function(r){function common(){return{gameId:r.gameId,title:r.title,category:r.category,eventFamily:r.eventFamily,status:r.status,confidence:r.confidence,dateConfidence:r.dateConfidence,timeConfidence:r.timeConfidence,authority:r.authority,sourceUrl:r.sourceUrl,sourceQuote:r.sourceQuote,channelId:null,verifiedAt:r.verifiedAt,verifiedDate:r.verifiedDate,projectionStart:r.projectionStart,projectionEnd:r.projectionEnd,expiry:r.expiry,filterTags:r.filterTags.slice(),official:false,changeNotice:r.changeNotice};}if(r.gameId==='boom-beach'){for(var date=r.projectionStart;date<=r.projectionEnd;date=addUtcDays(date,1)){if(r.weekdays.indexOf(new Date(date+'T00:00:00Z').getUTCDay())<0)continue;var timed=r.eventFamily==='CYCLE_HAMMERMAN'||r.eventFamily==='CYCLE_IMITATION',end=timed?addUtcDays(date,1):date,timing=timed?{startInstant:date+'T08:00:00Z',endInstant:end+'T08:00:00Z',datePrecision:'INSTANT_RANGE',timezone:'Asia/Seoul',sourceTimeZone:'UTC'}:{datePrecision:'DATE_ONLY_RANGE',timezone:null,sourceTimeZone:'UNKNOWN'};out.push(Object.assign({id:r.id+'-'+date,startDate:date,endDate:end},timing,common()));}}else r.starts.forEach(function(start){var end=addUtcDays(start,6);out.push(Object.assign({id:r.id+'-expected-'+start,startDate:start,endDate:end,startInstant:start+'T08:00:00Z',endInstant:end+'T08:00:00Z',datePrecision:'INSTANT_RANGE',timezone:'Asia/Seoul',sourceTimeZone:'UTC'},common()));});});return out.filter(validTrustedCalendarEvent);}
  function suppressTrustedConflicts(trusted,official,_catalog,expectedGameId){var allValid=(Array.isArray(trusted)?trusted:[]).filter(validTrustedCalendarEvent),validGame=/^(?:clash-of-clans|brawl-stars|boom-beach|clash-royale|hay-day)$/.test(String(expectedGameId||''));if(!validGame||allValid.some(function(e){return e.gameId!==expectedGameId;}))return allValid;var aliases={};allValid.forEach(function(e){var key=e.gameId+'|'+String(e.title).normalize('NFKC').trim().toLocaleLowerCase();if(!aliases[key])aliases[key]=e.eventFamily;else if(aliases[key]!==e.eventFamily)aliases[key]=null;});var conflicts={};(Array.isArray(official)?official:[]).filter(function(e){return actionableOfficialEvidence(e)&&validProjectedOfficialCalendarEvent(e,expectedGameId);}).forEach(function(e){var family=aliases[expectedGameId+'|'+String(e.title||'').normalize('NFKC').trim().toLocaleLowerCase()];if(family)(conflicts[expectedGameId+'|'+family]||(conflicts[expectedGameId+'|'+family]=[])).push(e);});return allValid.filter(function(e){return !(conflicts[e.gameId+'|'+e.eventFamily]||[]).some(function(o){return e.startDate<=o.endDate&&o.startDate<=e.endDate;});});}
  function trustedAgendaSourceLabel(e){if(!validTrustedCalendarEvent(e))return'';if(e.status==='HIGH_CONFIDENCE')return'고신뢰 · Supercell 공식 본문 · 연도는 기사 문맥';return e.authority==='OFFICIAL_RECURRENCE_RULE'?'예상 · 공식 반복 규칙':'예상 · 커뮤니티 반복 일정';}

  function classifyCalendarEvent(e){
    if(!e)return'UNCONFIRMED';
    if(e.sourceState==='STALE_CACHE'||e.sourceState==='PRESERVED_CACHE_PARTIAL')return'UNCONFIRMED';
    if(e.status==='HIGH_CONFIDENCE'||e.status==='EXPECTED')return validTrustedCalendarEvent(e)?e.status:'UNCONFIRMED';
    if(e.status==='CREATOR_DATED')return validCreatorCalendarEvent(e)?'CREATOR_DATED':'UNCONFIRMED';
    if(e.status==='OFFICIAL'&&e.official===true&&validProjectedOfficialCalendarEvent(e))return'OFFICIAL';
    return'UNCONFIRMED';
  }
  function evaluation(value){
    if(value instanceof Date)value=value.toISOString();
    if(validDate(value))return{instant:null,date:value};
    if(!validEvaluationInstant(value))return null;
    var instant=Date.parse(value),local=new Date(instant+9*3600000);
    return{instant:instant,date:local.toISOString().slice(0,10)};
  }
  function actionablePhase(e,now){
    var at=evaluation(now),truth=classifyCalendarEvent(e);if(!at||truth==='UNCONFIRMED'||!validDate(e.startDate)||!validDate(e.endDate))return'none';
    if(at.instant!==null&&validInstant(e.startInstant)&&at.instant<Date.parse(e.startInstant))return'upcoming';
    if(at.instant!==null&&validInstant(e.endInstant)&&at.instant>=Date.parse(e.endInstant))return'ended';
    if(e.endDate<at.date)return'ended';if(e.startDate>at.date)return'upcoming';return'active';
  }
  function isActionableCalendarEventAt(e,now){return actionablePhase(e,now)==='active';}
  function authorityRank(e){var truth=classifyCalendarEvent(e);return truth==='OFFICIAL'?0:truth==='CREATOR_DATED'?1:truth==='HIGH_CONFIDENCE'?2:truth==='EXPECTED'?3:4;}
  function rankCalendarEvents(events,boundary){return (Array.isArray(events)?events:[]).slice().sort(function(a,b){return String(a[boundary]||'').localeCompare(String(b[boundary]||''))||authorityRank(a)-authorityRank(b)||String(a.title||'').localeCompare(String(b.title||''));});}
  function buildPriorityAgenda(events,now,limit){var max=Number.isInteger(limit)&&limit>0?limit:3;if(!evaluation(now))return{active:[],upcoming:[]};var values=(Array.isArray(events)?events:[]).filter(function(e){return classifyCalendarEvent(e)!=='UNCONFIRMED'&&(validProjectedOfficialCalendarEvent(e)||validCreatorCalendarEvent(e)||validTrustedCalendarEvent(e));});return{active:rankCalendarEvents(values.filter(function(e){return actionablePhase(e,now)==='active';}),'endDate').slice(0,max),upcoming:rankCalendarEvents(values.filter(function(e){return actionablePhase(e,now)==='upcoming';}),'startDate').slice(0,max)};}
  function priorityAgendaWindow(today){if(!validDate(today))return null;var d=new Date(today+'T00:00:00Z'),last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+2,0));return{today:today,last:last.toISOString().slice(0,10)};}
  function buildPriorityAgendaWindow(events,now,limit){var at=evaluation(now),window=at&&priorityAgendaWindow(at.date);if(!window)return{active:[],upcoming:[]};return buildPriorityAgenda((Array.isArray(events)?events:[]).filter(function(e){return e&&e.endDate>=window.today&&e.startDate<=window.last;}),now,limit);}
  function localizedIsoDate(value){if(!validDate(value))return null;var parts=value.split('-').map(Number);return parts[0]+'년 '+parts[1]+'월 '+parts[2]+'일';}
  function formatKstInstant(value){if(!validInstant(value))return null;var d=new Date(Date.parse(value)+9*3600000);return d.getUTCFullYear()+'년 '+(d.getUTCMonth()+1)+'월 '+d.getUTCDate()+'일 '+String(d.getUTCHours()).padStart(2,'0')+':'+String(d.getUTCMinutes()).padStart(2,'0')+' KST';}
  function formatEventDisplayDate(event){if(!event||!validDate(event.startDate)||!validDate(event.endDate)||event.endDate<event.startDate)return'날짜 미확인';var start=localizedIsoDate(event.startDate),end=localizedIsoDate(event.endDate),precision=event.datePrecision,instantStart,instantEnd;if(validTrustedCalendarEvent(event)){if(precision==='INSTANT_RANGE'&&(instantStart=formatKstInstant(event.startInstant))&&(instantEnd=formatKstInstant(event.endInstant)))return instantStart+' – '+instantEnd;if(precision==='MIXED_START_INSTANT_END_DATE'&&(instantStart=formatKstInstant(event.startInstant)))return instantStart+' – '+end;if(precision==='END_INSTANT_ONLY'&&(instantEnd=formatKstInstant(event.endInstant)))return instantEnd+' 마감';}if(precision==='END_ONLY'||precision==='END_DATE_ONLY')return end+'까지';if(precision==='START_INSTANT_ONLY'||precision==='START_DATE_ONLY')return start+' 시작';if(event.startDate===event.endDate)return start;return start+' – '+end;}
  function formatDisplayTimestamp(value,timeZone){if(typeof value!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+)?Z$/.test(value))return'검증 기록 없음';var date=new Date(value);if(!Number.isFinite(date.getTime()))return'검증 기록 없음';try{var parts=new Intl.DateTimeFormat('ko-KR',{timeZone:timeZone||'Asia/Seoul',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),values={};parts.forEach(function(part){if(part.type!=='literal')values[part.type]=part.value;});if(!values.year||!values.month||!values.day||!values.hour||!values.minute)return'검증 기록 없음';return Number(values.year)+'. '+Number(values.month)+'. '+Number(values.day)+'. '+values.hour+':'+values.minute;}catch(_error){return'검증 기록 없음';}}
  function formatVerificationDisplay(value,timeZone){if(validDate(value)){var p=value.split('-').map(Number);return p[0]+'. '+p[1]+'. '+p[2]+'.';}return formatDisplayTimestamp(value,timeZone);}
  function canonicalSlug(value){return String(value||'').normalize('NFKD').toLocaleLowerCase().replace(/&amp;/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);}
  function canonicalizeOfficialEvent(e,gameId,strictScope){if(!e)return null;var raw=Object.assign({},e);delete raw.canonicalEventKey;var game=String(gameId||raw.gameId||'clash-of-clans'),strict=strictScope===undefined?Boolean(gameId):strictScope;if(!/^[a-z0-9-]+$/.test(game)||raw.gameId&&raw.gameId!==game||!validProjectedOfficialCalendarEvent(raw,strict?game:undefined))return null;var p=projectOfficialEvent(raw);return Object.assign({},p,{canonicalEventKey:game+'/'+canonicalSlug(p.title)+'/'+p.startDate.slice(0,4)});}
  function validateCreatorCallbackEnvelope(value,gameId,token,reviewedCutoff){var keys=['events','gameId','requestToken','reviewedCutoff','schemaVersion','state'];if(!value||Object.keys(value).sort().join('|')!==keys.sort().join('|')||value.schemaVersion!==1||value.gameId!==gameId||value.requestToken!==token||value.reviewedCutoff!==reviewedCutoff||!validDate(value.reviewedCutoff)||!Array.isArray(value.events)||!['BUNDLED_REVIEWED','EMPTY_FAIL_CLOSED'].includes(value.state))return null;if((value.state==='BUNDLED_REVIEWED')!==(value.events.length>0)||value.events.length>24||!value.events.every(function(e){return e.gameId===gameId&&validCreatorEvent(e);}))return null;return{state:value.state,events:value.events.slice()};}
  function calendarCellAriaLabel(date,events,selection){var values=Array.isArray(events)?events:[],parts=[],truths=values.map(classifyCalendarEvent),official=truths.filter(function(x){return x==='OFFICIAL';}).length,highConfidence=truths.filter(function(x){return x==='HIGH_CONFIDENCE';}).length,expected=truths.filter(function(x){return x==='EXPECTED';}).length,creator=truths.filter(function(x){return x==='CREATOR_DATED';}).length,unconfirmed=truths.filter(function(x){return x==='UNCONFIRMED';}).length,freshPartial=values.some(function(e){return e.sourceState==='FRESH_SOURCE_PARTIAL'}),preservedPartial=values.some(function(e){return e.sourceState==='PRESERVED_CACHE_PARTIAL'}),stale=values.some(function(e){return e.sourceState==='STALE_CACHE'}),representative=selection&&selection.visible&&selection.visible[0];if(representative)parts.push(String(representative.title));if(selection&&selection.overflow)parts.push('+'+selection.overflow);if(official)parts.push('공식 '+official+'개');if(highConfidence)parts.push('고신뢰 '+highConfidence+'개');if(expected)parts.push('예상 '+expected+'개');if(creator)parts.push('크리에이터 검토 '+creator+'개');if(unconfirmed)parts.push('미확정 '+unconfirmed+'개');if(freshPartial)parts.push('부분 갱신 새 자료 포함');if(preservedPartial)parts.push('부분 갱신 보존 캐시 포함');if(stale)parts.push('오래된 캐시 포함');var verified=values.map(function(e){return e&&e.lastVerifiedAt}).filter(Boolean).sort().pop();if(verified)parts.push('이벤트 확인 '+formatDisplayTimestamp(verified));if(!values.length)parts.push('일정 0개');return Number(date.slice(5,7))+'월 '+Number(date.slice(8,10))+'일, '+parts.join(', ').replace(/, (공식|고신뢰|예상|크리에이터 검토|미확정)/g,' · $1');}
  function officialAgendaSourceLabel(e){if(!e||e.official!==true)return'';var label;if(!('sourceState' in e)||e.sourceState==='BUNDLED')label='공식 · 번들 검증';else if(e.sourceState==='FRESH_NETWORK')label='공식 · 원격 검증';else if(e.sourceState==='FRESH_SOURCE_PARTIAL')label='공식 · 부분 갱신 새 자료';else if(e.sourceState==='PRESERVED_CACHE_PARTIAL')label='미확정 · 부분 갱신 보존 캐시 · 공식으로 사용하지 않음';else if(e.sourceState==='CACHED_FRESH')label='공식 · 저장된 검증';else if(e.sourceState==='STALE_CACHE')label='미확정 · 오래된 캐시 · 공식으로 사용하지 않음';else label='공식 · 출처 상태 미확인';return label+(e.lastVerifiedAt?' · 확인 '+formatDisplayTimestamp(e.lastVerifiedAt):'');}
  function selectCalendarDayEvents(events,limit){var max=Number.isInteger(limit)&&limit>0?limit:3,values=(Array.isArray(events)?events:[]).filter(function(e){return e&&classifyCalendarEvent(e)!=='UNCONFIRMED'&&validDate(e.startDate)&&validDate(e.endDate);}).sort(function(a,b){return authorityRank(a)-authorityRank(b)||String(a.id||'').localeCompare(String(b.id||''));});return{visible:values.slice(0,max),overflow:Math.max(0,values.length-max)};}
  function buildMonthAgenda(events,todayIso,lastIso,limit){var max=Number.isInteger(limit)&&limit>0?limit:8;if(!validDate(todayIso)||!validDate(lastIso))return[];return(Array.isArray(events)?events:[]).filter(function(e){return e&&classifyCalendarEvent(e)!=='UNCONFIRMED'&&validDate(e.startDate)&&validDate(e.endDate)&&e.endDate>=todayIso&&e.startDate<=lastIso;}).sort(function(a,b){var aa=a.startDate<=todayIso?0:1,ba=b.startDate<=todayIso?0:1;return aa-ba||String(aa===0?a.endDate:a.startDate).localeCompare(String(ba===0?b.endDate:b.startDate))||authorityRank(a)-authorityRank(b)||String(a.id||'').localeCompare(String(b.id||''));}).slice(0,max);}
  function calendarFocusIndex(count,preferred,today){return Number.isInteger(preferred)&&preferred>=0&&preferred<count?preferred:Number.isInteger(today)&&today>=0&&today<count?today:count>0?0:-1}
  function moveCalendarFocus(index,key,count){var next=index;if(key==='ArrowLeft')next=index-1;else if(key==='ArrowRight')next=index+1;else if(key==='ArrowUp')next=index-7;else if(key==='ArrowDown')next=index+7;else if(key==='Home')next=index-index%7;else if(key==='End')next=index+(6-index%7);return next<0||next>=count?index:next}
  var EVENT_META={season:{label:'시즌',symbol:'◆'},league:{label:'리그',symbol:'▰'},'clan-games':{label:'게임',symbol:'★'},raid:{label:'레이드',symbol:'◇'},'special-event':{label:'특별 이벤트',symbol:'✦'},'medal-event':{label:'메달 이벤트',symbol:'⬟'},spotlight:{label:'스포트라이트',symbol:'◉'}};
  function cloneBriefValue(value,seen){
    if(value===null||typeof value!=='object')return value;
    var memo=seen||new WeakMap(),known=memo.get(value);if(known)return known;
    var copy=Array.isArray(value)?[]:{};memo.set(value,copy);
    Object.keys(value).forEach(function(key){copy[key]=cloneBriefValue(value[key],memo);});return copy;
  }
  function buildDailyBrief(events,programs,guides,now){
    var empty={ongoing:[],highConfidenceTodayCount:0,expectedTodayCount:0,nextOfficial:null,inGameChecks:[],playerNotes:[]};if(!evaluation(now))return empty;var dated=Array.isArray(events)?events:[];
    function range(e){return e&&validDate(e.startDate)&&validDate(e.endDate)&&e.startDate<=e.endDate;}function admitted(e,truth){return range(e)&&classifyCalendarEvent(e)===truth;}
    var ongoing=dated.filter(function(e){return admitted(e,'OFFICIAL')&&isActionableCalendarEventAt(e,now);}).sort(function(a,b){return a.endDate.localeCompare(b.endDate)||a.startDate.localeCompare(b.startDate)||authorityRank(a)-authorityRank(b)||String(a.id||'').localeCompare(String(b.id||''));}).slice(0,4).map(function(e){return cloneBriefValue(e);});
    var highConfidenceTodayCount=dated.filter(function(e){return admitted(e,'HIGH_CONFIDENCE')&&isActionableCalendarEventAt(e,now);}).length;
    var expectedTodayCount=dated.filter(function(e){return admitted(e,'EXPECTED')&&isActionableCalendarEventAt(e,now);}).length;
    var future=dated.filter(function(e){return admitted(e,'OFFICIAL')&&actionablePhase(e,now)==='upcoming';}).sort(function(a,b){return a.startDate.localeCompare(b.startDate)||a.endDate.localeCompare(b.endDate)||String(a.id||'').localeCompare(String(b.id||''));});
    var checks=(Array.isArray(programs)?programs:[]).filter(function(p){return p&&p.official===true&&p.status==='OFFICIAL_UNDATED'&&!('startDate' in p)&&!('endDate' in p);}).slice(0,3).map(function(p){return cloneBriefValue(p);});
    var notes=(Array.isArray(guides)?guides:[]).filter(function(g){return g&&typeof g.title==='string'&&g.title.trim()&&typeof g.summary==='string'&&g.summary.trim()&&g.official!==true;}).slice(0,2).map(function(g){return cloneBriefValue(g);});
    return{ongoing:ongoing,highConfidenceTodayCount:highConfidenceTodayCount,expectedTodayCount:expectedTodayCount,nextOfficial:future.length?cloneBriefValue(future[0]):null,inGameChecks:checks,playerNotes:notes};
  }
  function isTodayCalendarEvent(e,now){return now===undefined?['OFFICIAL','HIGH_CONFIDENCE','EXPECTED','CREATOR_DATED'].includes(classifyCalendarEvent(e)):isActionableCalendarEventAt(e,now);}
  function eventMeta(category){return EVENT_META[category]||{label:'일정',symbol:'•'};}
  return { classifyCalendarEvent:classifyCalendarEvent, isTodayCalendarEvent:isTodayCalendarEvent, isActionableCalendarEventAt:isActionableCalendarEventAt, validTrustedCalendarEvent:validTrustedCalendarEvent, validTrustedCalendarRule:validTrustedCalendarRule, projectTrustedCalendar:projectTrustedCalendar, suppressTrustedConflicts:suppressTrustedConflicts, trustedAgendaSourceLabel:trustedAgendaSourceLabel, generateMonth:generateMonth, eventsForDate:eventsForDate, eventMeta:eventMeta, eventTitleKo:eventTitleKo, eventDescriptionKo:eventDescriptionKo, eventDisplayCategory:eventDisplayCategory, sortMonthHighlights:sortMonthHighlights, classifyNews:classifyNews, normalizeOfficialUrl:normalizeOfficialUrl, classifyCreatorTitle:classifyCreatorTitle, normalizeCreatorVideoUrl:normalizeCreatorVideoUrl, normalizeCreatorThumbnailUrl:normalizeCreatorThumbnailUrl, cleanExpectedTitle:cleanExpectedTitle, daysInMonth:daysInMonth, validOfficialEvent:validOfficialEvent, validCreatorEvent:validCreatorEvent, validCreatorCalendarEvent:validCreatorCalendarEvent, validCreatorEvidenceManifest:validCreatorEvidenceManifest, parseCreatorDateExpression:parseCreatorDateExpression, creatorChannelPolicy:creatorChannelPolicy, reconcileCalendarEvents:reconcileCalendarEvents, rankCalendarEvents:rankCalendarEvents, selectCalendarDayEvents:selectCalendarDayEvents, buildPriorityAgenda:buildPriorityAgenda, priorityAgendaWindow:priorityAgendaWindow, buildPriorityAgendaWindow:buildPriorityAgendaWindow, formatEventDisplayDate:formatEventDisplayDate, formatDisplayTimestamp:formatDisplayTimestamp, formatVerificationDisplay:formatVerificationDisplay, canonicalizeOfficialEvent:canonicalizeOfficialEvent, validateCreatorCallbackEnvelope:validateCreatorCallbackEnvelope, calendarCellAriaLabel:calendarCellAriaLabel, officialAgendaSourceLabel:officialAgendaSourceLabel, buildMonthAgenda:buildMonthAgenda, calendarFocusIndex:calendarFocusIndex, moveCalendarFocus:moveCalendarFocus, mergeOfficialEvents:mergeOfficialEvents, buildDailyBrief:buildDailyBrief };
}));
