(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EmergencyCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
var GAME_IDS=Object.freeze(['clash-of-clans','brawl-stars','boom-beach','clash-royale','hay-day']);
var SEVERITIES=Object.freeze(['CRITICAL','HIGH','NOTICE']),STATUSES=Object.freeze(['CONFIRMED','INVESTIGATING','MONITORING','RESOLVED']),AUTHORITIES=Object.freeze(['OFFICIAL','VERIFIED_CREATOR','PLAYER_REPORT']),KINDS=Object.freeze(['BUG','SERVICE_ISSUE','EVENT_CHANGE']);
var ROOT_KEYS=['issues','reviewedAt','schemaVersion'],ACTIVE_KEYS=['action','authority','firstSeenAt','gameId','id','kind','lastVerifiedAt','reviewBy','severity','sourceQuote','sourceUrl','status','summary','title'],RESOLVED_KEYS=ACTIVE_KEYS.concat(['resolution','resolvedAt']).sort();
var EXACT_URLS=Object.freeze(['https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/','https://supercell.com/en/games/clashofclans/blog/release-notes/august-update-3/','https://support.supercell.com/clash-of-clans/en/index.html','https://support.supercell.com/boom-beach/en/index.html','https://supercell.com/en/games/clashroyale/blog/news/new-collection-levels-and-mastery-changes/']);
function fail(){throw new TypeError('Invalid emergency dataset')}
function exact(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('\0')===keys.slice().sort().join('\0')}
function clean(value,min,max){return typeof value==='string'&&value.length>=min&&value.length<=max&&value===value.trim()&&!/[\u0000-\u001f\u007f<>]/.test(value)&&!/(?:[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:^|[^\uD800-\uDBFF])[\uDC00-\uDFFF])/.test(value)}
function instant(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value))return false;var date=new Date(value);return !Number.isNaN(date.valueOf())&&date.toISOString()===value}
function url(value){if(!EXACT_URLS.includes(value))return false;try{var parsed=new URL(value);return parsed.protocol==='https:'&&!parsed.username&&!parsed.password&&!parsed.port&&!parsed.search&&!parsed.hash&&parsed.href===value}catch(_error){return false}}
function normalizeIssue(issue,datasetReviewedAt){var resolved=issue&&issue.status==='RESOLVED',keys=resolved?RESOLVED_KEYS:ACTIVE_KEYS;if(!exact(issue,keys))fail();
  if(!clean(issue.id,1,64)||!/^[a-z0-9][a-z0-9._:-]*$/.test(issue.id)||!GAME_IDS.includes(issue.gameId)||!KINDS.includes(issue.kind)||!SEVERITIES.includes(issue.severity)||!STATUSES.includes(issue.status)||!AUTHORITIES.includes(issue.authority))fail();
  if(!clean(issue.title,1,100)||!clean(issue.summary,1,600)||!clean(issue.action,1,400)||!clean(issue.sourceQuote,1,500)||!url(issue.sourceUrl)||![issue.firstSeenAt,issue.lastVerifiedAt,issue.reviewBy].every(instant))fail();
  var first=Date.parse(issue.firstSeenAt),verified=Date.parse(issue.lastVerifiedAt),review=Date.parse(issue.reviewBy),datasetReview=Date.parse(datasetReviewedAt);if(first>verified||verified>datasetReview||review<verified)fail();
  if(issue.authority!=='OFFICIAL'&&issue.status!=='MONITORING')fail();if(issue.authority==='OFFICIAL'&&!['CONFIRMED','INVESTIGATING','RESOLVED'].includes(issue.status))fail();if(issue.status==='MONITORING'&&(review-verified>48*60*60*1000||!(issue.title+issue.summary).includes('공식 장애 확인 없음')))fail();
  if(issue.kind==='EVENT_CHANGE'&&(issue.authority!=='OFFICIAL'||issue.status!=='CONFIRMED'||issue.severity!=='NOTICE'||review-verified>7*24*60*60*1000))fail();
  if(issue.kind!=='EVENT_CHANGE'&&issue.status!=='RESOLVED'&&review-verified>48*60*60*1000)fail();
  if(resolved){var resolvedAt=Date.parse(issue.resolvedAt);if(!instant(issue.resolvedAt)||resolvedAt<verified||resolvedAt>datasetReview||!clean(issue.resolution,1,400))fail()}
  return Object.freeze(Object.assign({},issue));
}
function normalizeDataset(value){if(!exact(value,ROOT_KEYS)||value.schemaVersion!==2||!instant(value.reviewedAt)||!Array.isArray(value.issues)||value.issues.length>100)fail();var ids=new Set(),issues=value.issues.map(function(issue){var out=normalizeIssue(issue,value.reviewedAt);if(ids.has(out.id))fail();ids.add(out.id);return out});var raw=JSON.stringify(value);if(raw.length>128*1024)fail();return Object.freeze({schemaVersion:2,reviewedAt:value.reviewedAt,issues:Object.freeze(issues)})}
function validateDataset(value){try{normalizeDataset(value);return true}catch(_error){return false}}
function copy(issue,freshness){return Object.freeze(Object.assign({},issue,{freshness:freshness}))}
function compare(a,b){var severity={CRITICAL:0,HIGH:1,NOTICE:2},status={CONFIRMED:0,INVESTIGATING:1,MONITORING:2,RESOLVED:3};return severity[a.severity]-severity[b.severity]||status[a.status]-status[b.status]||Date.parse(b.lastVerifiedAt)-Date.parse(a.lastVerifiedAt)||a.id.localeCompare(b.id)}
function viewForGame(dataset,gameId,now){if(!GAME_IDS.includes(gameId)||!instant(now))fail();var data=normalizeDataset(dataset);if(Date.parse(data.reviewedAt)>Date.parse(now)+5*60*1000)fail();var active=[],monitoring=[],stale=[],resolved=[];data.issues.filter(function(x){return x.gameId===gameId}).forEach(function(issue){if(issue.status==='RESOLVED'){resolved.push(copy(issue,'RESOLVED'));return}var current=Date.parse(now)<=Date.parse(issue.reviewBy),item=copy(issue,current?'CURRENT':'STALE');if(!current)stale.push(item);else if(issue.status==='MONITORING')monitoring.push(item);else active.push(item)});[active,monitoring,stale,resolved].forEach(function(list){list.sort(compare)});var official=active.filter(function(x){return x.authority==='OFFICIAL'}),high=official.filter(function(x){return x.kind!=='EVENT_CHANGE'&&(x.severity==='HIGH'||x.severity==='CRITICAL')}),incidents=active.filter(function(x){return x.kind!=='EVENT_CHANGE'});return Object.freeze({gameId:gameId,activeCount:incidents.length+monitoring.length,officialActiveCount:official.length,highSeverityIncidentCount:high.length,active:Object.freeze(active),monitoring:Object.freeze(monitoring),stale:Object.freeze(stale),resolved:Object.freeze(resolved)})}
return Object.freeze({SCHEMA_VERSION:2,GAME_IDS:GAME_IDS,EXACT_SOURCE_URLS:EXACT_URLS,validateDataset:validateDataset,normalizeDataset:normalizeDataset,viewForGame:viewForGame});
});
