(function(root,factory){'use strict';var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OperationsCore=api}(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
var TYPES=['builder','lab','hero','pet','equipment','quest','event','ranked','building','armory','landing-craft','chest','request','war','production','crop','boat','custom'],TYPE_LABELS={builder:'건설',lab:'연구소',hero:'영웅',pet:'펫',equipment:'장비',quest:'퀘스트',event:'이벤트',ranked:'랭크전',building:'건설',armory:'무기고','landing-craft':'상륙정',chest:'상자',request:'카드 요청',war:'클랜전',production:'생산',crop:'작물',boat:'배',custom:'기타'},CLAN_GAMES_STEPS=[150,250,300,400,800],DAY=86400000,MAX_TARGET=10000,SEOUL_DATE=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'});
function ownKeysOnly(value,keys){if(!value||Object.prototype.toString.call(value)!=='[object Object]')return false;var actual=Object.keys(value);return actual.length===keys.length&&actual.every(function(k){return keys.indexOf(k)>=0})}
function plain(value,max){if(typeof value!=='string')return null;var s=value.trim();if(!s||s.length>max||/[<>\u0000-\u001f\u007f]/.test(s))return null;return s}
function integer(value,min,max){if(typeof value!=='number'||!Number.isFinite(value))return null;var n=Math.round(value);return Math.max(min,Math.min(max,n))}
function normalizeRoutine(value){if(!ownKeysOnly(value,['id','label','target','progress']))return null;var label=plain(value.label,40),id=plain(value.id,48),target=integer(value.target,1,MAX_TARGET);if(!label||!id||!/^[A-Za-z0-9_-]+$/.test(id)||target===null)return null;var progress=integer(value.progress,0,target);return progress===null?null:{id:id,label:label,target:target,progress:progress}}
function validNow(now){return now&&typeof now.getTime==='function'&&!Number.isNaN(now.getTime())?new Date(now.getTime()):new Date()}
function normalizeTimer(value,now){if(!ownKeysOnly(value,['id','label','type','endAt']))return null;var id=plain(value.id,48),label=plain(value.label,40),endType=typeof value.endAt;if(!id||!/^[A-Za-z0-9_-]+$/.test(id)||!label||TYPES.indexOf(value.type)<0||(endType!=='string'&&endType!=='number')||(endType==='number'&&!Number.isFinite(value.endAt)))return null;var end=new Date(value.endAt),base=validNow(now);if(Number.isNaN(end.getTime())||end.getTime()<=0||end.getTime()-base.getTime()>366*DAY)return null;return{id:id,label:label,type:value.type,endAt:end.toISOString()}}
function timerTypeLabel(type){return TYPE_LABELS[type]||TYPE_LABELS.custom}
function defaults(now){return{schemaVersion:2,routineDay:dayIso(validNow(now)),timerAlerts:false,routines:[{id:'clan-war',label:'클랜전 공격',target:2,progress:0},{id:'cwl-daily',label:'CWL 일일 공격',target:1,progress:0},{id:'raid-weekend',label:'주말 습격 공격',target:6,progress:0},{id:'clan-games',label:'클랜 게임 점수',target:10000,progress:0}],timers:[],favorites:[]}}
function validDatePart(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;var d=new Date(value+'T00:00:00Z');return!Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===value}
function normalizeState(value,now){var schema=value&&value.schemaVersion,legacy=schema===1,keys=legacy?['schemaVersion','timerAlerts','routines','timers','favorites']:['schemaVersion','routineDay','timerAlerts','routines','timers','favorites'];if((schema!==1&&schema!==2)||!ownKeysOnly(value,keys)||(!legacy&&(typeof value.routineDay!=='string'||!validDatePart(value.routineDay)))||typeof value.timerAlerts!=='boolean'||!Array.isArray(value.routines)||!Array.isArray(value.timers)||!Array.isArray(value.favorites)||value.routines.length>6||value.timers.length>8||value.favorites.length>64)return null;var routines=value.routines.map(normalizeRoutine),timers=value.timers.map(function(t){return normalizeTimer(t,now)}),favorites=[],routineIds=[],timerIds=[];if(routines.some(function(r){return!r||routineIds.indexOf(r.id)>=0?true:(routineIds.push(r.id),false)})||timers.some(function(t){return!t||timerIds.indexOf(t.id)>=0?true:(timerIds.push(t.id),false)}))return null;for(var i=0;i<value.favorites.length;i++){var x=plain(value.favorites[i],240),parts=x&&x.split('|');if(!x||parts.length!==3||!parts[0]||!validDatePart(parts[1])||!validDatePart(parts[2])||parts[1]>parts[2]||favorites.indexOf(x)>=0)return null;favorites.push(x)}return{schemaVersion:2,routineDay:legacy?dayIso(validNow(now)):value.routineDay,timerAlerts:value.timerAlerts,routines:migrateBuiltInRoutines(routines),timers:timers,favorites:favorites}}
function migrateBuiltInRoutines(routines){return routines.map(function(r){return r.id==='clan-games'&&r.target===4000?{id:r.id,label:r.label,target:10000,progress:r.progress}:r})}
function canonical(value){return String(value==null?'':value).trim().replace(/\s+/g,' ').toLocaleLowerCase('ko-KR')}
function keyPart(value){return canonical(value).replace(/%/g,'%25').replace(/\|/g,'%7C')}
function eventKey(e){return keyPart(e&&e.title)+'|'+keyPart(e&&e.startDate)+'|'+keyPart(e&&e.endDate)}
function toggleFavorite(keys,event){var out=Array.isArray(keys)?keys.slice(0,64):[],key=eventKey(event),at=out.indexOf(key);if(at>=0)out.splice(at,1);else if(key!=='||'&&out.length<64)out.push(key);return out}
function dayIso(date){var parts=SEOUL_DATE.formatToParts(date),values={};parts.forEach(function(p){if(p.type!=='literal')values[p.type]=p.value});return values.year+'-'+values.month+'-'+values.day}
function monthPartsAt(date){var parts=dayIso(date).split('-').map(Number);return{year:parts[0],month:parts[1],day:parts[2]}}
function shiftDay(value,days){var date=new Date(value+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function millisecondsUntilNextDay(now){var current=validNow(now),next=Date.parse(shiftDay(dayIso(current),1)+'T00:00:00+09:00');return Math.max(1000,next-current.getTime()+250)}
function eventsOverlappingToday(events,now){var today=dayIso(validNow(now));return(Array.isArray(events)?events:[]).filter(function(e){return typeof e.startDate==='string'&&typeof e.endDate==='string'&&e.startDate<=today&&e.endDate>=today})}
function rolloverDailyState(value,now){var state=normalizeState(value,now),today=dayIso(validNow(now));if(!state)return null;if(state.routineDay!==today){state.routineDay=today;state.routines=state.routines.map(function(r){return{id:r.id,label:r.label,target:r.target,progress:0}})}return state}
function dailyRoutineSummary(routines){var rows=Array.isArray(routines)?routines:[],pending=[],done=[];rows.forEach(function(r){(r.progress>=r.target?done:pending).push(r)});return{total:rows.length,completed:done.length,percent:rows.length?Math.round(done.length*100/rows.length):0,pending:pending,done:done}}
function verifiedNextSevenDays(events,now,verified){var today=dayIso(validNow(now)),last=shiftDay(today,6),accept=typeof verified==='function'?verified:function(e){return e&&e.official===true&&e.status==='OFFICIAL'};return(Array.isArray(events)?events:[]).filter(function(e){return e&&accept(e)===true&&typeof e.startDate==='string'&&typeof e.endDate==='string'&&validDatePart(e.startDate)&&validDatePart(e.endDate)&&e.startDate<=e.endDate&&e.startDate<=last&&e.endDate>=today}).slice().sort(function(a,b){return a.endDate.localeCompare(b.endDate)||a.startDate.localeCompare(b.startDate)||String(a.id||'').localeCompare(String(b.id||''))})}
function hasKnownEnd(event){return!!event&&!['START_DATE_ONLY','START_INSTANT_ONLY','START_ONLY'].includes(event.datePrecision)}
function eventCountdown(event,now){var today=new Date(dayIso(validNow(now))+'T00:00:00Z'),start=new Date(event.startDate+'T00:00:00Z'),end=new Date(event.endDate+'T00:00:00Z'),until=Math.round((start-today)/DAY);if(!hasKnownEnd(event)){if(until===0)return{days:0,label:'오늘 시작'};return{days:until,label:until>0?'D-'+until+' 시작':'시작일 경과'}}if(today>=start&&today<=end)return{days:0,label:end.getTime()===today.getTime()?'오늘 종료':'진행 중 · '+Math.round((end-today)/DAY)+'일 남음'};if(until===0)return{days:0,label:'오늘 시작'};return{days:until,label:until>0?'D-'+until:'종료'}}
function incrementRoutine(value,delta){var r=normalizeRoutine(value),amount=integer(delta,-MAX_TARGET,MAX_TARGET);if(!r||amount===null)return null;r.progress=integer(r.progress+amount,0,r.target);return r}
function setRoutineProgress(value,progress){var r=normalizeRoutine(value);if(!r||typeof progress!=='number'||!Number.isFinite(progress)||!Number.isInteger(progress))return null;r.progress=Math.max(0,Math.min(r.target,progress));return r}
function restoreRoutine(value,progress){var r=normalizeRoutine(value);if(!r)return null;var fallback=Math.max(0,r.progress-1),requested=progress===undefined?fallback:progress,next=integer(requested,0,fallback);if(next===null)return null;r.progress=next;return r}
function resetRoutine(value){return incrementRoutine(value,-MAX_TARGET)}
function timerStatus(timer,now){var end=new Date(timer.endAt),ms=end-validNow(now);if(ms<=0)return{completed:true,label:'완료'};var minutes=Math.ceil(ms/60000);if(minutes<60)return{completed:false,label:minutes+'분 남음'};if(minutes<1440)return{completed:false,label:Math.ceil(minutes/60)+'시간 남음'};var days=Math.floor(minutes/1440),hours=Math.ceil((minutes-days*1440)/60),label=days+'일'+(hours?' '+hours+'시간':'')+' 남음';return{completed:false,label:label}}
function sortTimers(timers,now){return(Array.isArray(timers)?timers:[]).slice().sort(function(a,b){var ac=timerStatus(a,now).completed,bc=timerStatus(b,now).completed;if(ac!==bc)return ac?1:-1;return new Date(a.endAt)-new Date(b.endAt)||String(a.id).localeCompare(String(b.id))})}
return{SCHEMA_VERSION:2,MAX_ROUTINES:6,MAX_TIMERS:8,MAX_FAVORITES:64,TIMER_TYPES:TYPES.slice(),CLAN_GAMES_STEPS:CLAN_GAMES_STEPS.slice(),defaults:defaults,normalizeState:normalizeState,normalizeRoutine:normalizeRoutine,normalizeTimer:normalizeTimer,timerTypeLabel:timerTypeLabel,eventKey:eventKey,toggleFavorite:toggleFavorite,dayIso:dayIso,monthPartsAt:monthPartsAt,millisecondsUntilNextDay:millisecondsUntilNextDay,eventsOverlappingToday:eventsOverlappingToday,verifiedNextSevenDays:verifiedNextSevenDays,hasKnownEnd:hasKnownEnd,eventCountdown:eventCountdown,incrementRoutine:incrementRoutine,setRoutineProgress:setRoutineProgress,restoreRoutine:restoreRoutine,resetRoutine:resetRoutine,rolloverDailyState:rolloverDailyState,dailyRoutineSummary:dailyRoutineSummary,timerStatus:timerStatus,sortTimers:sortTimers};
}));
