(function(){
'use strict';
var core=window.SpendCore;
var state={schemaVersion:1,entries:[]},catalog=null,selectedGame='clash-of-clans',seq=0,idSeq=0,loadToken=null,inFlight=null,dirty=false,undo=null;
var nativeBridge=!!(window.AndroidBridge&&typeof window.AndroidBridge.getSpendState==='function'&&typeof window.AndroidBridge.saveSpendState==='function');
var loaded=!nativeBridge;
function $(id){return document.getElementById(id)}
function node(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function money(n){return n.toLocaleString('ko-KR')+'원'}
function gameName(id){return({'clash-of-clans':'클래시 오브 클랜','brawl-stars':'브롤스타즈','boom-beach':'붐비치','clash-royale':'클래시 로얄','hay-day':'헤이데이'})[id]||id}
function newId(){var id;do{id='purchase-'+Date.now()+'-'+(++idSeq)+'-'+Math.floor(Math.random()*1000000)}while(state.entries.some(function(e){return e.id===id}));return id}
function status(text,bad){$('spendStatus').textContent=text;$('spendStatus').classList.toggle('spend-error',!!bad)}
function nextToken(){return'spend-'+(++seq)}
function browserStatus(message){status((message?message+' · ':'')+'브라우저 미리보기 · 저장되지 않음',false)}
function sendCurrent(){var raw=JSON.stringify(state),token=nextToken();inFlight={token:token,raw:raw};dirty=false;window.AndroidBridge.saveSpendState(raw,token)}
function persist(){if(!nativeBridge){browserStatus();return}if(inFlight){dirty=true;return}sendCurrent()}
function commit(next,message,action){if(!loaded){status('저장 기록을 불러오는 중입니다. 잠시 후 다시 시도해 주세요.',true);return false}state=next;undo=action;persist();render();if(nativeBridge)status(message);else browserStatus(message);return true}
function add(data){try{return commit(core.addEntry(state,data,today()),data.label+' 기록을 추가했습니다.',{type:'add',id:data.id})}catch(_){status('입력값을 확인해 주세요. 기록은 최대 500개이며 저장 용량 제한이 있습니다.',true);return false}}
function makeEntry(gameId,item,amount,origin,note,date){return{id:newId(),gameId:gameId,catalogId:origin==='catalog'?item.id:null,label:String(item.label||'').trim(),category:item.category||'custom',amountKrw:Number(amount),purchasedAt:date||today(),note:String(note||'').trim(),origin:origin}}
function addPriceButton(card,item){var b=node('button','',money(item.amountKrw)+' 오늘 기록');b.type='button';b.disabled=!loaded;b.setAttribute('aria-label',item.label+' '+money(item.amountKrw)+' 오늘 기록');b.onclick=function(){add(makeEntry(selectedGame,item,item.amountKrw,'catalog'))};card.appendChild(b)}
function renderCatalog(){
 var root=$('spendCatalog');root.textContent='';var game=catalog&&catalog.games.find(function(g){return g.gameId===selectedGame});$('spendCatalogTitle').textContent=gameName(selectedGame)+' 빠른 기록';
 if(!game){root.appendChild(node('p','spend-empty','이 게임에는 빠른 가격 목록이 없습니다. 아래 직접 기록을 이용하세요.'));return}
 var groups=[];game.items.forEach(function(item){var group=groups.find(function(x){return x.label===item.label});if(group)group.items.push(item);else groups.push({label:item.label,items:[item]})});
 groups.forEach(function(group){var card=node('article','spend-item');card.setAttribute('aria-label',group.label+' 가격 선택');var head=node('div','spend-card-head');head.appendChild(node('strong','',group.label));card.appendChild(head);var names=group.items.map(function(x){return x.publicName}).filter(Boolean);if(names.length)card.appendChild(node('p','', '공개 목록 이름: '+Array.from(new Set(names)).join(' / ')));if(group.items.length>1)card.appendChild(node('p','spend-price-note','공개 목록에 두 가격이 모두 표시됩니다. 고유한 현재 가격이라는 뜻이 아닙니다.'));var buttons=node('div','spend-price-options');buttons.setAttribute('role','group');buttons.setAttribute('aria-label',group.label+' 가격');group.items.forEach(function(item){if(item.variable){var row=node('div','spend-variable'),input=node('input');input.type='number';input.min='1';input.max='100000000';input.step='1';input.inputMode='numeric';input.disabled=!loaded;input.setAttribute('aria-label',item.label+' 원화 금액');var b=node('button','','추가');b.type='button';b.disabled=!loaded;b.onclick=function(){add(makeEntry(selectedGame,item,input.value,'catalog'))};row.append(input,b);buttons.appendChild(row)}else addPriceButton(buttons,item)});card.appendChild(buttons);root.appendChild(card)})
}
function renderSources(){var root=$('spendSources');Array.prototype.forEach.call(root.children||[],function(button){var visible=button.dataset&&button.dataset.game===selectedGame;button.hidden=!visible;button.disabled=visible&&!nativeBridge;if(visible&&!nativeBridge)button.setAttribute('aria-label',button.textContent+' (브라우저 미리보기에서는 열 수 없음)')})}
function render(){var totals=core.totals(state,selectedGame);$('spendGlobalTotal').textContent=money(totals.globalTotalKrw);$('spendGameTotal').textContent=money(totals.gameTotalKrw);$('spendGameTotalLabel').textContent=gameName(selectedGame)+' 합계';$('spendEntryCount').textContent=totals.entryCount.toLocaleString('ko-KR')+'건';renderCatalog();renderSources();var history=$('spendHistory');history.textContent='';state.entries.filter(function(e){return e.gameId===selectedGame}).slice().reverse().forEach(function(e){var row=node('article','spend-history-item'),copy=node('div','spend-history-copy'),del=node('button','','삭제');copy.append(node('strong','',e.label+' · '+money(e.amountKrw)),node('p','',e.purchasedAt+' · '+gameName(e.gameId)+(e.note?' · '+e.note:'')));del.type='button';del.onclick=function(){try{commit(core.removeEntry(state,e.id,today()),e.label+' 기록을 삭제했습니다.',{type:'delete',entry:e})}catch(_){status('삭제하지 못했습니다.',true)}};row.append(copy,del);history.appendChild(row)});if(!history.children.length)history.appendChild(node('p','spend-empty','선택한 게임의 기록이 없습니다.'));var u=$('spendUndo');u.textContent='';if(undo){var b=node('button','','실행 취소');b.type='button';b.onclick=function(){var action=undo;try{var next=action.type==='add'?core.removeEntry(state,action.id,today()):core.addEntry(state,action.entry,today());commit(next,'마지막 변경을 되돌렸습니다.',null)}catch(_){status('이 변경은 더 이상 되돌릴 수 없습니다.',true)}};u.appendChild(b)}}
function loadCatalog(){try{catalog=core.normalizeCatalog(window.PurchaseCatalog);$('spendCheckedAt').textContent='가격 확인일 '+catalog.checkedAt;render()}catch(_){catalog=null;status('신뢰할 수 있는 가격 목록을 불러오지 못했습니다.',true);render()}}
window.renderSpendPanel=function(gameId){selectedGame=gameId;$('spendGame').value=gameId;render()};
window.requestSpendState=function(){if(nativeBridge){loaded=false;loadToken=nextToken();window.AndroidBridge.getSpendState(loadToken)}else{loaded=true;browserStatus();render()}};
window.onSpendStateResult=function(raw){try{var data=JSON.parse(raw);if(!loaded&&data.requestToken===loadToken){state=core.normalizeStoredState(data.state,today());loaded=true;loadToken=null;render();status('이 Android 기기에 저장됩니다.');return}if(!inFlight||data.requestToken!==inFlight.token)return;var completed=inFlight;inFlight=null;if(data.saved!==true){state=core.normalizeStoredState(data.state,today());dirty=false;undo=null;render();status('저장에 실패해 마지막으로 안전하게 저장된 기록으로 되돌렸습니다.',true);return}var changed=dirty&&JSON.stringify(state)!==completed.raw;dirty=false;if(changed)sendCurrent();status(changed?'최신 변경을 저장하는 중입니다.':'이 Android 기기에 저장했습니다.')}catch(_){status('저장 응답을 처리하지 못했습니다.',true)}};
$('spendForm').onsubmit=function(e){e.preventDefault();var item={id:'custom',label:$('spendName').value.trim(),category:$('spendCategory').value};if(add(makeEntry($('spendGame').value,item,$('spendAmount').value,'custom',$('spendNote').value.trim(),$('spendDate').value))){this.reset();$('spendGame').value=selectedGame;$('spendDate').value=today()}};
$('spendDate').max=today();$('spendDate').value=today();$('spendGame').value=selectedGame;
$('spendSources').onclick=function(e){var target=e.target,url=target&&target.dataset?target.dataset.url:null;if(url&&nativeBridge&&!target.disabled)window.AndroidBridge.openSpendSource(url)};
if(window.__SPEND_TEST_MODE__===true)window.__spendTest={add:add,state:function(){return JSON.parse(JSON.stringify(state))}};
loadCatalog();window.requestSpendState();
})();
