(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.SpendCore=factory()})(typeof self!=='undefined'?self:this,function(){
'use strict';
var GAMES=['clash-of-clans','brawl-stars','boom-beach','clash-royale','hay-day'],CATEGORIES=['pass','currency','cosmetic','service','offer','custom'],ORIGINS=['catalog','custom'],KEYS=['id','gameId','catalogId','label','category','amountKrw','purchasedAt','note','origin'],MAX_ENTRIES=500,MAX_PAYLOAD_BYTES=96*1024;
var SOURCES=[['ios-public-listing','clash-of-clans','https://apps.apple.com/kr/app/clash-of-clans/id529479190'],['ios-public-listing','brawl-stars','https://apps.apple.com/kr/app/brawl-stars/id1229016807'],['ios-public-listing','boom-beach','https://apps.apple.com/kr/app/boom-beach/id672150402'],['official-type-existence','clash-of-clans','https://store.supercell.com/ko/clashofclans'],['official-type-existence','brawl-stars','https://store.supercell.com/ko/brawlstars'],['official-type-existence','boom-beach','https://store.supercell.com/ko/boombeach']];
var INVENTORY={'clash-of-clans':[['coc-gold-pass-7500','골드 패스','pass',7500,'Gold Pass'],['coc-gold-pass-9900','골드 패스','pass',9900,'Gold Pass'],['coc-gems-handful','보석 한 줌','currency',1500],['coc-gems-pile','보석 더미','currency',7500],['coc-gems-bag','보석 가방','currency',15000],['coc-gems-sack','보석 자루','currency',30000],['coc-gems-vault','보석 금고','currency',149000],['coc-hero-skin','영웅 스킨','cosmetic','variable'],['coc-scenery','마을 배경','cosmetic','variable'],['coc-event-offer','이벤트 패스/특가','offer','variable']], 'brawl-stars':[['brawl-gems-30','보석 30개','currency',3000],['brawl-gems-80','보석 80개','currency',7500],['brawl-gems-170','보석 170개','currency',15000],['brawl-gems-360','보석 360개','currency',30000],['brawl-pass','브롤 패스','pass',9900,'Season Pass'],['brawl-pass-plus-15000','브롤 패스 플러스','pass',15000,'Season Pass Plus'],['brawl-pass-plus-20000','브롤 패스 플러스','pass',20000,'브롤 패스 플러스'],['brawl-skin','스킨','cosmetic','variable'],['brawl-offer','특가 상품','offer','variable']], 'boom-beach':[['boom-diamonds-handful','다이아몬드 한 움큼','currency',1500],['boom-diamonds-bunch','다이아몬드 한 줌','currency',7500],['boom-diamonds-pocket','다이아몬드 주머니','currency',15000],['boom-diamonds-bag','다이아몬드 가방','currency',30000],['boom-diamonds-box','다이아몬드 상자','currency',79000],['boom-diamonds-chest','다이아몬드 궤짝','currency',149000],['boom-extra-builder','추가 장인','service',4400],['boom-instant-training','즉시 훈련','service',15000],['boom-pass','붐 패스','pass','variable'],['boom-offer','특가 상품','offer','variable']]};
var CATALOG={};Object.keys(INVENTORY).forEach(function(gameId){INVENTORY[gameId].forEach(function(item){CATALOG[item[0]]={gameId:gameId,label:item[1],category:item[2],amount:item[3]}})});
function fail(){throw new TypeError('invalid spend data')}
function exact(o,keys){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).length!==keys.length||!keys.every(function(k){return Object.prototype.hasOwnProperty.call(o,k)}))fail()}
function date(value,today,allowFuture){if(typeof value!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value))fail();var p=value.split('-').map(Number),d=new Date(Date.UTC(p[0],p[1]-1,p[2]));if(d.getUTCFullYear()!==p[0]||d.getUTCMonth()!==p[1]-1||d.getUTCDate()!==p[2]||(!allowFuture&&value>today))fail();return value}
function text(value,max,empty){if(typeof value!=='string'||value.length>max||(!empty&&!value.length)||value!==value.trim()||/[\u0000-\u001f\u007f-\u009f<>]/.test(value))fail();return value}
function normalizeEntry(e,today,allowFuture){exact(e,KEYS);var id=text(e.id,48,false),gameId=e.gameId,catalogId=e.catalogId,label=text(e.label,60,false),category=e.category,amount=e.amountKrw,purchasedAt=date(e.purchasedAt,today,allowFuture===true),note=text(e.note,80,true),origin=e.origin;if(!/^[A-Za-z0-9_-]+$/.test(id)||GAMES.indexOf(gameId)<0||(catalogId!==null&&(typeof catalogId!=='string'||!/^[A-Za-z0-9_-]+$/.test(catalogId)||catalogId.length>64))||CATEGORIES.indexOf(category)<0||!Number.isInteger(amount)||amount<1||amount>100000000||ORIGINS.indexOf(origin)<0||(origin==='catalog'&&catalogId===null)||(origin==='custom'&&catalogId!==null))fail();if(origin==='catalog'){var expected=CATALOG[catalogId];if(!expected||expected.gameId!==gameId||expected.label!==label||expected.category!==category||(expected.amount!=='variable'&&expected.amount!==amount))fail()}return{id:id,gameId:gameId,catalogId:catalogId,label:label,category:category,amountKrw:amount,purchasedAt:purchasedAt,note:note,origin:origin}}
function normalizeState(s,today,allowFuture){exact(s,['schemaVersion','entries']);if(s.schemaVersion!==1||!Array.isArray(s.entries)||s.entries.length>MAX_ENTRIES)fail();var seen={},entries=s.entries.map(function(e){var n=normalizeEntry(e,today,allowFuture===true);if(seen[n.id])fail();seen[n.id]=true;return n}),out={schemaVersion:1,entries:entries};if(typeof TextEncoder!=='undefined'&&new TextEncoder().encode(JSON.stringify(out)).length>MAX_PAYLOAD_BYTES)fail();return out}
function normalizeStoredState(s,today){return normalizeState(s,today,true)}
function normalizeCatalog(c){exact(c,['schemaVersion','checkedAt','sources','games']);if(c.schemaVersion!==1||c.checkedAt!=='2026-08-17'||!Array.isArray(c.sources)||c.sources.length!==SOURCES.length||!Array.isArray(c.games)||c.games.length!==3)fail();c.sources.forEach(function(s,i){exact(s,['kind','gameId','url']);if(s.kind!==SOURCES[i][0]||s.gameId!==SOURCES[i][1]||s.url!==SOURCES[i][2])fail()});var ids={};c.games.forEach(function(g,gi){exact(g,['gameId','items']);var gameId=['clash-of-clans','brawl-stars','boom-beach'][gi],expected=INVENTORY[gameId];if(g.gameId!==gameId||!Array.isArray(g.items)||g.items.length!==expected.length)fail();g.items.forEach(function(item,i){var x=expected[i],variable=x[3]==='variable',keys=['id','label','category',variable?'variable':'amountKrw'];if(x.length===5)keys.push('publicName');exact(item,keys);if(ids[item.id]||item.id!==x[0]||item.label!==x[1]||item.category!==x[2]||CATEGORIES.indexOf(item.category)<0)fail();ids[item.id]=true;if(variable){if(item.variable!==true)fail()}else if(!Number.isInteger(item.amountKrw)||item.amountKrw!==x[3]||item.amountKrw<1||item.amountKrw>100000000)fail();if(x.length===5&&item.publicName!==x[4])fail()})});return JSON.parse(JSON.stringify(c))}
function addEntry(s,e,today){var n=normalizeState(s,today);if(n.entries.length>=MAX_ENTRIES)fail();var item=normalizeEntry(e,today);if(n.entries.some(function(x){return x.id===item.id}))fail();return normalizeState({schemaVersion:1,entries:n.entries.concat([item])},today)}
function removeEntry(s,id,today){var n=normalizeState(s,today),next=n.entries.filter(function(x){return x.id!==id});if(next.length===n.entries.length)fail();return{schemaVersion:1,entries:next}}
function totals(s,gameId){var n=normalizeState(s,'9999-12-31');if(GAMES.indexOf(gameId)<0)fail();return{globalTotalKrw:n.entries.reduce(function(a,x){return a+x.amountKrw},0),gameTotalKrw:n.entries.filter(function(x){return x.gameId===gameId}).reduce(function(a,x){return a+x.amountKrw},0),entryCount:n.entries.length}}
return{SCHEMA_VERSION:1,MAX_ENTRIES:MAX_ENTRIES,MAX_PAYLOAD_BYTES:MAX_PAYLOAD_BYTES,GAME_IDS:GAMES,CATEGORIES:CATEGORIES,normalizeEntry:normalizeEntry,normalizeState:normalizeState,normalizeStoredState:normalizeStoredState,normalizeCatalog:normalizeCatalog,addEntry:addEntry,removeEntry:removeEntry,totals:totals};
});
