(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.StrategyData=api;}(typeof self!=='undefined'?self:this,function(){'use strict';var LAYOUTS=[
  {
    "th": 4,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_4/war_38.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH4%3AWB%3AAAAAMAAAAAJ1FQartgNvSYHg0bycl9a-",
    "imageUrl": "https://clashofclans-layouts.com/pics/th4_plans/war/thumb/th4_war_38.jpg?u=1766683091",
    "title": "Best Anti 3 Stars War Base TH4 with Link, Anti Everything 2026 - Town Hall Level 4 CWL Base Copy - (#38)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 4,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_4/war_37.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH4%3AWB%3AAAAAMAAAAAJ1FG_-_UMX44d_lppNovMt",
    "imageUrl": "https://clashofclans-layouts.com/pics/th4_plans/war/thumb/th4_war_37.jpg?u=1766681591",
    "title": "Best Anti 3 Stars War Base TH4 with Link, Anti Everything 2026 - Town Hall Level 4 CWL Base Copy - (#37)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 4,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_4/farm_123.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH4%3AHV%3AAAAAMAAAAAJ1FElpllTfBBMmryMJCJMH",
    "imageUrl": "https://clashofclans-layouts.com/pics/th4_plans/farm/thumb/th4_farm_123.jpg?u=1766681229",
    "title": "Farming Base TH4 with Link, Hybrid - Clash of Clans 2026 - Town Hall Level 4 Base Copy - (#123)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 5,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_5/war_55.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH5%3AWB%3AAAAAAgAAAAMmgJnOzP0h7QKAETmLBVUU",
    "imageUrl": "https://clashofclans-layouts.com/pics/th5_plans/war/thumb/th5_war_55.jpg",
    "title": "Best Anti 3 Stars War Base TH5 with Link 2026 - Town Hall Level 5 CWL Base Copy - (#55)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 5,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_5/war_54.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH5%3AWB%3AAAAAAgAAAAMbx7ckzhT5_80A-GFyCTPz",
    "imageUrl": "https://clashofclans-layouts.com/pics/th5_plans/war/thumb/th5_war_54.jpg",
    "title": "Best Anti 3 Stars War Base TH5 with Link, Anti Air 2026 - Town Hall Level 5 CWL Base Copy - (#54)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 5,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_5/farm_121.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH5%3AHV%3AAAAAAgAAAAMNYy2CUk2a07u4Sru2x6pj",
    "imageUrl": "https://clashofclans-layouts.com/pics/th5_plans/farm/thumb/th5_farm_121.jpg?u=1766765291",
    "title": "Farming Base TH5 Max Levels with Link, Hybrid - Town Hall Level 5 Base Copy - Clash of Clans 2026 - (#121)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 6,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_6/war_70.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH6%3AWB%3AAAAABQAAAAMDqt3lWwcZIhgk2vv1uMxs",
    "imageUrl": "https://clashofclans-layouts.com/pics/th6_plans/war/thumb/th6_war_70.jpg",
    "title": "Best Anti 3 Stars War Base TH6 with Link, Anti Everything 2026 - Town Hall Level 6 CWL Base Copy - (#70)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 6,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_6/war_69.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH6%3AWB%3AAAAABQAAAAL1X8hQVDDCPOu24JegGjGf",
    "imageUrl": "https://clashofclans-layouts.com/pics/th6_plans/war/thumb/th6_war_69.jpg?u=1766768651",
    "title": "Best Max Levels War Base TH6 with Link, Anti Everything 2026 - Town Hall Level 6 CWL Base Copy - (#69)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 6,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_6/farm_171.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH6%3AHV%3AAAAABQAAAALwXKC7JZRP0vvv00jMVgS5",
    "imageUrl": "https://clashofclans-layouts.com/pics/th6_plans/farm/thumb/th6_farm_171.jpg?u=1763571128",
    "title": "Farming Base TH6 with Link, Anti 3 Stars - Clash of Clans 2026 - Town Hall Level 6 Base Copy - (#171)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 7,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_7/war_173.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH7%3AWB%3AAAAAAQAAAAMYWY0g63tj0jW1-Taav6Z8",
    "imageUrl": "https://clashofclans-layouts.com/pics/th7_plans/war/thumb/th7_war_173.jpg",
    "title": "Best Anti 3 Stars War Base TH7 with Link 2026 - Town Hall Level 7 CWL Base Copy - (#173)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 7,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_7/war_172.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH7%3AWB%3AAAAAAQAAAAMIJPcxdVIkGKvXnLv_ubiJ",
    "imageUrl": "https://clashofclans-layouts.com/pics/th7_plans/war/thumb/th7_war_172.jpg?u=1766837528",
    "title": "Best War Base TH7 with Link 2026 - Town Hall Level 7 CWL Base Copy - (#172)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 7,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_7/farm_284.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH7%3AHV%3AAAAAAQAAAAMbEBVeQEWSMKg6MpN8_9uK",
    "imageUrl": "https://clashofclans-layouts.com/pics/th7_plans/farm/thumb/th7_farm_284.jpg",
    "title": "Farming Base TH7 with Link, Anti 2 Stars, Hybrid - Clash of Clans 2026 - Town Hall Level 7 Base Copy - (#284)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 8,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_8/war_151.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH8%3AWB%3AAAAACAAAAALduvImJ9ZX_vnNJLIDwQAS",
    "imageUrl": "https://clashofclans-layouts.com/pics/th8_plans/war/thumb/th8_war_151.jpg?u=1766853309",
    "title": "Best Anti 3 Stars War Base TH8 with Link 2026 - Town Hall Level 8 CWL Base Copy - (#151)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 8,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_8/war_150.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH8%3AWB%3AAAAACAAAAALdu0KADWj4Vy0THdUeEfZo",
    "imageUrl": "https://clashofclans-layouts.com/pics/th8_plans/war/thumb/th8_war_150.jpg?u=1766853848",
    "title": "Best War Base TH8 with Link, Anti Everything, Hybrid 2026 - Town Hall Level 8 CWL Base Copy - (#150)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 8,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_8/war_149.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH8%3AWB%3AAAAACAAAAALdu10BwlpqUf01IxMOURNx",
    "imageUrl": "https://clashofclans-layouts.com/pics/th8_plans/war/thumb/th8_war_149.jpg?u=1766854088",
    "title": "Best Anti 2 Stars War Base TH8 with Link, Anti Everything 2026 - Town Hall Level 8 CWL Base Copy - (#149)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 9,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_9/war_130.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH9%3AWB%3AAAAAKwAAAAKVRQB9aaoZ5QPTfI-4_DeK",
    "imageUrl": "https://clashofclans-layouts.com/pics/th9_plans/war/thumb/th9_war_130.jpg",
    "title": "Best Anti 3 Stars War Base TH9 with Link, Anti Air / Dragon 2026 - Town Hall Level 9 CWL Base Copy - (#130)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 9,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_9/war_129.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH9%3AWB%3AAAAAKwAAAAKNVmHcHTUbLvrMUolwr6lo",
    "imageUrl": "https://clashofclans-layouts.com/pics/th9_plans/war/thumb/th9_war_129.jpg?u=1774180080",
    "title": "Best Anti 2 Stars War Base TH9 with Link, Anti Everything 2026 - Town Hall Level 9 CWL Base Copy - (#129)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 9,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_9/farm_273.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH9%3AHV%3AAAAAKwAAAAKVRNO-B0-qqia8TXTDolec",
    "imageUrl": "https://clashofclans-layouts.com/pics/th9_plans/farm/thumb/th9_farm_273.jpg",
    "title": "Farming Base TH9 with Link, Anti 3 Stars - Clash of Clans 2026 - Town Hall Level 9 Base Copy - (#273)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 10,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_10/war_205.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH10%3AHV%3AAAAASAAAAAIfs7NHbxuy6xmcV-hgPZPt",
    "imageUrl": "https://clashofclans-layouts.com/pics/th10_plans/war/thumb/th10_war_205.jpg",
    "title": "Best Anti 3 Stars War Base TH10 with Link 2026 - Town Hall Level 10 CWL Base Copy - (#205)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 10,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_10/war_204.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH10%3AWB%3AAAAASAAAAAIeF6Ny5wznmDDxZiUPi51D",
    "imageUrl": "https://clashofclans-layouts.com/pics/th10_plans/war/thumb/th10_war_204.jpg",
    "title": "Best War Base TH10 with Link 2026 - Town Hall Level 10 CWL Base Copy - (#204)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 10,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_10/farm_230.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH10%3AHV%3AAAAASAAAAAIc5qfIDd7y-7wlObm7KS1I",
    "imageUrl": "https://clashofclans-layouts.com/pics/th10_plans/farm/thumb/th10_farm_230.jpg",
    "title": "Farming Base TH10 with Link, Anti 3 Stars - Clash of Clans 2026 - Town Hall Level 10 Base Copy - (#230)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 11,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_11/war_205.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH11%3AWB%3AAAAAFwAAAAK-bfEfGvcyQPsKF1x14NyC",
    "imageUrl": "https://clashofclans-layouts.com/pics/th11_plans/war/thumb/th11_war_205.jpg",
    "title": "Best Anti 3 Stars War Base TH11 with Link 2026 - Town Hall Level 11 CWL Base Copy - (#205)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 11,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_11/war_204.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH11%3AWB%3AAAAAFwAAAAK2UHunVDN0qaQsqROCejX4",
    "imageUrl": "https://clashofclans-layouts.com/pics/th11_plans/war/thumb/th11_war_204.jpg",
    "title": "Best Anti 3 Stars War Base TH11 with Link 2026 - Town Hall Level 11 CWL Base Copy - (#204)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 11,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_11/farm_66.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH11%3AHV%3AAAAAFwAAAAK5dBV6iqxaWiR0S2_i-0iZ",
    "imageUrl": "https://clashofclans-layouts.com/pics/th11_plans/farm/thumb/th11_farm_66.jpg",
    "title": "Farming Base TH11 with Link - Clash of Clans 2026 - Town Hall Level 11 Base Copy - (#66)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 12,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_12/war_207.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH12%3AWB%3AAAAAMQAAAAKMPRyyONMHWLY1VpMzOlud",
    "imageUrl": "https://clashofclans-layouts.com/pics/th12_plans/war/thumb/th12_war_207.jpg",
    "title": "Best Anti 3 Stars War Base TH12 with Link 2026 - Town Hall Level 12 CWL Base Copy - (#207)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 12,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_12/war_206.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH12%3AWB%3AAAAAMQAAAAKLjnybd6oDpPAJZ-bOHz7e",
    "imageUrl": "https://clashofclans-layouts.com/pics/th12_plans/war/thumb/th12_war_206.jpg",
    "title": "Best War Base TH12 with Link, Anti Everything 2026 - Town Hall Level 12 CWL Base Copy - (#206)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 12,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_12/farm_100.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH12%3AHV%3AAAAAMQAAAAKJQ11r4XUvmPCLGwHEu6wm",
    "imageUrl": "https://clashofclans-layouts.com/pics/th12_plans/farm/thumb/th12_farm_100.jpg",
    "title": "Farming Base TH12 with Link, Anti 3 Stars - Clash of Clans 2026 - Town Hall Level 12 Base Copy - (#100)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 13,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_13/war_312.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH13%3AWB%3AAAAADgAAAALf7KAIUVhYMlHXQ3kH8zfb",
    "imageUrl": "https://clashofclans-layouts.com/pics/th13_plans/war/thumb/th13_war_312.jpg",
    "title": "Best Anti 3 Stars War Base TH13 with Link, Anti Everything 2026 - Town Hall Level 13 CWL Base Copy - (#312)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 13,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_13/war_311.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH13%3AWB%3AAAAADgAAAALfsOib-XshMm1pwfR0QbNq",
    "imageUrl": "https://clashofclans-layouts.com/pics/th13_plans/war/thumb/th13_war_311.jpg",
    "title": "Best Max Levels War Base TH13 with Link 2026 - Town Hall Level 13 CWL Base Copy - (#311)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 13,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_13/farm_80.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH13%3AHV%3AAAAADgAAAALZvcgu2dbrvZ42UlxfTmzD",
    "imageUrl": "https://clashofclans-layouts.com/pics/th13_plans/farm/thumb/th13_farm_80.jpg",
    "title": "Farming Base TH13 with Link, Anti 3 Stars, Hybrid - Clash of Clans 2026 - Town Hall Level 13 Base Copy - (#80)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 14,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_14/war_239.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH14%3AWB%3AAAAAQAAAAAJVzSwyPdweHcbDy0u1UcI9",
    "imageUrl": "https://clashofclans-layouts.com/pics/th14_plans/war/thumb/th14_war_239.jpg",
    "title": "Best Anti 3 Stars War Base TH14 with Link 2026 - Town Hall Level 14 CWL Base Copy - (#239)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 14,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_14/war_238.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH14%3AWB%3AAAAAQAAAAAJSJRmxlx9lwlmcL5EKF8Q1",
    "imageUrl": "https://clashofclans-layouts.com/pics/th14_plans/war/thumb/th14_war_238.jpg",
    "title": "Best War Base TH14 with Link 2026 - Town Hall Level 14 CWL Base Copy - (#238)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 14,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_14/war_237.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH14%3AWB%3AAAAAQAAAAAJSIrWIztz569Nk5NkYS58w",
    "imageUrl": "https://clashofclans-layouts.com/pics/th14_plans/war/thumb/th14_war_237.jpg",
    "title": "Best War Base TH14 with Link, Anti Everything 2026 - Town Hall Level 14 CWL Base Copy - (#237)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 15,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_15/war_138.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH15%3AWB%3AAAAARQAAAAJI8indaHHIwHsxO-JDJhza",
    "imageUrl": "https://clashofclans-layouts.com/pics/th15_plans/war/thumb/th15_war_138.jpg",
    "title": "Best Anti 3 Stars War Base TH15 with Link, Anti Everything 2026 - Town Hall Level 15 CWL Base Copy - (#138)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 15,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_15/war_137.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH15%3AWB%3AAAAARQAAAAJEvZYTUQ-VAxF_-IBLf76f",
    "imageUrl": "https://clashofclans-layouts.com/pics/th15_plans/war/thumb/th15_war_137.jpg",
    "title": "Best Max Levels War Base TH15 with Link 2026 - Town Hall Level 15 CWL Base Copy - (#137)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 15,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_15/farm_37.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH15%3AHV%3AAAAARQAAAAJEu1ICN40YI0MkXbPUY13w",
    "imageUrl": "https://clashofclans-layouts.com/pics/th15_plans/farm/thumb/th15_farm_37.jpg",
    "title": "Farming Base TH15 Max Levels with Link, Anti 3 Stars - Town Hall Level 15 Base Copy - Clash of Clans 2026 - (#37)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 16,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_16/war_135.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH16%3AWB%3AAAAAEAAAAALaVr9W60FxjwHX2ZfpE9Uw",
    "imageUrl": "https://clashofclans-layouts.com/pics/th16_plans/war/thumb/th16_war_135.jpg",
    "title": "Best Anti 2 Stars War Base TH16 with Link, Legend League 2026 - Town Hall Level 16 CWL Base Copy - (#135)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 16,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_16/war_134.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH16%3AWB%3AAAAAEAAAAALZOqehZUWTgTPRJgvm4aBP",
    "imageUrl": "https://clashofclans-layouts.com/pics/th16_plans/war/thumb/th16_war_134.jpg",
    "title": "Best Anti 3 Stars War Base TH16 with Link 2026 - Town Hall Level 16 CWL Base Copy - (#134)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 16,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_16/farm_33.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH16%3AHV%3AAAAAEAAAAALWr0Lcl7TgLa4f-wYwhdBR",
    "imageUrl": "https://clashofclans-layouts.com/pics/th16_plans/farm/thumb/th16_farm_33.jpg",
    "title": "Farming Base TH16 with Link, Anti 3 Stars, Anti Air / Electro Dragon - Clash of Clans 2026 - Town Hall Level 16 Base Copy - (#33)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 17,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_17/war_197.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH17%3AWB%3AAAAAWAAAAAHyuDpb3ifEXV0NIOTgP1Ly",
    "imageUrl": "https://clashofclans-layouts.com/pics/th17_plans/war/thumb/th17_war_197.jpg",
    "title": "Best Anti 3 Stars War Base TH17 with Link 2026 - Town Hall Level 17 CWL Base Copy - (#197)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 17,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_17/war_196.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH17%3AWB%3AAAAAWAAAAAHyGjUW3xZX1rq43MkDuzrA",
    "imageUrl": "https://clashofclans-layouts.com/pics/th17_plans/war/thumb/th17_war_196.jpg",
    "title": "Best Anti 3 Stars War Base TH17 with Link 2026 - Town Hall Level 17 CWL Base Copy - (#196)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 17,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_17/war_195.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH17%3AWB%3AAAAAWAAAAAHx0bwOgHWzqNixVuo2ZZxa",
    "imageUrl": "https://clashofclans-layouts.com/pics/th17_plans/war/thumb/th17_war_195.jpg",
    "title": "Best Anti 3 Stars War Base TH17 with Link 2026 - Town Hall Level 17 CWL Base Copy - (#195)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 18,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_18/war_160.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH18%3AWB%3AAAAAVwAAAAHy7C20A_wF81POMsuWgHa2",
    "imageUrl": "https://clashofclans-layouts.com/pics/th18_plans/war/thumb/th18_war_160.jpg",
    "title": "Best Anti 3 Stars War Base TH18 with Link 2026 - Town Hall Level 18 CWL Base Copy - (#160)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 18,
    "kind": "war",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_18/war_159.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH18%3AWB%3AAAAAVwAAAAHyqm2EE8IWKGaUAW4wbLuT",
    "imageUrl": "https://clashofclans-layouts.com/pics/th18_plans/war/thumb/th18_war_159.jpg",
    "title": "Best Anti 3 Stars War Base TH18 with Link 2026 - Town Hall Level 18 CWL Base Copy - (#159)",
    "kindLabel": "배치 유형"
  },
  {
    "th": 18,
    "kind": "farm",
    "sourceName": "Clash of Clans Layouts",
    "sourceUrl": "https://clashofclans-layouts.com/plans/th_18/farm_21.html",
    "copyUrl": "https://link.clashofclans.com/en?action=OpenLayout&id=TH18%3AHV%3AAAAAVwAAAAHxr6DDBnxRnUQ-Bgm83y_c",
    "imageUrl": "https://clashofclans-layouts.com/pics/th18_plans/farm/thumb/th18_farm_21.jpg",
    "title": "Farming Base TH18 with Link - Clash of Clans 2026 - Town Hall Level 18 Base Copy - (#21)",
    "kindLabel": "배치 유형"
  }
];var ARMIES=[
  {
    "th": 4,
    "nameKo": "Judo 쉬운 TH4 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=i1x23-1x5u1x0-19x1-12x5-",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 4,
    "nameKo": "자이언트 · 아처 벽개방",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=VMIZbKuSd0U",
    "creator": "LukaBraxi",
    "publishedDate": "2021-04-05",
    "coreUnits": "자이언트 · 아처 · 벽 파괴병",
    "spells": "번개 주문(보유 시)",
    "siege": "없음",
    "heroes": "없음",
    "note": "자이언트로 방어를 묶고 벽 파괴병 뒤에 아처 투입",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 4,
    "nameKo": "벌룬 집중",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=VMIZbKuSd0U",
    "creator": "LukaBraxi",
    "publishedDate": "2021-04-05",
    "coreUnits": "벌룬 · 아처",
    "spells": "번개 주문(보유 시)",
    "siege": "없음",
    "heroes": "없음",
    "note": "대공포를 먼저 정리하고 벌룬을 한 방향으로 투입",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 5,
    "nameKo": "Judo 쉬운 TH5 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=i3x5u1x0-8x1-11x3-5x4-5x5-9x6-s2x0",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 5,
    "nameKo": "다수 벌룬",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=K1pfqaeBQPM",
    "creator": "The Nightowl",
    "publishedDate": "2021-01-01",
    "coreUnits": "벌룬 · 아처 보조",
    "spells": "번개 주문",
    "siege": "없음",
    "heroes": "없음",
    "note": "영상의 TH5 Top 3 조합명 기준; 수량은 기지·캠프에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 5,
    "nameKo": "자이언트 · 마법사 · 벌룬",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=K1pfqaeBQPM",
    "creator": "The Nightowl",
    "publishedDate": "2021-01-01",
    "coreUnits": "자이언트 · 마법사 · 벌룬 · 아처 보조",
    "spells": "번개 주문",
    "siege": "없음",
    "heroes": "없음",
    "note": "영상의 TH5 Top 3 조합명 기준; 수량은 기지·캠프에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 6,
    "nameKo": "Judo 쉬운 TH6 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=i1x110u5x0-11x1-10x3-5x4-2x5-16x6-s2x1",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 6,
    "nameKo": "다수 벌룬 3별",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=LnUoPlj2UCE",
    "creator": "Jsmith Gaming",
    "publishedDate": "2021-02-11",
    "coreUnits": "벌룬 · 아처 보조",
    "spells": "치유/번개 주문",
    "siege": "없음",
    "heroes": "없음",
    "note": "대공 방어 접근 경로를 먼저 정한 뒤 벌룬을 뭉쳐 투입",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 6,
    "nameKo": "자이언트 · 마법사 · 힐러",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=LnUoPlj2UCE",
    "creator": "Jsmith Gaming",
    "publishedDate": "2021-02-11",
    "coreUnits": "자이언트 · 마법사 · 힐러 · 벽 파괴병",
    "spells": "치유 주문",
    "siege": "없음",
    "heroes": "없음",
    "note": "자이언트 탱킹 뒤 힐러, 마법사로 외곽 정리",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 7,
    "nameKo": "자이언트 · 마법사",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=u23x3-8x4-16x6-5x1s3x1",
    "videoUrl": "https://www.youtube.com/watch?v=cOBM0rrPais",
    "creator": "AngryGoblin",
    "publishedDate": "2024-05-13",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 7,
    "nameKo": "드래곤 · 번개",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=u8x5-8x8s6x0",
    "videoUrl": "https://www.youtube.com/watch?v=cOBM0rrPais",
    "creator": "AngryGoblin",
    "publishedDate": "2024-05-13",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 7,
    "nameKo": "다수 호그",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=u10x6-25x11-3x3-5x10-2x1-4x4s3x1",
    "videoUrl": "https://www.youtube.com/watch?v=cOBM0rrPais",
    "creator": "AngryGoblin",
    "publishedDate": "2024-05-13",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 8,
    "nameKo": "퀸 차지 호그",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=u4x7-16x11-8x6-7x4-3x1-3x5s1x2-2x1-1x9",
    "videoUrl": "https://www.youtube.com/watch?v=9EJZpg-9Zgc",
    "creator": "AngryGoblin",
    "publishedDate": "2024-12-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 8,
    "nameKo": "골렘·페카·발키리",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=u2x1-7x4-8x6-2x9-9x12-1x13s2x1-1x2-1x9",
    "videoUrl": "https://www.youtube.com/watch?v=9EJZpg-9Zgc",
    "creator": "AngryGoblin",
    "publishedDate": "2024-12-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 8,
    "nameKo": "번개 드래곤",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=u9x8-4x5s7x0",
    "videoUrl": "https://www.youtube.com/watch?v=9EJZpg-9Zgc",
    "creator": "AngryGoblin",
    "publishedDate": "2024-12-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 9,
    "nameKo": "번개 마녀",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0e8_1-1e17_2i1x110-2x11d1x10u18x15-1x6s1x10-7x0-1x9",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 9,
    "nameKo": "Judo 쉬운 TH9 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0e1_8-1e3_2i2x1-1x6-3x12d1x9u5x4-3x13-10x15-s1x1-1x2-2x3-1x5",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 9,
    "nameKo": "퀸 차지 라바룬",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=65mZlQlrhOk",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2021-01-24",
    "coreUnits": "힐러 · 라바 하운드 · 벌룬",
    "spells": "분노 · 신속 · 얼음",
    "siege": "지원 시즈 선택",
    "heroes": "아처 퀸 선행",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 10,
    "nameKo": "번개 드래곤",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h1e17_2-6e42_43i7x5-1x62d1x5u10x8-6x5-1x23s6x0-2x10-1x2-1x5",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 10,
    "nameKo": "Judo 쉬운 TH10 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h6e42_43-1e2_17i1x5-1x8-1x62d1x10u12x8-s9x0-2x10",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 10,
    "nameKo": "광부 러시",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=PLUoYoqUKtg",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2021-02-02",
    "coreUnits": "광부 · 베이비 드래곤 보조",
    "spells": "치유 · 얼음",
    "siege": "지원 시즈 선택",
    "heroes": "퀸으로 외곽 정리",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 11,
    "nameKo": "드래곤 + 복제 주문 + 슈퍼 예티",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h1e17_48-2m1e4_24-6e42_43i1x52-1x147d1x2u2x23-8x5-10x8s3x16-2x5",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 11,
    "nameKo": "Judo 쉬운 TH11 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0e11_8-1e39_15-2e4_5i1x110-1x12-1x6-3x0-1x87d1x10u15x15-1x6-2x13-2x28-s8x0-2x10-1x9",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 11,
    "nameKo": "번개 마녀",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=D-b4xmc_wo8",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2021-02-23",
    "coreUnits": "마녀 · 골렘/아이스 골렘",
    "spells": "번개 · 지진",
    "siege": "로그 런처 권장",
    "heroes": "영웅 본대 동행",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 12,
    "nameKo": "파이어볼 슈퍼 마녀",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0e8_1-1e17_20-2e22_24i5x12-1x75d1x5-1x9u5x7-3x66-3x28-1x23-3x12-2x6-1x82-3x5-1x10-1x1s2x2-2x35-1x10-2x5-1x3",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 12,
    "nameKo": "Judo 쉬운 TH12 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0e8_14-1e17_20-2m1e4_24i3x5-1x65-1x91d1x2u14x8-1x52-1x62s1x70-3x5-6x28",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 12,
    "nameKo": "퀸 차지 라바룬",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=DCS4YeCOBKQ",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2021-03-03",
    "coreUnits": "힐러 · 라바 하운드 · 벌룬",
    "spells": "분노 · 신속 · 얼음",
    "siege": "전투 비행선/석재 비행선",
    "heroes": "아처 퀸 선행",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 13,
    "nameKo": "로열 챔피언 다이브 + 드래곤",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h4e40_13-1e17_20-2m1e4_34-6e42_43i1x0-1x12-1x52-2x53d1x2u1x23-1x28-1x82-7x5-12x8-1x1s10x35-1x9",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 13,
    "nameKo": "Judo 쉬운 TH13 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0e8_1-1e17_39-2e4_34-4e7_40i1x0-1x12-2x53d1x5-1x9u2x1-1x28-10x53-11x83-1x87s1x2-3x5-6x28",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 13,
    "nameKo": "하이브리드",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=0u_buQhODBU",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2021-08-29",
    "coreUnits": "광부 · 호그 라이더 · 힐러",
    "spells": "치유 · 분노 · 얼음",
    "siege": "시즈 병영",
    "heroes": "퀸 차지 + 로열 챔피언",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 14,
    "nameKo": "다수 드래곤",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0p0e8_14-1p3e17_20-2m1p2e4_34-6e42_43i1x65-4x5d2x17u10x5-11x8-2x23-1x28-1x10s3x2-5x5",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 14,
    "nameKo": "일렉트로 드래곤",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h6p0e49_43-2m1p2e4_34-1p1e17_48-4p3e6_13i1x75-3x84-1x5-2x10d3x120u9x59-4x5-1x23s3x5-4x2",
    "videoUrl": "https://www.youtube.com/watch?v=W8UlCd2BdaE",
    "creator": "CorruptYT",
    "publishedDate": "2026-04-06",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 14,
    "nameKo": "다수 슈퍼 호그",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0p1e10_1-2m1p2e5_4-1p3e39_48-4p0e40_13i1x87-2x53-1x12-1x0d1x2-1x9u15x98-8x11-2x53-5x6-1x58-1x82-1x1-1x10s5x35-1x53-2x1",
    "videoUrl": "https://www.youtube.com/watch?v=W8UlCd2BdaE",
    "creator": "CorruptYT",
    "publishedDate": "2026-04-06",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 15,
    "nameKo": "슈퍼 예티 스매시",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h2p3e4_24-0p4e8_14-1p9e17_20-4p8e9_40i3x5-1x110-1x135-1x58d1x1-1x9u3x5-5x7-1x97-4x147-2x82-2x28-2x23-2x10-2x6-1x58-1x91-1x87-1x75s1x3-2x2-2x5-1x35-1x109-1x10",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 15,
    "nameKo": "루트 라이더 스매시",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h4p3e40_13-1p9e17_48-2p8e4_24-7p4e52_57i2x53-2x5-2x10-1x135d2x120-1x9u5x7-4x110-3x27-6x57-1x58-1x97-1x82-1x10-2x23-4x5-3x1s5x35-1x70-1x98-1x53",
    "videoUrl": "https://www.youtube.com/watch?v=fPnZQRp8joQ",
    "creator": "CorruptYT",
    "publishedDate": "2026-03-16",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 15,
    "nameKo": "다수 일렉트로 드래곤",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h6p4e49_43-1p9e17_48-2m1p2e4_34-7p8e52_57i1x75-4x84-1x10d1x2-1x9u9x59-1x28-5x57-1x10s2x2-7x5",
    "videoUrl": "https://www.youtube.com/watch?v=fPnZQRp8joQ",
    "creator": "CorruptYT",
    "publishedDate": "2026-03-16",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 설명에 제공된 Army Link",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 16,
    "nameKo": "로열 챔피언 다이브 + 루트 라이더·발키리",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h4p10e12_40-1p9e17_20-2p8e4_34-0p4e8_14i1x87-1x135-6x5-1x110d1x2-1x9u3x5-5x7-6x110-5x12-1x28-2x1-9x26-1x97-1x91-1x75-1x135s1x70-1x2-4x35-1x5-1x53",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 16,
    "nameKo": "Judo 쉬운 TH16 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h0p4e14_8-1p9e39_20-2p2e4_34-4p10e40_9i1x1-5x11-3x12d1x2-1x5u6x110-5x12-1x58-1x97-3x5-5x7-7x26-5x1-1x75s2x2-2x5-1x17-2x70",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 16,
    "nameKo": "슈퍼 아처 블림프 · 루트 라이더",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=mjJnEGmOpCA",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2023-12-12",
    "coreUnits": "슈퍼 아처 지원 · 루트 라이더",
    "spells": "분노 · 투명 · 얼음",
    "siege": "전투 비행선",
    "heroes": "영웅으로 진입로 정리",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 17,
    "nameKo": "로열 챔피언 다이브 + 루트 라이더·발키리",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h4p10e12_40-1p9e17_20-2p8e4_34-0p4e8_14i1x87-1x135-7x5-1x110d1x2-1x9u3x5-5x7-7x110-5x12-1x28-2x1-9x26-1x97-1x91-1x75-1x135s1x70-1x2-4x35-1x5-1x53",
    "videoId": "8mffnvOg_CE",
    "videoUrl": "https://www.youtube.com/watch?v=8mffnvOg_CE",
    "videoTitle": "Best Ranked Attack Strategy for Every Town Hall",
    "creator": "Judo Sloth Gaming",
    "handle": "@JudoSloth",
    "publishedDate": "2025-10-06",
    "sourceBasis": "영상 설명의 제작자 제공 Army Link 및 영상 자막",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용"
  },
  {
    "th": 17,
    "nameKo": "Judo 쉬운 TH17 조합",
    "copyArmyUrl": "https://link.clashofclans.com/en?action=CopyArmy&army=h4p4e40_12-1p9e20_17-2p16e4_34-6p11e42_43i1x75-1x62-4x84-1x6-1x55d1x2-1x35u17x8-1x91-1x75-1x135s11x35",
    "videoUrl": "https://www.youtube.com/watch?v=ahXtrhKqPM4",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-04-24",
    "coreUnits": "Army Link에 포함",
    "spells": "Army Link에 포함",
    "siege": "Army Link에 포함",
    "heroes": "Army Link에 포함",
    "note": "제작자 제공 Army Link 그대로 사용",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 17,
    "nameKo": "파이어볼 투척병",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=gxV53vgu2Ak",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2024-11-25",
    "coreUnits": "투척병 · 탱커",
    "spells": "분노 · 얼음/투명",
    "siege": "기지에 맞춰 선택",
    "heroes": "그랜드 워든 파이어볼 중심",
    "note": "영상 chapter의 전략명 기준; 정확한 수량은 기지에 맞춰 조정",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 18,
    "nameKo": "파이어볼 메테오 골렘",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=PcW_BtJmxTk",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-11-17",
    "coreUnits": "메테오 골렘 · 본대 지원",
    "spells": "분노 · 토템/얼음",
    "siege": "기지에 맞춰 선택",
    "heroes": "그랜드 워든 파이어볼 중심",
    "note": "Judo TH18 영상 chapter 기준; 공식 Army Link가 없어 구조화 텍스트만 제공",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 18,
    "nameKo": "정밀 일렉트로 드래곤",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=PcW_BtJmxTk",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-11-17",
    "coreUnits": "일렉트로 드래곤 · 벌룬 보조",
    "spells": "분노 · 얼음",
    "siege": "기지에 맞춰 선택",
    "heroes": "영웅으로 외곽 정리",
    "note": "Judo TH18 영상 chapter 기준; 공식 Army Link가 없어 구조화 텍스트만 제공",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 18,
    "nameKo": "루트 라이더 · 발키리",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=PcW_BtJmxTk",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-11-17",
    "coreUnits": "루트 라이더 · 발키리",
    "spells": "분노 · 얼음/투명",
    "siege": "기지에 맞춰 선택",
    "heroes": "영웅 본대 동행",
    "note": "Judo TH18 영상 chapter 기준; 공식 Army Link가 없어 구조화 텍스트만 제공",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  },
  {
    "th": 18,
    "nameKo": "퀸/워든 차지 리콜",
    "copyArmyUrl": null,
    "videoUrl": "https://www.youtube.com/watch?v=PcW_BtJmxTk",
    "creator": "Judo Sloth Gaming",
    "publishedDate": "2025-11-17",
    "coreUnits": "힐러 · 후속 본대",
    "spells": "분노 · 리콜 · 얼음",
    "siege": "기지에 맞춰 선택",
    "heroes": "퀸 또는 워든 차지 선행",
    "note": "Judo TH18 영상 chapter 기준; 공식 Army Link가 없어 구조화 텍스트만 제공",
    "sourceBasis": "영상 설명/챕터에 명시된 전략"
  }
];LAYOUTS.forEach(function(layout){layout.kindLabel=layout.kind==='war'?'전쟁·리그 배치':'파밍·자원 보호 배치';});return {CHECKED_DATE:'2026-08-10',TH_LEVELS:Array.from({length:15},function(_,i){return i+4}),LAYOUTS:LAYOUTS,ARMIES:ARMIES,STORE_URL:'https://store.supercell.com/ko/clashofclans'};}));
