(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SupercellGames=api;})(typeof self!=='undefined'?self:this,function(){
  'use strict';
  var GAME_IDS=['clash-of-clans','brawl-stars','boom-beach','clash-royale','hay-day'];
  function routine(id,label,target){return{id:id,label:label,target:target,progress:0};}
  function expected(id,title,category,rule){return{id:id,title:title,category:category,rule:rule,status:'EXPECTED',official:false};}
  function guide(title,summary){return{title:title,summary:summary,source:'플레이 메모 · 공식 아님'};}
  function creator(name,handle,authority){var item={name:name,channelUrl:'https://www.youtube.com/@'+handle,source:'공개 채널 주소'};if(authority)item.authority=authority;return item;}
  function feed(name,channelId){return{name:name,channelId:channelId,feedUrl:'https://www.youtube.com/feeds/videos.xml?channel_id='+channelId};}
  function seed(channelId,creatorName,videoId,title,published){return{channelId:channelId,creatorName:creatorName,videoId:videoId,title:title,published:published,videoUrl:'https://www.youtube.com/watch?v='+videoId,thumbnailUrl:'https://i.ytimg.com/vi/'+videoId+'/hqdefault.jpg',sourceState:'BUNDLED'};}
  function program(id,label,description,sourceUrl,activityFamily,cadence,actionKo,triggers){var item={id:id,label:label,description:description,status:'OFFICIAL_UNDATED',official:true,datePrecision:'NO_VERIFIED_DATE',activityFamily:activityFamily||'event-reward',cadence:cadence||'게임 내 공지 확인',actionKo:actionKo||'게임에서 참여 여부와 보상을 확인하세요.',sourceUrl:sourceUrl,asOf:'2026-08-12'};if(Array.isArray(triggers))item.triggers=triggers.slice();return item;}
  function playerCheck(id,label,description,activityFamily,cadence,actionKo){return{id:id,label:label,description:description,status:'PLAYER_NOTE',official:false,datePrecision:'NO_VERIFIED_DATE',activityFamily:activityFamily||'event-reward',cadence:cadence||'게임 내 확인',actionKo:actionKo||'게임에서 현재 상태를 확인하세요.',asOf:'2026-08-12'};}
  var games={
    'clash-of-clans':{nameKo:'클래시 오브 클랜',officialUrl:'https://supercell.com/en/games/clashofclans/',accent:'#ef6c3e',categories:['시즌','클랜전 리그','클랜 게임','주말 습격'],routines:[routine('clan-war','클랜전 공격',2),routine('cwl-daily','CWL 일일 공격',1),routine('raid-weekend','주말 습격 공격',6),routine('clan-games','클랜 게임 점수',10000)],timerTypes:[['builder','건설'],['lab','연구소'],['hero','영웅'],['pet','펫'],['equipment','장비'],['custom','기타']],guides:[guide('초반 자원 운영','보호막과 저장고 용량을 먼저 확인하세요.'),guide('클랜전 공격 점검','정찰과 지원 병력을 공격 전에 확인하세요.'),guide('영웅 장비 우선순위','주력 조합에 쓰는 장비부터 집중하세요.'),guide('주말 습격 협업','남은 공격과 지구 진행도를 공유하세요.')],creators:[creator('빠다','%EB%B9%A0%EB%8B%A4','PARTNER_STATUS_UNVERIFIED'),creator('Judo Sloth Gaming','JudoSloth','VERIFIED'),creator('Clash of Clans 공식','ClashofClans','OFFICIAL')],expectedRules:[expected('season','시즌 예상 패턴','시즌','월초 갱신 패턴'),expected('cwl','클랜전 리그 예상 패턴','리그','월초 반복 패턴'),expected('raid','주말 습격 예상 패턴','습격','금요일 시작 패턴')],officialSeeds:[]},
    'brawl-stars':{nameKo:'브롤스타즈',officialUrl:'https://supercell.com/en/games/brawlstars/',accent:'#f2b705',categories:['시즌','퀘스트','챔피언십'],routines:[routine('quests','퀘스트 진행',3),routine('starr-drops','스타 드롭 획득',3),routine('club-play','클럽 플레이',2),routine('ranked','랭크전 연습',3)],timerTypes:[['quest','퀘스트'],['event','이벤트 슬롯'],['ranked','랭크전'],['custom','기타']],guides:[guide('맵별 역할 확인','엄폐물과 공격 사거리에 맞춰 역할을 정하세요.'),guide('탄창 관리','교전 전에 탄창을 모두 소모하지 마세요.'),guide('조합 균형','딜러와 제어 역할의 균형을 확인하세요.'),guide('가젯 사용 기록','패배한 교전의 가젯 타이밍을 복기하세요.')],creators:[creator('Holit','holit92'),creator('Brawl Stars 공식','BrawlStars','OFFICIAL')],expectedRules:[expected('season','시즌 예상 패턴','시즌','시즌 주기 패턴'),expected('quests','퀘스트 예상 패턴','퀘스트','일일 갱신 패턴'),expected('challenge','도전 예상 패턴','챔피언십','반복 패턴')],officialSeeds:[]},
    'boom-beach':{nameKo:'붐비치',officialUrl:'https://supercell.com/en/games/boombeach/',accent:'#20a8d8',categories:['작전','워십','메가 크랩'],routines:[routine('task-force','태스크 포스 작전',1),routine('resource-base','자원 기지 확인',2),routine('warship','워십 전투',3),routine('scout','기지 정찰',3)],timerTypes:[['building','건설'],['armory','무기고'],['landing-craft','상륙정'],['custom','기타']],guides:[guide('연막 경로 설계','상륙 지점부터 본부까지 경로를 먼저 그리세요.'),guide('건보트 에너지','필수 능력 사용량을 공격 전에 계산하세요.'),guide('조각상 구성','공격 목표에 맞는 조각상 효과를 선택하세요.'),guide('태스크 포스 작전','공격 전 남은 방어 시설을 공유하세요.')],creators:[creator('The Chicken','TheChicken'),creator('Boom Beach 공식','BoomBeach','OFFICIAL'),creator('SkullCrusher Boom','SkullCrusherBoom')],expectedRules:[expected('operation','작전 예상 패턴','작전','태스크 포스 반복 패턴'),expected('warships','워십 예상 패턴','워십','시즌 주기 패턴'),expected('crab','메가 크랩 예상 패턴','메가 크랩','과거 반복 패턴')],officialSeeds:[]},
    'clash-royale':{nameKo:'클래시 로얄',officialUrl:'https://supercell.com/en/games/clashroyale/',accent:'#4a83e8',categories:['시즌','클랜전','토너먼트'],routines:[routine('clan-battle','클랜전 참여',4),routine('daily-tasks','일일 과제',3),routine('chests','상자 슬롯 확인',2),routine('deck-practice','덱 연습',3)],timerTypes:[['chest','상자'],['request','카드 요청'],['war','클랜전'],['custom','기타']],guides:[guide('엘릭서 교환','상대 카드 비용과 내 대응 비용을 기록하세요.'),guide('승리 조건 보호','주력 승리 조건을 불필요하게 수비에 쓰지 마세요.'),guide('순환 카드 추적','상대 핵심 카드의 다음 순서를 예상하세요.'),guide('연장전 운영','타워 체력과 주문 피해량을 미리 계산하세요.')],creators:[creator('JUNE','JUNECR'),creator('Clash Royale 공식','ClashRoyale','OFFICIAL')],expectedRules:[expected('season','시즌 예상 패턴','시즌','월간 주기 패턴'),expected('war','클랜전 예상 패턴','클랜전','주간 반복 패턴'),expected('tournament','토너먼트 예상 패턴','토너먼트','과거 반복 패턴')],officialSeeds:[]},
    'hay-day':{nameKo:'헤이데이',officialUrl:'https://supercell.com/en/games/hayday/',accent:'#72ad3c',categories:['더비','생산','방문 이벤트'],routines:[routine('derby','더비 과제',1),routine('production','생산 대기열',4),routine('boat','배 주문 확인',3),routine('town','마을 방문객',3)],timerTypes:[['production','생산'],['crop','작물'],['boat','배'],['custom','기타']],guides:[guide('생산 대기열','접속 간격에 맞춰 긴 생산품을 배치하세요.'),guide('창고 균형','확장 재료가 한 종류에 치우치지 않게 정리하세요.'),guide('더비 과제','완료 가능한 과제만 선택하고 남은 시간을 기록하세요.'),guide('배 주문 판단','보상과 재고 소모를 비교한 뒤 출항 여부를 정하세요.')],creators:[creator('Hay Day 공식','hayday','OFFICIAL'),creator('Hay Day Everyday','HayDayEveryday')],expectedRules:[expected('derby','더비 예상 패턴','더비','주간 반복 패턴'),expected('visitor','방문 이벤트 예상 패턴','방문 이벤트','과거 반복 패턴'),expected('production','생산 이벤트 예상 패턴','생산','과거 반복 패턴')],officialSeeds:[]}
  };
  var themes={
    'clash-of-clans':{heroImage:'assets/game-themes/clash-of-clans.webp',heroAltKo:'바바리안이 있는 클래시 오브 클랜 공식 배경',surface:'#482817',ink:'#fff4dd',actionKo:'마을의 다음 작전을 달력에서 먼저 확인하세요.'},
    'brawl-stars':{heroImage:'assets/game-themes/brawl-stars.png',heroAltKo:'브롤스타즈 셸리 캐릭터',surface:'#1754a5',ink:'#ffffff',actionKo:'셸리와 함께 오늘의 난투 일정을 빠르게 훑어보세요.'},
    'boom-beach':{heroImage:'assets/game-themes/boom-beach.png',heroAltKo:'붐비치 닥터 카반 캐릭터',surface:'#086b78',ink:'#f4ffff',actionKo:'상륙 전에 작전과 워십 일정을 먼저 정찰하세요.'},
    'clash-royale':{heroImage:'assets/game-themes/clash-royale.png',heroAltKo:'클래시 로얄 기사 카드 캐릭터',surface:'#173f81',ink:'#ffffff',actionKo:'아레나에 들어가기 전 시즌과 도전을 확인하세요.'},
    'hay-day':{heroImage:'assets/game-themes/hay-day.webp',heroAltKo:'헤이데이 공식 농장 배경',surface:'#356c24',ink:'#fffbea',actionKo:'농장의 배와 더비 일정을 여유롭게 챙겨보세요.'}
  };
  Object.keys(themes).forEach(function(id){games[id].theme=themes[id];});
  var DISPLAY_TITLES_KO={
    'clash-of-clans':{'Clash of Cards Event':'클래시 오브 카드 이벤트','New Crafted Defenses':'신규 제작 방어 시설','Mass Spell Event #1: Totem and Birth Boom Spells':'대규모 마법 이벤트 #1 · 토템 및 탄생 붐 마법','Mass Elephant Riders and Super Valkyries':'코끼리 기수·슈퍼 발키리 대규모 지원','Clan War League':'클랜전 리그','Clan Games':'클랜 게임','Awesome Medal Event':'어썸 메달 이벤트','Card Hunt':'카드 사냥'},
    'brawl-stars':{'Brawl Stars World Finals':'브롤스타즈 월드 파이널','Brawl Stars Challengers Finals':'브롤스타즈 챌린저스 파이널','Last Chance Qualifier':'라스트 찬스 퀄리파이어','Brawl Stars mode recommendations':'브롤스타즈 모드별 추천','Gem Grab':'젬 그랩','Brawl Ball':'브롤 볼','Heist':'하이스트','Bounty':'바운티','Hot Zone':'핫 존','Knockout':'녹아웃','Solo Showdown':'솔로 쇼다운','Duo Showdown':'듀오 쇼다운'},
    'boom-beach':{'Warships Season 90':'워십 시즌 90','Warships S90':'워십 시즌 90','Warships S91':'워십 시즌 91','Sonar Ops':'소나 작전','Tiny Shock':'타이니 쇼크','Deployable Turret':'배치형 포탑','Explosive Drones':'폭발 드론','Rocket Choppa & Laser Ranger Mania':'로켓 초파·레이저 레인저 마니아','Crystal Critters':'크리스털 크리터','Gunboat Crab':'건보트 크랩','Crystal Shield':'크리스털 실드','Heavy Mania':'헤비 마니아','Boom Beach attack principles':'붐비치 공격 원칙','Mechs + Bombardiers + Kavan':'메카 + 봄바디어 + 카반','Scorchers + Bombardiers + Laser Rangers + Kavan':'스코처 + 봄바디어 + 레이저 레인저 + 카반','Layout-specific Warriors':'기지 맞춤형 워리어','Smoky Zookas':'연막 주카','Stable mid-range firepower and healing':'안정적인 중거리 화력과 회복','High-health frontline with long-range damage':'높은 체력의 전열과 장거리 화력','Layout-specific direct HQ route':'기지에 맞춘 본부 직행 경로','Precise smoke path around key defenses':'핵심 방어시설을 피하는 정밀 연막 경로','Mechs screen for Bombardiers while Kavan sustains the formation.':'메카가 봄바디어를 보호하고 카반이 대형을 유지합니다.','Spread the frontline and manage Kavan survival around long-range units.':'전열을 넓게 펼치고 장거리 병력 주변에서 카반의 생존을 관리합니다.','Use only when shock coverage, pathing, and HQ access suit the layout.':'충격탄 범위와 이동 경로, 본부 접근이 기지에 맞을 때만 사용하세요.','Pre-plan smoke spacing and shock energy; execution errors are costly.':'연막 간격과 충격탄 에너지를 미리 계산하세요. 실행 실수의 대가가 큽니다.','Inspect the stage':'스테이지 먼저 확인','Adjust the loadout':'병력 구성 조정','Budget gunboat energy':'건보트 에너지 배분','Preserve the next attack':'다음 공격 준비','Check HQ health and priority defenses first.':'본부 체력과 우선 제거할 방어시설부터 확인하세요.','Adapt troops, hero, and abilities to each layout.':'기지마다 병력·영웅·능력을 맞춰 조정하세요.','Plan flare, smoke, shock, and barrage costs by stage.':'스테이지별 조명탄·연막·충격탄·포격 비용을 계획하세요.','A setup attack can be more valuable than a forced clear.':'무리한 완파보다 다음 공격을 위한 준비 공격이 더 가치 있을 수 있습니다.','Mega Crab layouts and modifiers are update-sensitive; verify them in game.':'메가 크랩 배치와 변형 요소는 업데이트에 따라 달라질 수 있으니 게임에서 확인하세요.'},
    'clash-royale':{'C.H.A.O.S Triple Draft':'C.H.A.O.S 트리플 드래프트','Epic Only Challenge':'에픽 카드 전용 도전','Sudden Death Challenge':'서든 데스 도전','Infinite Elixir Challenge':'무한 엘릭서 도전','Clash Royale editorial deck examples':'클래시 로얄 편집 덱 예시','Giant control example':'자이언트 컨트롤 예시','Hog EQ example':'호그 지진 예시','Royal Giant example':'로얄 자이언트 예시','Miner Wall Breakers example':'광부 월 브레이커 예시','Knight':'기사','Giant':'자이언트','Skeletons':'해골 병사','Valkyrie':'발키리','Bomber':'폭탄병','Musketeer':'머스킷병','Mini P.E.K.K.A':'미니 P.E.K.K.A','Spear Goblins':'창 고블린','Hog Rider':'호그 라이더','Royal Giant':'로얄 자이언트','Ice Spirit':'아이스 스피릿','Miner':'광부','Hunter':'사냥꾼','Bats':'박쥐','Wall Breakers':'월 브레이커','Fisherman':'낚시꾼','Magic Archer':'마법 아처','Firecracker':'폭죽병','Mother Witch':'마녀 엄마','Phoenix':'피닉스','Cannon':'대포','Bomb Tower':'폭탄 타워','Fireball':'파이어볼','Arrows':'화살','Lightning':'번개','Zap':'감전','The Log':'통나무','Earthquake':'지진'},
    'hay-day':{'Discover the new Boat Destinations in Hay Day!':'헤이데이의 새로운 배 목적지를 만나보세요!','Hay Day is expanding the Beach Area!':'헤이데이 해변 구역이 넓어집니다!','I\'m something of a musician myself...':'저도 제법 음악가랍니다…'}
  };
  DISPLAY_TITLES_KO['boom-beach']['Warships Season 91']='워십 시즌 91';
  Object.assign(DISPLAY_TITLES_KO['clash-of-clans'],{'Clash of Cards — Card Hunt':'클래시 오브 카드 — 카드 사냥','Supercell Store free card-pack tasks':'Supercell Store 무료 카드 팩 과제','August Gold Pass':'8월 골드 패스',"Chief's Chronicles":'족장의 연대기','Revenge Deck Boost':'복수 덱 부스트','Resource Fest & Work for Hire #2':'자원 축제 & 일꾼 고용 #2','Awesome Medal Trader/Event Building access':'어썸 메달 상인·이벤트 건물 이용 마감','Clash of Cards trading window':'클래시 오브 카드 거래 창 마감'});
  Object.assign(DISPLAY_TITLES_KO['brawl-stars'],{'Brawl Stars Challengers Finals 2026':'브롤스타즈 챌린저스 파이널 2026'});
  Object.assign(DISPLAY_TITLES_KO['clash-of-clans'],{'Gold Pass':'골드 패스','Friend or Foe Army Camps #1':'친구 혹은 적 아미 캠프 #1','Equipment Boost':'장비 부스트','Friend or Foe Army Camps #2':'친구 혹은 적 아미 캠프 #2','John Cena Challenge':'존 시나 챌린지','WWE Chests':'WWE 상자','Temporary WWE Troops':'WWE 기간 한정 유닛','Battle Options #1':'전투 옵션 #1','Money in the Bank Rush':'머니 인 더 뱅크 러시','WWE Equipment Blast':'WWE 장비 블래스트','Battle Options #2':'전투 옵션 #2','Resource Collector Boosts #1':'자원 생산 시설 부스트 #1','Resource Collector Boosts #2':'자원 생산 시설 부스트 #2'});
  Object.assign(DISPLAY_TITLES_KO['brawl-stars'],{'August 2026 game update (planned release)':'2026년 8월 업데이트 · 9월 1일 출시 계획','Duo Community Event / Duolingo collaboration':'듀오 커뮤니티 이벤트 · Duolingo 협업'});
  Object.assign(DISPLAY_TITLES_KO['boom-beach'],{'Hammerman Strikes Back (Threat)':'해머맨의 역습 (위협)','Dr. T Tropical':'Dr. T 열대 섬','Dr. T Volcano':'Dr. T 화산 섬','War Factory':'워 팩토리','Imitation Game':'이미테이션 게임','Warrior & Bombardier Mania':'워리어 & 봄바디어 마니아','Speed Serum':'스피드 세럼','Grenadier & Rocket Choppa Mania':'그레네이디어 & 로켓 초파 마니아','Cryo Bomb':'크라이오 폭탄','Beastly Crab':'비스트리 크랩','Leader Deployment Event':'리더 배치 이벤트','Joker Crab':'조커 크랩','Explosive Drones':'폭발 드론','Warships Season 92':'워십 시즌 92'});
  Object.assign(DISPLAY_TITLES_KO['clash-royale'],{'C.H.A.O.S Epic Only':'C.H.A.O.S 에픽 전용','C.H.A.O.S Sudden Death':'C.H.A.O.S 서든 데스',"Ken’s C.H.A.O.S Mega Draft — Global Tournament":'켄의 C.H.A.O.S 메가 드래프트 — 글로벌 토너먼트','C.H.A.O.S Infinite Elixir':'C.H.A.O.S 무한 엘릭서','Merge Tactics Season 11':'머지 택틱스 시즌 11'});
  Object.assign(DISPLAY_TITLES_KO['hay-day'],{'Neighborhood Derby':'이웃 더비'});
  function displayTitleKo(gameId,title){var raw=String(title||'');var map=DISPLAY_TITLES_KO[normalizeGameId(gameId)];return map&&map[raw]||raw;}
  games['clash-of-clans'].creatorFeeds=[feed('빠다','UCv45ttLI7WSM5YnNjIWDb8A'),feed('Judo','UC85aYbNSFjsJdxfpxgQr8tA')];
  games['clash-of-clans'].videoSeeds=[seed('UCv45ttLI7WSM5YnNjIWDb8A','빠다','kKZDvVGMnK8','전설 국내 1등은 무슨 조합을 쓸까?','2026-08-10T08:00:29Z'),seed('UCv45ttLI7WSM5YnNjIWDb8A','빠다','YDgn3dFBj44','반박자 빠른 클오클 소식입니다','2026-08-09T08:00:30Z'),seed('UCv45ttLI7WSM5YnNjIWDb8A','빠다','biSh1kfaCks','세계 1등도 쓰고 있는 날먹 조합 TOP 5','2026-08-08T08:00:35Z')];
  games['brawl-stars'].creatorFeeds=[feed('Holit','UCoH2pCzAr6zWDG-LtUiLWRw'),feed('공식','UCooVYzDxdwTtGYAkcPmOgOw')];
  games['brawl-stars'].creators.find(function(item){return item.name==='Holit';}).authority='PARTNER_STATUS_UNVERIFIED';
  games['brawl-stars'].videoSeeds=[seed('UCoH2pCzAr6zWDG-LtUiLWRw','홀릿','cXjpnOtBRfg','스무디드롭 보상 잘나오게 하는 방법을 제보 받았습니다.. 바로 테스트 ㄱㄱㄱ [브롤스타즈]','2026-08-09T22:30:32Z'),seed('UCoH2pCzAr6zWDG-LtUiLWRw','홀릿','3MnENhxlKHs','여러분이 날린거 100% 그대로 돌려준다는 갓겜 브롤스타즈ㄷㄷ','2026-08-09T10:00:36Z'),seed('UCoH2pCzAr6zWDG-LtUiLWRw','홀릿','BEpPCcl0-NE','이번 신규 전설&신화 스킨들 확률 진짜 이상합니다ㄷㄷ 못뽑는 사람이 이상한게 되어버림;; [브롤스타즈]','2026-08-08T23:00:23Z')];
  games['boom-beach'].creatorFeeds=[feed('The Chicken','UCVtCq_mSA6YpVV7FG5dYM-g'),feed('공식','UC3Xzm_n7d0jy726uHsTX7yA')];
  games['boom-beach'].videoSeeds=[seed('UCVtCq_mSA6YpVV7FG5dYM-g','The Chicken','7cwTJ7HmBkQ','Finally *DIAMOND* Season 90! // Boom Beach Warships','2026-08-10T10:00:29Z'),seed('UCVtCq_mSA6YpVV7FG5dYM-g','The Chicken','LRNRWtD47wI','Adding more DEFENSE in Season 90! // Boom Beach Warships','2026-08-09T10:00:14Z'),seed('UCVtCq_mSA6YpVV7FG5dYM-g','The Chicken','45CZzDNZk7I','Jump to 7er or Begin Backfill Parade? (Season 90) // Boom Beach Warships','2026-08-08T10:00:25Z')];
  games['clash-royale'].creatorFeeds=[feed('JUNE','UCL_IvtOZo6sONpiydbzzHpA'),feed('공식','UC_F8DoJf9MZogEOU51TpTbQ')];
  games['clash-royale'].videoSeeds=[seed('UCL_IvtOZo6sONpiydbzzHpA','JUNE','K7YX0Lp8Ib8','리메이크된 공허  [클래시로얄] [June]','2026-08-09T05:53:54Z'),seed('UCL_IvtOZo6sONpiydbzzHpA','JUNE','fBzkRypBXZg','히발통ㅋ [클래시로얄] [June]','2026-08-07T09:06:05Z'),seed('UCL_IvtOZo6sONpiydbzzHpA','JUNE','s2IycRZDwTA','미친X','2026-08-05T09:11:11Z')];
  games['hay-day'].creatorFeeds=[feed('공식','UCBrMq7wkdPWb3PxR-GUR61A'),feed('HayDayEveryday','UCGoJ4CNJj3BI3uslWV9nUsA')];
  games['hay-day'].videoSeeds=[seed('UCBrMq7wkdPWb3PxR-GUR61A','Hay Day 공식','HBBixe1Fvkk','Hay Day: Boat Destinations Trailer','2026-08-17T09:12:45Z'),seed('UCBrMq7wkdPWb3PxR-GUR61A','Hay Day 공식','P5tvEnzIsX0','Discover the new Boat Destinations in Hay Day!','2026-07-30T07:45:09Z'),seed('UCBrMq7wkdPWb3PxR-GUR61A','Hay Day 공식','MMoteNXoelw','Hay Day is expanding the Beach Area!','2026-06-29T07:45:29Z')];
  function official(id,title,start,end,category,source,evidence,precision){return{id:id,title:title,startDate:start,endDate:end,datePrecision:precision||'DATE_ONLY',sourceTimeZone:'UNPUBLISHED',category:category,description:evidence+' · 원문 날짜 범위 양끝 포함',status:'OFFICIAL',official:true,sourceUrl:source,sourceFamily:'SUPERCELL_ARCHIVE',verifiedAt:'2026-08-19',verifiedDate:'2026-08-19',lastVerifiedAt:'2026-08-18T21:04:12Z',sourceState:'BUNDLED'};}
  function startPoint(id,title,startInstant,pointDate,sourceUrls){return{id:id,title:title,startInstant:startInstant,pointDate:pointDate,datePrecision:'START_INSTANT_ONLY',timezone:'Asia/Seoul',sourceTimeZone:'UTC',category:'esports',description:'Official UTC start point: '+startInstant,status:'OFFICIAL',official:true,sourceUrl:sourceUrls[0],sourceUrls:sourceUrls.slice(),sourceFamily:'BRAWL_ESPORTS',verifiedAt:'2026-08-11',verifiedDate:'2026-08-11',lastVerifiedAt:'2026-08-11T00:00:00Z',sourceState:'BUNDLED'};}

  var awesomeSource='https://supercell.com/en/games/clashofclans/blog/news/the-awesome-quest-is-here/';
  var cardsSource='https://supercell.com/en/games/clashofclans/blog/news/clash-of-cards-event/';
  var chroniclesSource='https://supercell.com/en/games/clashofclans/blog/news/chiefs-chronicles-are-here/';
  games['clash-of-clans'].officialSeeds=[];
  var brawlSource='https://supercell.com/en/games/brawlstars/blog/esports/brawl-stars-world-finals-format/';
  games['brawl-stars'].officialSeeds=[official('brawl-stars-world-finals-2026','Brawl Stars World Finals','2026-11-20','2026-11-22','esports',brawlSource,'EVENT DATES: Friday 20 November to Sunday 22 November 2026')];
  var brawlEventSources=['https://event.supercell.com/brawlstars/v1/event','https://event.supercell.com/brawlstars/assets/events/en.json','https://event.supercell.com/brawlstars/assets/events/kr.json'];
  [['brawl-monthly-finals-2026-08-ea','브롤스타즈 챔피언십 2026 · 8월 월별 파이널 · 동아시아','2026-08-08T06:45:00Z','2026-08-08'],['brawl-monthly-finals-2026-08-emea','브롤스타즈 챔피언십 2026 · 8월 월별 파이널 · 유럽, 중동 및 아프리카','2026-08-09T11:45:00Z','2026-08-09'],['brawl-monthly-finals-2026-08-sa','브롤스타즈 챔피언십 2026 · 8월 월별 파이널 · 남아메리카','2026-08-15T18:45:00Z','2026-08-16'],['brawl-monthly-finals-2026-08-na','브롤스타즈 챔피언십 2026 · 8월 월별 파이널 · 북아메리카','2026-08-16T18:45:00Z','2026-08-17']].reverse().forEach(function(x){games['brawl-stars'].officialSeeds.unshift(startPoint(x[0],x[1],x[2],x[3],brawlEventSources));});
  var royaleSource='https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/';
  games['clash-royale'].officialSeeds=[];
  var boomSource='https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/';
  games['boom-beach'].officialSeeds=[];
  games['hay-day'].officialSeeds=[];

  /* Dated non-official material is deliberately separate from officialSeeds.  These
     rows are article-context or bounded projections and can never reach alerts. */
  function trusted(id,gameId,title,start,end,precision,category,family,source,quote,extra){var boom=gameId==='boom-beach',newBoom=boom&&source.indexOf('this-september-on-boom-beach-2')>=0,wwe=source.indexOf('wwe-search-for-cena')>=0,brawlTalk=source==='https://www.youtube.com/watch?v=qhvPlcwJUvk';return Object.assign({id:id,gameId:gameId,title:title,startDate:start,endDate:end,startInstant:null,endInstant:null,datePrecision:precision,category:category,eventFamily:family,status:'HIGH_CONFIDENCE',confidence:'HIGH',dateConfidence:'HIGH',timeConfidence:null,authority:'OFFICIAL_CONTEXT_YEAR',sourceUrl:source,sourceQuote:quote,verifiedAt:boom?null:wwe?'2026-09-01T08:40:42Z':brawlTalk?'2026-08-29T15:00:06Z':(['clash-of-clans','clash-royale'].indexOf(gameId)>=0?'2026-08-19T06:03:18Z':'2026-08-19T06:06:14Z'),verifiedDate:boom?(newBoom?'2026-08-30':'2026-08-19'):null,projectionStart:null,projectionEnd:null,expiry:null,filterTags:[],official:false,timezone:null,sourceTimeZone:'UNKNOWN',changeNotice:'일정은 변경될 수 있습니다.'},extra||{});}
  function recurrence(id,gameId,title,family,authority,confidence,source,quote,revision,weekdays,starts,timedUtc){var hay=gameId==='hay-day',exactTime=hay||timedUtc===true;return{id:id,gameId:gameId,title:title,eventFamily:family,status:'EXPECTED',confidence:confidence,dateConfidence:confidence,timeConfidence:hay?'MEDIUM_HIGH':null,authority:authority,sourceUrl:source,sourceQuote:quote,sourceRevision:revision,verifiedAt:hay?'2026-08-19T06:06:14Z':null,verifiedDate:hay?null:'2026-08-19',projectionStart:hay?'2026-08-18':'2026-08-19',projectionEnd:'2026-09-29',expiry:hay?'2026-10-05':'2026-09-29',category:hay?'derby':'event',filterTags:[hay?'derby':'cycle-of-evil'],official:false,timezone:exactTime?'Asia/Seoul':null,sourceTimeZone:exactTime?'UTC':'UNKNOWN',weekdays:weekdays,starts:starts||[],changeNotice:'반복 규칙 기반 예상이며 변경될 수 있습니다.'};}
  function contextRows(gameId,source,rows){return rows.map(function(x){return trusted(x[0],gameId,x[1],x[2],x[3],x[4]||'DATE_ONLY_RANGE',x[5],x[6],source,x[7],x[8]);});}
  games['clash-of-clans'].trustedCalendarRecords=contextRows('clash-of-clans',awesomeSource,[
    ['coc-clash-of-cards','Clash of Cards Event','2026-08-01','2026-08-31',null,'special-event','CLASH_OF_CARDS','August 1-31: Clash of Cards Event'],
    ['coc-card-hunt','Clash of Cards — Card Hunt','2026-08-01','2026-08-31',null,'special-event','CARD_HUNT','Card Hunt (Aug 1-31) - The main event.',{sourceUrl:cardsSource}],
    ['coc-store-card-tasks','Supercell Store free card-pack tasks','2026-08-03','2026-08-30',null,'special-event','STORE_CARD_TASKS','SC Store (Aug 3-30) - Complete exclusive tasks in the SC Store for free card packs',{sourceUrl:cardsSource}],
    ['coc-august-gold-pass','August Gold Pass','2026-08-01','2026-08-31',null,'season','GOLD_PASS','August 1-31: Gold Pass'],
    ['coc-chiefs-chronicles',"Chief's Chronicles",'2026-08-08','2026-08-31','MIXED_START_INSTANT_END_DATE','special-event','CHIEFS_CHRONICLES',"Chief’s Chronicles runs from August 8 (8:00 UTC) through August 31.",{sourceUrl:chroniclesSource,startInstant:'2026-08-08T08:00:00Z',timezone:'Asia/Seoul',sourceTimeZone:'UTC'}],
    ['coc-awesome-medal','Awesome Medal Event','2026-08-12','2026-08-31','INSTANT_RANGE','medal-event','AWESOME_MEDAL','Event starts: August 12, 08:00 UTC. Event ends: August 31, 08:00 UTC.',{sourceUrl:'https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/',startInstant:'2026-08-12T08:00:00Z',endInstant:'2026-08-31T08:00:00Z',timezone:'Asia/Seoul',sourceTimeZone:'UTC'}],
    ['coc-clan-games','Clan Games','2026-08-22','2026-08-28',null,'clan-games','CLAN_GAMES','August 22-28: Clan Games'],
    ['coc-revenge-deck','Revenge Deck Boost','2026-08-26','2026-08-31',null,'special-event','REVENGE_DECK','Equipment boost: from August 26-31, Revenge Deck gets boosted…',{sourceUrl:'https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/'}],
    ['coc-resource-fest-2','Resource Fest & Work for Hire #2','2026-08-29','2026-08-31',null,'special-event','RESOURCE_FEST','August 29-31: Resource Fest & Work for Hire #2'],
    ['coc-medal-access-end','Awesome Medal Trader/Event Building access','2026-09-02','2026-09-02','END_INSTANT_ONLY','medal-event','AWESOME_MEDAL_ACCESS',"The Trader's Event tab and Event Building stay accessible until September 2, 08:00 UTC",{sourceUrl:'https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/',endInstant:'2026-09-02T08:00:00Z',timezone:'Asia/Seoul',sourceTimeZone:'UTC'}],
    ['coc-card-trading-end','Clash of Cards trading window','2026-09-02','2026-09-02','END_INSTANT_ONLY','special-event','CARD_TRADING','On September 2nd at 08:00 AM UTC, the trading window closes',{sourceUrl:cardsSource,endInstant:'2026-09-02T08:00:00Z',timezone:'Asia/Seoul',sourceTimeZone:'UTC'}]
  ]);
  var wweSource='https://supercell.com/en/games/clashofclans/blog/news/wwe-search-for-cena-steps-into-the-ring/';
  games['clash-of-clans'].trustedCalendarRecords=games['clash-of-clans'].trustedCalendarRecords.concat(contextRows('clash-of-clans',wweSource,[
    ['coc-september-gold-pass','Gold Pass','2026-09-01','2026-09-30',null,'season','SEPTEMBER_GOLD_PASS','September 1-30: Gold Pass'],
    ['coc-september-cwl','Clan War League','2026-09-01','2026-09-11',null,'clan-war-league','SEPTEMBER_CWL','September 1-11: Clan War League'],
    ['coc-john-cena-challenge','John Cena Challenge','2026-09-01','2026-09-30',null,'challenge','JOHN_CENA_CHALLENGE','September 1-30: John Cena Challenge'],
    ['coc-wwe-chests','WWE Chests','2026-09-01','2026-09-30',null,'special-event','WWE_CHESTS','September 1-30: WWE Chests'],
    ['coc-temporary-wwe-troops','Temporary WWE Troops','2026-09-01','2026-09-30',null,'troop-event','TEMP_WWE_TROOPS','September 1-30: Temp Troops'],
    ['coc-battle-options-1','Battle Options #1','2026-09-01','2026-09-06',null,'special-event','BATTLE_OPTIONS_1','September 1-6: Battle Options'],
    ['coc-money-in-the-bank-rush','Money in the Bank Rush','2026-09-01','2026-09-05',null,'special-event','MONEY_IN_THE_BANK_RUSH','September 1-5: Money in the Bank Rush'],
    ['coc-friend-or-foe-army-camps-1','Friend or Foe Army Camps #1','2026-09-06','2026-09-09',null,'troop-event','FRIEND_OR_FOE_ARMY_CAMPS_1','September 6-9: Friend or Foe Army Camps'],
    ['coc-wwe-equipment-blast','WWE Equipment Blast','2026-09-09','2026-09-22',null,'equipment-event','WWE_EQUIPMENT_BLAST','September 9-22: WWE Equipment Blast'],
    ['coc-battle-options-2','Battle Options #2','2026-09-09','2026-09-22',null,'special-event','BATTLE_OPTIONS_2','September 9-22: Battle Options #2'],
    ['coc-resource-collector-boosts-1','Resource Collector Boosts #1','2026-09-12','2026-09-14',null,'resource-boost','RESOURCE_COLLECTOR_BOOSTS_1','September 12-14: Resource Collector Boosts'],
    ['coc-equipment-boost','Equipment Boost','2026-09-16','2026-09-21',null,'equipment-event','EQUIPMENT_BOOST','September 16-21: Equipment Boost'],
    ['coc-september-clan-games','Clan Games','2026-09-22','2026-09-28',null,'clan-games','SEPTEMBER_CLAN_GAMES','September 22-28: Clan Games'],
    ['coc-resource-collector-boosts-2','Resource Collector Boosts #2','2026-09-26','2026-09-28',null,'resource-boost','RESOURCE_COLLECTOR_BOOSTS_2','September 26-28: Resource Collector Boosts'],
    ['coc-friend-or-foe-army-camps-2','Friend or Foe Army Camps #2','2026-09-28','2026-09-30',null,'troop-event','FRIEND_OR_FOE_ARMY_CAMPS_2','September 28-30: Friend or Foe Army Camps']
  ]));games['clash-of-clans'].trustedCalendarRules=[];
  games['brawl-stars'].trustedCalendarRecords=contextRows('brawl-stars','https://supercell.com/en/games/brawlstars/blog/esports/brawl-stars-challengers-finals-format--2/',[
    ['brawl-challengers-finals-2026','Brawl Stars Challengers Finals 2026','2026-09-05','2026-09-06','MIXED_START_INSTANT_END_DATE','esports','CHALLENGERS_FINALS','Brawl Stars Challengers Final takes place September 5-6 at the ESA Espor Arena in Istanbul, Turkiye. Venue doors will open at 10:30am local times (09:30 CEST) each day. The show will start at 11:00am (subject to change).',{startInstant:'2026-09-05T08:00:00Z',timezone:'Asia/Seoul',sourceTimeZone:'Europe/Istanbul',timeConfidence:'MEDIUM_HIGH',changeNotice:'11:00 시작 시각은 변경될 수 있습니다.'}]
  ]);
  games['brawl-stars'].trustedCalendarRecords=games['brawl-stars'].trustedCalendarRecords.concat(contextRows('brawl-stars','https://www.youtube.com/watch?v=qhvPlcwJUvk',[
    ['brawl-update-planned-2026-09-01','August 2026 game update (planned release)','2026-09-01','2026-09-01','START_DATE_ONLY','game-update','PLANNED_UPDATE','We are planning to release this update on September 1st, but if this information turns out to be false, blame Danny.',{channelId:'UCooVYzDxdwTtGYAkcPmOgOw',changeNotice:'계획된 시작일 · 공식 영상의 변경 가능성 문구 유지'}],
    ['brawl-duo-community-event-2026-09-19','Duo Community Event / Duolingo collaboration','2026-09-19','2026-09-19','START_DATE_ONLY','community-event','DUO_COMMUNITY_EVENT','The event starts on September 19th.',{channelId:'UCooVYzDxdwTtGYAkcPmOgOw',changeNotice:'종료일 미공개 · Chaos Drops 및 무료 Spike'}]
  ]));games['brawl-stars'].trustedCalendarRules=[];
  games['boom-beach'].trustedCalendarRecords=contextRows('boom-beach',boomSource,[
    ['boom-crystal-critters','Crystal Critters','2026-08-17','2026-08-19',null,'event','CRYSTAL_CRITTERS','17 - 19: Crystal Critters'],['boom-gunboat-crab','Gunboat Crab','2026-08-21','2026-08-23',null,'event','GUNBOAT_CRAB','21 - 23: Gunboat Crab'],['boom-crystal-shield','Crystal Shield','2026-08-24','2026-08-26',null,'event','CRYSTAL_SHIELD','24 - 26: Crystal Shield'],['boom-warships-91','Warships Season 91','2026-08-24','2026-09-13',null,'warships','WARSHIPS_SEASON','24 Aug - 13 Sept: Warships Season 91'],['boom-sonar-ops','Sonar Ops','2026-08-28','2026-09-06',null,'operation','SONAR_OPS','28 Aug - 6 Sept: Sonar Ops'],['boom-heavy-mania','Heavy Mania','2026-08-28','2026-08-30',null,'mania','HEAVY_MANIA','28 - 30: Heavy Mania']
  ]);
  var boomSeptemberSource='https://supercell.com/en/games/boombeach/blog/blog/this-september-on-boom-beach-2/';
  games['boom-beach'].trustedCalendarRecords=games['boom-beach'].trustedCalendarRecords.concat(contextRows('boom-beach',boomSeptemberSource,[
    ['boom-deployable-turret','Deployable Turret','2026-08-31','2026-09-02',null,'event','DEPLOYABLE_TURRET','31 Aug - 2 Sept: Deployable Turret'],
    ['boom-warrior-bombardier-mania','Warrior & Bombardier Mania','2026-09-04','2026-09-06',null,'mania','WARRIOR_BOMBARDIER_MANIA','4 - 6: Warrior & Bombardier Mania'],
    ['boom-speed-serum','Speed Serum','2026-09-07','2026-09-09',null,'event','SPEED_SERUM','7 - 9: Speed Serum'],
    ['boom-grenadier-rocket-choppa-mania','Grenadier & Rocket Choppa Mania','2026-09-11','2026-09-13',null,'mania','GRENADIER_ROCKET_CHOPPA_MANIA','11 - 13: Grenadier & Rocket Choppa Mania'],
    ['boom-cryo-bomb','Cryo Bomb','2026-09-14','2026-09-16',null,'event','CRYO_BOMB','14 - 16: Cryo Bomb'],
    ['boom-beastly-crab','Beastly Crab','2026-09-18','2026-09-20',null,'event','BEASTLY_CRAB','18 - 20: Beastly Crab'],
    ['boom-leader-deployment','Leader Deployment Event','2026-09-18','2026-09-24',null,'event','LEADER_DEPLOYMENT','18 - 24: Leader Deployment Event'],
    ['boom-crystal-critters-september','Crystal Critters','2026-09-21','2026-09-23',null,'event','CRYSTAL_CRITTERS','21 - 23: Crystal Critters'],
    ['boom-joker-crab','Joker Crab','2026-09-25','2026-09-27',null,'event','JOKER_CRAB','25 - 27: Joker Crab'],
    ['boom-explosive-drones-september','Explosive Drones','2026-09-28','2026-09-30',null,'event','EXPLOSIVE_DRONES','28 - 30: Explosive Drones'],
    ['boom-warships-92','Warships Season 92','2026-09-28','2026-10-18',null,'warships','WARSHIPS_SEASON_92','28 Sept - 18 Oct: Warships Season 92']
  ]));
  games['boom-beach'].trustedCalendarRules=[
    recurrence('boom-cycle-hammerman','boom-beach','Hammerman Strikes Back (Threat)','CYCLE_HAMMERMAN','COMMUNITY_MAINTAINED_SECONDARY','MEDIUM','https://boombeach.fandom.com/wiki/Hammerman_Strikes_Back_(Threat)','This event starts on Monday at 8 a.m. GMT and lasts for 24 hours.','2026-08-17T13:17:59Z',[1],[],true),
    recurrence('boom-cycle-dr-t-tropical','boom-beach','Dr. T Tropical','CYCLE_DR_T_TROPICAL','COMMUNITY_MAINTAINED_SECONDARY','MEDIUM','https://boombeach.fandom.com/wiki/Dr._T','Thereafter, the tropical Dr. T challenge will appear on the island of the defeated base every Tuesday and Saturday.','2026-08-15T20:58:20Z',[2,6]),
    recurrence('boom-cycle-dr-t-volcano','boom-beach','Dr. T Volcano','CYCLE_DR_T_VOLCANO','COMMUNITY_MAINTAINED_SECONDARY','MEDIUM','https://boombeach.fandom.com/wiki/Dr._T',"Dr. T's volcano challenge will appear every Wednesday and Sunday.",'2026-08-15T20:58:20Z',[3,0]),
    recurrence('boom-cycle-war-factory','boom-beach','War Factory','CYCLE_WAR_FACTORY','COMMUNITY_MAINTAINED_SECONDARY','MEDIUM','https://boombeach.fandom.com/wiki/The_War_Factory','The War Factory is an event that takes place every Thursday after beating the first War Factory, which is accessible after exploring at least 93 regions on the Archipelago.','2026-08-20T08:53:44Z',[4]),
    recurrence('boom-cycle-imitation','boom-beach','Imitation Game','CYCLE_IMITATION','COMMUNITY_MAINTAINED_SECONDARY','MEDIUM','https://boombeach.fandom.com/wiki/Imitation_Game','The Imitation Game is an event that occurs on Fridays in the event cycle. Like the other events, it lasts for 24 hours, appearing at 8 am GMT.','2026-08-17T13:17:34Z',[5],[],true)
  ];
  ['boom-cycle-dr-t-tropical','boom-cycle-war-factory','boom-cycle-imitation'].forEach(function(id){games['boom-beach'].trustedCalendarRules.find(function(item){return item.id===id;}).verifiedDate='2026-08-25';});
  games['clash-royale'].trustedCalendarRecords=contextRows('clash-royale',royaleSource,[
    ['cr-chaos-triple-draft','C.H.A.O.S Triple Draft','2026-08-17','2026-09-07',null,'challenge','CHAOS_TRIPLE_DRAFT','C.H.A.O.S Triple Draft: August 17th – Sept 7th'],['cr-chaos-epic-only','C.H.A.O.S Epic Only','2026-08-17','2026-08-24',null,'challenge','CHAOS_EPIC_ONLY','C.H.A.O.S Epic Only: August 17th – 24th'],['cr-chaos-sudden-death','C.H.A.O.S Sudden Death','2026-08-24','2026-08-31',null,'challenge','CHAOS_SUDDEN_DEATH','C.H.A.O.S Sudden Death: August 24th – 31st'],['cr-kens-mega-draft','Ken’s C.H.A.O.S Mega Draft — Global Tournament','2026-08-24','2026-08-29',null,'challenge','CHAOS_MEGA_DRAFT','Ken’s C.H.A.O.S Mega Draft: August 24th – 29th'],['cr-chaos-infinite-elixir','C.H.A.O.S Infinite Elixir','2026-08-31','2026-09-07',null,'challenge','CHAOS_INFINITE_ELIXIR','C.H.A.O.S Infinite Elixir: August 31st – Sept 7th'],['cr-merge-tactics-11','Merge Tactics Season 11','2026-09-01','2026-12-01',null,'season','MERGE_TACTICS_11','Season 11 will run from September 1st to December 1st, with no monthly resets!',{sourceUrl:'https://supercell.com/en/games/clashroyale/blog/release-notes/merge-tactics-season-11/',verifiedAt:'2026-08-29T18:00:30Z'}]
  ]);games['clash-royale'].trustedCalendarRules=[];
  games['hay-day'].trustedCalendarRecords=[];
  games['hay-day'].trustedCalendarRules=[recurrence('hay-derby','hay-day','Neighborhood Derby','HAY_DERBY','OFFICIAL_RECURRENCE_RULE','MEDIUM_HIGH','https://support.supercell.com/hay-day/en/articles/about-the-derby.html','This event starts from 8 AM UTC on Tuesdays and ends at 8 AM UTC the following Monday.','2026-08-19T06:06:14Z',[],['2026-08-18','2026-08-25','2026-09-01','2026-09-08','2026-09-15','2026-09-22','2026-09-29'])];
  function trustedTags(gameId,item){if(gameId==='clash-of-clans'){if(/clan-games/.test(item.id))return['clan-games'];if(/(?:cwl|clan-war-league)/.test(item.id)||item.category==='clan-war-league')return['league'];if(item.id==='coc-august-gold-pass'||item.id==='coc-september-gold-pass')return['season-pass'];if(item.id==='coc-store-card-tasks')return['free'];return['official-news'];}if(gameId==='brawl-stars')return item.id==='brawl-challengers-finals-2026'?['championship']:['events-quests'];if(gameId==='boom-beach'){if(/crab/.test(item.id))return['mega-crab'];if(/mania/.test(item.id))return['troop-mania'];if(/warships/.test(item.id))return['warships'];if(item.id==='boom-sonar-ops')return['sonar-ops'];return['abilities-boosts'];}if(gameId==='clash-royale'){if(item.category==='season')return['season-pass'];if(/draft/i.test(item.title))return['challenge','draft'];return['challenge','special-modes'];}return['derby'];}
  Object.keys(games).forEach(function(gameId){(games[gameId].trustedCalendarRecords||[]).forEach(function(item){item.filterTags=trustedTags(gameId,item);});});
  Object.keys(games).forEach(function(id){games[id].trustedConflictCatalog=(games[id].trustedCalendarRecords||[]).map(function(e){return{eventFamily:e.eventFamily,titles:[e.title]};});});

  var brawlProgramsSource='https://supercell.com/en/games/brawlstars/blog/release-notes/release-notes-june-2026/';
  games['clash-of-clans'].inGamePrograms=[program('cards-tutorial-pack','클래시 오브 카드 튜토리얼 팩','첫 로그인과 튜토리얼 완료 보상이며 달력 날짜는 공개되지 않았습니다.',cardsSource),program('cards-social-drops','클래시 오브 카드 소셜 드롭','공식 소셜 드롭은 예고됐지만 날짜는 공개되지 않았습니다.',cardsSource),program('clashiversary-cake-return','클래시버서리 케이크 복귀','공식 복귀가 예고됐지만 날짜는 공개되지 않았습니다.',awesomeSource)];
  games['brawl-stars'].inGamePrograms=[program('windstock-season','윈드스톡 시즌','연결된 두 시즌 중 윈드스톡 테마 시즌입니다.',brawlProgramsSource),program('smoothie-drops','스무디 드롭','게임 플레이로 스무디 드롭 보상을 확인하는 항목입니다.',brawlProgramsSource),program('topple-the-tower','탑플 더 타워','공식 릴리스 노트에 명시된 게임 모드이며 정확한 현재 기간은 공개되지 않았습니다.',brawlProgramsSource),program('brawl-pass','브롤 패스','브롤 패스 상품과 스킨은 Store 및 게임에서 확인합니다.','https://store.supercell.com/brawlstars'),program('ramen-rebellion','라면 반란','공식 스토리 이벤트지만 전체 기간은 공개되지 않았습니다.','https://www.youtube.com/watch?v=INe4L0S4xMs')];
  games['boom-beach'].inGamePrograms=[program('boom-pass','붐 패스','붐 패스 상품의 현재 제공 여부는 게임과 Store에서 확인합니다.','https://store.supercell.com/boombeach')];
  games['clash-royale'].inGamePrograms=[program('pass-royale','로얄 패스','로얄 패스 상품의 현재 제공 여부는 게임과 Store에서 확인합니다.','https://store.supercell.com/clashroyale'),program('khaos-season','K.H.A.O.S 시즌','공식 시즌 전체의 정확한 범위는 공개되지 않았습니다.',royaleSource),program('unleash-the-beast','야수 해방','공식 영웅 해금 이벤트지만 자체 기간은 공개되지 않았습니다.',royaleSource),program('hero-valkyrie-availability','영웅 발키리 해금','공식 해금 가능 시점은 시즌 시작으로만 표현됐습니다.',royaleSource),program('kens-shop','켄의 상점','공식 한정 상점이지만 정확한 기간은 공개되지 않았습니다.',royaleSource),program('custom-chaos-tournaments','커스텀 C.H.A.O.S 드래프트 토너먼트','공식 향후 토너먼트 기능이지만 날짜는 공개되지 않았습니다.',royaleSource)];
  games['hay-day'].inGamePrograms=[program('farm-pass','농장 패스','농장 패스 상품의 현재 제공 여부는 게임과 Store에서 확인합니다.','https://store.supercell.com/hayday'),program('neighborhood-derby','이웃 더비','이웃과 함께하는 더비의 현재 일정은 게임에서 확인합니다.','https://hayday.com/en/'),program('valley','밸리','밸리 활동의 현재 상태는 게임에서 확인합니다.','https://hayday.com/en/'),program('global-community-events','글로벌 커뮤니티 이벤트','글로벌 커뮤니티 이벤트의 현재 날짜는 게임에서 확인합니다.','https://hayday.com/en/'),program('future-panda-event','판다 이벤트 예정','판다가 향후 이벤트로 농장을 방문할 예정이지만 날짜는 공개되지 않았습니다.','https://x.com/hayday/status/2084247923471335917')];
  var wendyBoxes=program('wendy-boxes-check','웬디 박스 무료 해금','Wendy Boxes를 모아 Wendy를 무료로 해금하세요. Wendy Side Quests에서는 Smoothie Drops도 받을 수 있으며 날짜는 공개되지 않았습니다.','https://www.youtube.com/watch?v=niPhOjGey4k','event-reward','게임 내 이벤트','게임에서 Wendy Boxes와 Wendy Side Quests 진행도를 확인하세요.');wendyBoxes.asOf='2026-08-25';wendyBoxes.sourceQuote='Collect Wendy Boxes to unlock Wendy for FREE!';games['brawl-stars'].inGamePrograms.push(wendyBoxes);
  var khaosTokens=program('free-khaos-tokens-check','무료 K.H.A.O.S 토큰 확인','공식 영상에 무료 K.H.A.O.S 토큰이 안내됐지만 마감일은 공개되지 않았습니다. 게임의 이벤트, 상점, 증정 항목을 확인하세요.','https://www.youtube.com/watch?v=iFE2uv7Gd1o','event-reward','게임 내 증정','게임에서 이벤트, 상점, 증정 항목을 확인하세요.');khaosTokens.asOf='2026-08-25';khaosTokens.sourceQuote='FREE K.H.A.O.S Tokens!';games['clash-royale'].inGamePrograms.push(khaosTokens);
  var evolvedEliteBarbarians=program('kens-shop-evolved-elite-barbarians-check','켄의 상점 진화 엘리트 바바리안 안내 확인','공식 글은 무료 획득 문구 뒤에 가능 여부를 되묻습니다. 날짜와 확정 조건이 공개되지 않았으므로 게임 내 켄의 상점에서 실제 제공 여부를 확인하세요.',royaleSource,'event-reward','게임 내 상점','게임에서 켄의 상점과 진화 엘리트 바바리안 제공 여부를 확인하세요.');evolvedEliteBarbarians.asOf='2026-08-26';evolvedEliteBarbarians.sourceQuote='You can get Evolved Elite Barbarians for free in Ken’s Shop... or can you?';games['clash-royale'].inGamePrograms.push(evolvedEliteBarbarians);
  var qrReward=program('qr-reward-check','공식 영상 QR 보상 확인','공식 영상의 QR 보상에 공개된 만료일이 없습니다. 공식 영상에서 바로 수령을 시도하고 게임에서 적용 여부를 확인하세요.','https://www.youtube.com/watch?v=P5tvEnzIsX0','event-reward','1회 수령 확인','공식 영상을 열어 QR 보상을 수령하고 게임에서 확인하세요.');qrReward.asOf='2026-08-25';qrReward.sourceQuote='Claim the QR code: https://link.haydaygame.com/?action=voucher&code=2eb763ba-a587-4fb9-8389-5f80e37f49c7';games['hay-day'].inGamePrograms.push(qrReward);
  var cocFinalsReward=program('august-finals-view-rewards-check','8월 월별 파이널 시청 보상 확인','공식 방송 설명은 시청 보상을 안내하지만 보상 가능 종료 시각을 공개하지 않았습니다. 공식 이벤트 페이지에서 현재 수령 가능 여부를 확인하세요.','https://www.youtube.com/watch?v=MWbK-CLnPHY','event-reward','방송 중 확인','공식 이벤트 페이지에서 로그인 후 현재 보상 진행 상태를 확인하세요.');cocFinalsReward.asOf='2026-08-30';cocFinalsReward.sourceQuote='Tune in to event.supercell.com/clashofclans for in-game rewards! 🛍️';games['clash-of-clans'].inGamePrograms.push(cocFinalsReward);
  var brawlTalkFreebie=program('brawl-talk-freebie-20260829','브롤 토크 무료 보상','공식 브롤 토크 설명에 무료 보상 링크가 있지만 만료일은 공개되지 않았습니다. 즉시 공식 영상 링크에서 수령 가능 여부를 확인하세요.','https://www.youtube.com/watch?v=qhvPlcwJUvk','event-reward','1회 수령 확인','공식 브롤 토크를 열어 무료 보상 수령을 시도하고 게임에서 확인하세요.');brawlTalkFreebie.asOf='2026-08-30';brawlTalkFreebie.sourceQuote='Brawl Talk Freebie! - https://link.brawlstars.com/voucher/04b98c55-f411-4656-bbec-ef47b46ef1fa';games['brawl-stars'].inGamePrograms.push(brawlTalkFreebie);
  var hedgehogQr=program('hedgehog-qr-reward-check','고슴도치 공식 영상 QR 보상 확인','공식 영상 설명에 QR 보상 링크가 있지만 만료일은 공개되지 않았습니다. 즉시 공식 영상에서 수령 가능 여부를 확인하세요.','https://www.youtube.com/watch?v=E1SpXe2u30M','event-reward','1회 수령 확인','공식 영상을 열어 QR 보상 수령을 시도하고 게임에서 확인하세요.');hedgehogQr.asOf='2026-08-30';hedgehogQr.sourceQuote='Claim the QR code: https://link.haydaygame.com/?action=voucher&code=0e7ba42d-57f8-47ba-a963-d47a05aee3a4';games['hay-day'].inGamePrograms.push(hedgehogQr);
  games['clash-of-clans'].inGamePrograms=games['clash-of-clans'].inGamePrograms.concat([
    program('gold-pass-check','골드 패스','시즌 도전과 보상 트랙은 게임에서 현재 상태를 확인합니다.','https://store.supercell.com/clashofclans','pass','시즌제','게임에서 패스 보상과 남은 과제를 확인하세요.'),
    playerCheck('raid-weekend','습격 주말','공격 횟수와 수도 골드는 클랜별 게임 상태에서 확인하는 플레이 체크입니다.','weekly','주말 활동','게임에서 공격 횟수와 수도 골드를 확인하세요.'),
    playerCheck('clan-war','클랜전','매칭과 공격 기회는 클랜별 게임 상태에서 확인하는 플레이 체크입니다.','weekly','클랜 일정','게임에서 전쟁 상태와 남은 공격을 확인하세요.'),
    playerCheck('clan-capital-forge','클랜 수도 대장간','제작 슬롯과 수령 가능 보상을 확인하는 플레이 체크입니다.','daily','주기적 확인','게임에서 제작 슬롯과 수령 가능 보상을 확인하세요.'),
    playerCheck('season-challenges','시즌 도전','진행 가능한 도전과 보상 트랙을 확인하는 플레이 체크입니다.','season','시즌제','게임에서 진행 가능한 도전과 보상을 확인하세요.')
  ]);
  var smoothie=games['brawl-stars'].inGamePrograms.find(function(item){return item.id==='smoothie-drops';});
  smoothie.description='일일 승리, 메가 퀘스트, 탑플 더 타워, 사이드 퀘스트, 크리에이터 QR 코드로 획득합니다.';
  smoothie.triggers=['Daily Wins','Mega Quests','Topple the Tower','Side Quests','Creator QR codes'];
  smoothie.activityFamily='event-reward';smoothie.cadence='활동별 획득';smoothie.actionKo='게임에서 각 획득 경로와 보상을 확인하세요.';
  games['brawl-stars'].inGamePrograms=games['brawl-stars'].inGamePrograms.concat([
    program('daily-wins','일일 승리','일일 승리로 시즌 드롭 보상을 획득하는 활동입니다.',brawlProgramsSource,'daily','매일','게임에서 오늘의 승리 진행도를 확인하세요.'),
    program('mega-quests','메가 퀘스트','메가 퀘스트는 나노드롭과 스무디 드롭 획득 경로입니다.',brawlProgramsSource,'weekly','게임 내 갱신','게임에서 활성 메가 퀘스트를 확인하세요.'),
    program('side-quests','사이드 퀘스트','사이드 퀘스트로 두 시즌의 드롭 보상을 획득할 수 있습니다.',brawlProgramsSource,'event-reward','게임 내 갱신','게임에서 활성 사이드 퀘스트를 확인하세요.'),
    program('daily-contests','일일 콘테스트','매일 열리는 콘테스트의 참가와 순위 보상을 확인합니다.',brawlProgramsSource,'daily','매일','게임에서 오늘의 콘테스트와 점수를 확인하세요.'),
    program('boss-fights','보스전','보스전은 나노드롭 획득 경로로 안내된 활동입니다.',brawlProgramsSource,'event-reward','게임 내 활성 시','게임에서 활성 보스와 보상을 확인하세요.'),
    program('creator-qr-drops','크리에이터 QR 드롭','공식 크리에이터 QR 코드로 시즌 드롭을 획득할 수 있습니다.',brawlProgramsSource,'event-reward','코드 공개 시','공식 QR 코드를 확인하고 게임에서 보상을 받으세요.')
  ]);
  var brawlPass=games['brawl-stars'].inGamePrograms.find(function(item){return item.id==='brawl-pass';});brawlPass.activityFamily='pass';brawlPass.cadence='시즌제';brawlPass.actionKo='게임에서 패스 진행도와 받을 보상을 확인하세요.';
  games['boom-beach'].inGamePrograms=games['boom-beach'].inGamePrograms.concat([
    playerCheck('imitation-game','이미테이션 게임','공식 웹 날짜가 검증되지 않은 악의 순환 활동입니다.','daily','게임 내 순환','게임에서 이미테이션 게임 활성 여부와 보상을 확인하세요.'),
    playerCheck('hammerman-strikes-back','해머맨의 역습','공식 웹 날짜가 검증되지 않은 악의 순환 활동입니다.','daily','게임 내 순환','게임에서 해머맨의 역습 활성 여부와 보상을 확인하세요.'),
    playerCheck('dr-t-island','박사의 섬 (Dr. T)','공식 웹 날짜가 검증되지 않은 악의 순환 활동입니다.','daily','게임 내 순환','게임에서 박사의 섬 활성 상태와 보상을 확인하세요.'),
    program('task-force-operation','태스크 포스 작전','공식 게임 페이지가 태스크 포스 협동 공격을 설명하며, 현재 작전 상태는 게임에서 확인합니다.','https://supercell.com/en/games/boombeach/','weekly','부대 일정','게임에서 작전 상태와 남은 공격을 확인하세요.'),playerCheck('cycle-of-evil','악의 순환','오늘의 적과 보상 상태를 확인하는 플레이 체크입니다.','daily','순환 활동','게임에서 오늘의 적과 보상을 확인하세요.'),program('warships-check','워십 확인','현재 워십 시즌, 티어와 전투 진행도를 확인합니다.',boomSource,'season','시즌제','게임에서 현재 워십 시즌과 보상을 확인하세요.'),program('mega-crab-check','메가 크랩 확인','메가 크랩의 등장과 스테이지 보상은 게임에서 확인합니다.',boomSource,'event-reward','공식 공지 확인','게임에서 활성 여부와 다음 스테이지를 확인하세요.'),program('prototype-troops-check','프로토타입 병력 확인','공식 월간 일정에 등장하는 기간 한정 병력·능력의 사용 가능 여부를 확인합니다.',boomSource,'event-reward','게임 내 활성 시','게임에서 사용할 수 있는 병력과 혜택을 확인하세요.')
  ]).filter(function(item){return item.id!=='cycle-of-evil';});
  var boomPass=games['boom-beach'].inGamePrograms.find(function(item){return item.id==='boom-pass';});boomPass.activityFamily='pass';boomPass.cadence='시즌제';boomPass.actionKo='게임에서 패스 과제와 보상을 확인하세요.';
  games['clash-royale'].inGamePrograms=games['clash-royale'].inGamePrograms.concat([
    playerCheck('ranked-season','랭크 시즌','현재 리그와 보상 진행도를 확인하는 플레이 체크입니다.','season','시즌제','게임에서 현재 리그와 보상을 확인하세요.'),playerCheck('clan-war','클랜전','클랜별 전쟁 상태와 남은 덱을 확인하는 플레이 체크입니다.','weekly','클랜 일정','게임에서 전쟁 상태와 남은 덱을 확인하세요.'),playerCheck('daily-tasks','일일 과제','오늘의 과제와 보상을 확인하는 플레이 체크입니다.','daily','매일','게임에서 오늘의 과제와 보상을 확인하세요.'),playerCheck('season-shop','시즌 상점','시즌 재화와 교환 목록을 확인하는 플레이 체크입니다.','event-reward','시즌제','게임에서 재화와 교환 목록을 확인하세요.'),playerCheck('global-tournaments','글로벌 토너먼트','현재 참가 가능 여부와 보상을 확인하는 플레이 체크입니다.','event-reward','게임 내 공지 확인','게임에서 참가 상태와 보상을 확인하세요.')
  ]);
  var royalePass=games['clash-royale'].inGamePrograms.find(function(item){return item.id==='pass-royale';});royalePass.activityFamily='pass';royalePass.cadence='시즌제';royalePass.actionKo='게임에서 패스 진행도와 보상을 확인하세요.';
  games['hay-day'].inGamePrograms=games['hay-day'].inGamePrograms.concat([
    program('task-events','새로운 과제 이벤트','공식 영상은 새 유형의 과제 이벤트를 소개하지만 날짜 범위는 공개하지 않습니다.','https://www.youtube.com/watch?v=JuA0-uBQLlg','event-reward','게임 내 활성 시','게임에서 과제 조건과 보상을 확인하세요.'),program('neighborhood-events','새로운 이웃 이벤트','공식 영상은 새 이웃 이벤트를 소개하지만 날짜 범위는 공개하지 않습니다.','https://www.youtube.com/watch?v=aozAlhU4x8E','event-reward','게임 내 활성 시','게임에서 이웃 이벤트 참여 상태를 확인하세요.'),program('boat-destinations','새로운 배 목적지','공식 영상은 새 배 목적지를 소개하지만 날짜 범위는 공개하지 않습니다.','https://www.youtube.com/watch?v=P5tvEnzIsX0','event-reward','게임 내 활성 시','게임에서 배 목적지와 주문을 확인하세요.')
  ]);
  var passFamilies={'clash-of-clans':'gold-pass-check','brawl-stars':'brawl-pass','boom-beach':'boom-pass','clash-royale':'pass-royale','hay-day':'farm-pass'};
  Object.keys(passFamilies).forEach(function(gameId){var item=games[gameId].inGamePrograms.find(function(row){return row.id===passFamilies[gameId];});item.activityFamily='pass';item.cadence=item.cadence||'시즌제';item.actionKo=item.actionKo||'게임에서 패스 진행도와 보상을 확인하세요.';});
  function filters(rows){return rows.map(function(row){return{id:row[0],label:row[1]};});}
  function assign(items,tagger){items.forEach(function(item){item.filterTags=tagger(item);});}
  games['clash-of-clans'].calendarFilters=filters([['all','전체'],['official-news','공식'],['free','무료·보상'],['league','리그전'],['clan-games','클랜 게임'],['raid','습격전'],['season-pass','시즌·패스']]);
  assign(games['clash-of-clans'].officialSeeds,function(item){var tags=['official-news'];if(/reward|free|medal|card pack|Card Hunt|tutorial/i.test(item.id+' '+item.title))tags.push('free');if(item.id.indexOf('clan-war-league')===0)tags.push('league');if(item.id.indexOf('clan-games')===0)tags.push('clan-games');return tags;});
  assign(games['clash-of-clans'].inGamePrograms,function(item){return['official-news'].concat(/팩|드롭|케이크/.test(item.label)?['free']:[]);});
  games['clash-of-clans'].expectedRules[0].filterTags=['official-news'];games['clash-of-clans'].expectedRules[1].filterTags=['league'];games['clash-of-clans'].expectedRules[2].filterTags=['raid'];
  games['clash-of-clans'].inGamePrograms.find(function(item){return item.id==='gold-pass-check';}).filterTags.push('season-pass');
  games['brawl-stars'].calendarFilters=filters([['all','전체'],['championship','챔피언십'],['season-pass','시즌·패스'],['events-quests','이벤트·퀘스트'],['game-modes','게임 모드']]);
  assign(games['brawl-stars'].officialSeeds,function(item){return item.category==='esports'?['championship']:['events-quests'];});
  assign(games['brawl-stars'].inGamePrograms,function(item){if(/season|pass/.test(item.id))return['season-pass'];if(/topple/.test(item.id))return['game-modes'];return['events-quests'];});
  games['brawl-stars'].expectedRules[0].filterTags=['season-pass'];games['brawl-stars'].expectedRules[1].filterTags=['events-quests'];games['brawl-stars'].expectedRules[2].filterTags=['championship'];
  games['boom-beach'].calendarFilters=filters([['all','전체'],['cycle-of-evil','악의 순환'],['mega-crab','메가 크랩'],['troop-mania','병력 훈련·마니아'],['warships','워십'],['sonar-ops','소나 작전'],['abilities-boosts','능력·부스트'],['pass-rewards','패스·보상']]);
  assign(games['boom-beach'].officialSeeds,function(item){if(item.id==='gunboat-crab')return['mega-crab'];if(item.category==='mania')return['troop-mania'];if(item.category==='warships')return['warships'];if(item.category==='operation')return['sonar-ops'];return['abilities-boosts'];});
  assign(games['boom-beach'].inGamePrograms,function(item){if(/^(imitation-game|hammerman-strikes-back|dr-t-island)$/.test(item.id))return['cycle-of-evil'];if(item.id==='boom-pass')return['pass-rewards'];if(item.id==='warships-check')return['warships'];if(item.id==='mega-crab-check')return['mega-crab'];if(item.id==='task-force-operation')return['sonar-ops'];return['abilities-boosts'];});
  games['boom-beach'].expectedRules[1].filterTags=['warships'];games['boom-beach'].expectedRules[2].filterTags=['mega-crab'];
  games['boom-beach'].officialSeeds.forEach(function(item){if(item.id==='gunboat-crab'){item.filterAliases=['Gunboat Crab'];item.description+=' · 공식 글에서 메가 크랩의 귀환으로 안내합니다.';}if(item.category==='mania')item.description+=' · Mania/boost · 정확한 훈련 혜택은 게임 내 확인';});
  games['clash-royale'].calendarFilters=filters([['all','전체'],['season-pass','시즌·패스'],['challenge','도전'],['draft','드래프트'],['special-modes','특수 모드'],['shop-unlocks','상점·해금']]);
  assign(games['clash-royale'].officialSeeds,function(item){var tags=['challenge'];if(/draft/i.test(item.title))tags.push('draft');else if(/Epic Only|Sudden Death|Infinite Elixir/i.test(item.title))tags.push('special-modes');if(item.category==='season')tags=['season-pass'];return tags;});
  assign(games['clash-royale'].inGamePrograms,function(item){if(/pass|season/.test(item.id))return['season-pass'];if(/tournament/.test(item.id))return['draft'];return['shop-unlocks'];});
  games['clash-royale'].expectedRules[0].filterTags=['season-pass'];games['clash-royale'].expectedRules[2].filterTags=['challenge'];
  games['hay-day'].calendarFilters=filters([['all','전체'],['farm-pass','농장 패스'],['derby','더비'],['valley','밸리'],['community','커뮤니티'],['future-events','예정 이벤트']]);
  assign(games['hay-day'].inGamePrograms,function(item){return[item.id==='farm-pass'?'farm-pass':item.id==='neighborhood-derby'?'derby':item.id==='valley'?'valley':item.id==='global-community-events'?'community':'future-events'];});
  games['hay-day'].expectedRules[0].filterTags=['derby'];games['hay-day'].expectedRules[1].filterTags=['future-events'];games['hay-day'].expectedRules[2].filterTags=['future-events'];
  games['clash-of-clans'].storeUrl='https://store.supercell.com/clashofclans';
  games['brawl-stars'].storeUrl='https://store.supercell.com/brawlstars';
  games['boom-beach'].storeUrl='https://store.supercell.com/boombeach';
  games['clash-royale'].storeUrl='https://store.supercell.com/clashroyale';
  games['hay-day'].storeUrl='https://store.supercell.com/hayday';
  function clone(value){return JSON.parse(JSON.stringify(value));}
  function normalizeGameId(value){return typeof value==='string'&&GAME_IDS.indexOf(value)!==-1?value:null;}
  function getGame(id){id=normalizeGameId(id);return id?clone(Object.assign({id:id},games[id])):null;}
  function normalizedTitle(value){return String(value||'').trim().toLowerCase().replace(/\s+/g,' ');}
  function categoryFallback(gameId,category){var map={
    'brawl-stars':{esports:['championship']},
    'boom-beach':{mania:['troop-mania'],warships:['warships'],operation:['sonar-ops']},
    'clash-royale':{season:['season-pass'],challenge:['challenge']}
  };return map[gameId]&&map[gameId][category]?map[gameId][category].slice():[];}
  function filterTagsForEvent(gameId,event){gameId=normalizeGameId(gameId);if(!gameId||!event||typeof event!=='object')return[];if(gameId==='brawl-stars'&&event.eventScope==='COMMUNITY_ESPORTS_APPLICATION')return['championship'];var title=normalizedTitle(event.title);if(gameId==='boom-beach'&&title===normalizedTitle('Gunboat Crab'))return['mega-crab'];if(gameId==='boom-beach'&&/mania/.test(title))return['troop-mania'];var seed=games[gameId].officialSeeds.find(function(item){if(item.id===event.id)return true;var names=[item.title].concat(item.filterAliases||[]).map(normalizedTitle);return !!title&&names.indexOf(title)!==-1;});return seed?(seed.filterTags||[]).slice():categoryFallback(gameId,event.category);}
  function normalizeExternalUrl(raw){if(typeof raw!=='string')return null;var official=/^https:\/\/supercell\.com\/en\/games\/(clashofclans|brawlstars|boombeach|clashroyale|hayday)\/$/.test(raw);var exact=['https://event.supercell.com/brawlstars/v1/event','https://event.supercell.com/brawlstars/assets/events/en.json','https://event.supercell.com/brawlstars/assets/events/kr.json','https://supercell.com/en/games/brawlstars/blog/release-notes/release-notes-june-2026/','https://supercell.com/en/games/brawlstars/blog/esports/brawl-stars-world-finals-format/','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-quest-is-here/','https://supercell.com/en/games/clashofclans/blog/news/clash-of-cards-event/','https://supercell.com/en/games/clashofclans/blog/news/chiefs-chronicles-are-here/','https://supercell.com/en/games/clashofclans/blog/news/the-awesome-medal-event-is-here/','https://supercell.com/en/games/clashofclans/blog/release-notes/august-update-3/','https://supercell.com/en/games/clashroyale/blog/news/new-season-k-h-a-o-s/','https://supercell.com/en/games/boombeach/blog/blog/this-august-on-boom-beach-2/','https://supercell.com/en/games/brawlstars/blog/esports/brawl-stars-challengers-finals-format--2/','https://supercell.com/en/games/brawlstars/blog/esports/brawl-stars-challengers-finals-tickets-available-now-2/','https://supercell.com/en/games/brawlstars/blog/esports/last-chance-qualifier-format-2','https://support.supercell.com/hay-day/en/articles/about-the-derby.html','https://boombeach.fandom.com/wiki/Hammerman_Strikes_Back_(Threat)','https://boombeach.fandom.com/wiki/Dr._T','https://boombeach.fandom.com/wiki/The_War_Factory','https://boombeach.fandom.com/wiki/Imitation_Game','https://www.youtube.com/post/UgkxrJcqzgtVh99kIcgU3w0h3IAkL1SSzNbA','https://www.youtube.com/watch?v=fnY1uD3z4WU','https://www.youtube.com/watch?v=INe4L0S4xMs','https://www.youtube.com/watch?v=P5tvEnzIsX0','https://www.youtube.com/watch?v=JuA0-uBQLlg','https://www.youtube.com/watch?v=aozAlhU4x8E','https://x.com/hayday/status/2084247923471335917'];var hay=raw==='https://hayday.com/en/'||raw==='https://hayday.com/en';var store=/^https:\/\/store\.supercell\.com\/(clashofclans|brawlstars|boombeach|clashroyale|hayday)$/.test(raw);var channel=/^https:\/\/www\.youtube\.com\/@(%EB%B9%A0%EB%8B%A4|JudoSloth|ClashofClans|holit92|BrawlStars|BoomBeach|SkullCrusherBoom|JUNECR|ClashRoyale|hayday|HayDayEveryday)$/.test(raw);return official||exact.indexOf(raw)!==-1||hay||store||channel?raw:null;}
  var normalizeKnownExternalUrl=normalizeExternalUrl;normalizeExternalUrl=function(raw){return/^(?:https:\/\/www\.youtube\.com\/watch\?v=niPhOjGey4k|https:\/\/www\.youtube\.com\/watch\?v=iFE2uv7Gd1o|https:\/\/www\.youtube\.com\/watch\?v=MWbK-CLnPHY|https:\/\/www\.youtube\.com\/watch\?v=qhvPlcwJUvk|https:\/\/www\.youtube\.com\/watch\?v=E1SpXe2u30M|https:\/\/supercell\.com\/en\/games\/boombeach\/blog\/blog\/this-september-on-boom-beach-2\/|https:\/\/supercell\.com\/en\/games\/clashroyale\/blog\/release-notes\/merge-tactics-season-11\/|https:\/\/supercell\.com\/en\/games\/clashofclans\/blog\/news\/wwe-search-for-cena-steps-into-the-ring\/)$/.test(String(raw||''))?raw:normalizeKnownExternalUrl(raw);};
  return Object.freeze({GAME_IDS:Object.freeze(GAME_IDS.slice()),getGame:getGame,normalizeGameId:normalizeGameId,normalizeExternalUrl:normalizeExternalUrl,filterTagsForEvent:filterTagsForEvent,displayTitleKo:displayTitleKo});
});
